### ISSUE TITLE
1.18整合包崩溃

### ISSUE THREAD

**Issue by Shapaper** [BloCamLimb/ModernUI#100]
[debug.log](https://github.com/BloCamLimb/ModernUI/files/8500993/debug.log)
[latest.log](https://github.com/BloCamLimb/ModernUI/files/8500994/latest.log)
[crafttweaker.log](https://github.com/BloCamLimb/ModernUI/files/8500995/crafttweaker.log)
![image](https://user-images.githubusercontent.com/88654772/163700619-bac70974-67dd-49dd-a88e-b7062864f581.png)

**Comment by BloCamLimb** [comment]
你的Forge版本太低了，你是39.1.0，需要39.1.2
