### ISSUE TITLE
[Bug] 1.18.2 crash during loading state

### ISSUE THREAD

**Issue by L-time** [BloCamLimb/ModernUI#101]
**Describe the bug**

The game crash in the loading state with Quark Mod.

**To Reproduce**

1.install Quark-3.2-349 and MUI-1.18.2-3.43.102

2.Start Game

3.Crash

**Expected behavior**

Crash,and nothing to happen.

**Screenshots**

Provided Crash Report.

**Environment**
 - Mod Version:3.43.102
 - Forge Version:40.1.0
 - Operating System:Windows 11
 - Graphics Card:GTX 1660
 - Other Mods:Quark
[crash-2022-04-23_18.04.18-client.txt](https://github.com/BloCamLimb/ModernUI/files/8546673/crash-2022-04-23_18.04.18-client.txt)
[crash-2022-04-23_18.03.45-client.txt](https://github.com/BloCamLimb/ModernUI/files/8546674/crash-2022-04-23_18.03.45-client.txt)

**Comment by BloCamLimb** [comment]
It's a Chat Heads bug.

**Comment by qznfbnj** [comment]
我刚刚用最新的 Forge 40.1.0 测试 Quark 和 modernui 并不冲突，无法再现同样的崩溃……
![quark-modernui](https://user-images.githubusercontent.com/100760086/164964421-da93796a-7889-45fe-8e82-ac2699210d41.png)
![quark-modernui-2](https://user-images.githubusercontent.com/100760086/164964615-3e35a0f3-b677-4b26-bd2d-8ffff7706ec0.png)
（题外话：我想起我之前有段时间启动崩溃测出来是 Chat Heads 和 Quark 冲突，不过 modernui 也会在崩溃报告中出现。但是不装 Chat Heads 单独装 Quark 和 modernui又没事……搞不懂……）

**Comment by BloCamLimb** [comment]
Chat Heads和这俩都冲突，而且它的版本还是1.18.1的

**Comment by qznfbnj** [comment]
> Chat Heads和这俩都冲突，而且它的版本还是1.18.1的

反正我最后还是选了夸克，因为Chat Heads最后的更新都有四个月了，对于这种虽然标了1.18.2但却是1.18.1能在1.18.2上运行的情况，就不奢求兼容性了（逃
