### ISSUE TITLE
[Bug] 1.16.5，在与rubidium一同使用时 log 被刷屏

### ISSUE THREAD

**Issue by liu13755305** [BloCamLimb/ModernUI#103]
确实能用,日常使用也不会崩溃，但是log会被刷屏。玩了两个的小时mc发现latestlog有2g那么大。

一直在刷这句话：
[Render thread/WARN]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: modern_text

**Environment**
 - Mod Version:2.7.1.105
 - Forge Version:36.2.34
 - Operating System:win10
 - Graphics Card:RTX2060super
 - Other Mods:oculus,rubidium

![image](https://user-images.githubusercontent.com/74533409/165086407-116e95c9-4e71-44a2-aeba-8aef27d162f2.png)

**Comment by BloCamLimb** [comment]
无解

**Comment by OcrSu** [comment]
加个delogger之类的模组，屏蔽一下
或者资助作者开发一个这样的模组/斜眼笑

**Comment by Kasualix** [comment]
https://www.mcmod.cn/class/3783.html
可以用这个模组，编辑一下配置文件，把这种log给扬了。

**Comment by OcrSu** [comment]
> https://www.mcmod.cn/class/3783.html 可以用这个模组，编辑一下配置文件，把这种log给扬了。

很有意思的mod，谢谢分享
