### ISSUE TITLE
[Bug] 1.16.5 crash on startup, Unsupported Class Version error

### ISSUE THREAD

**Issue by Kaleidio** [BloCamLimb/ModernUI#104]
**Describe the bug**
compile script configuration makes the VM believe MixinConnector is attempting to use methods present in class formats above furthest supported v52.

**Expected behavior**
If this is because code was backported from the recent version, refactor the codebase build script to ensure it compiles against the correct Java VM format.

**Environment**
 - Mod Version: 1.16.5-2.7.1.105-universal (though can be as late as 2.6.0.88)
 - Forge Version: 36.2.34
 - Operating System: Windows 10
 - Graphics Card: RTX 3080
 - Other Mods: Kaleidio's Battle Pack 5.0.0-beta5 dev instance

**Comment by Kaleidio** [comment]
1.16.5-2.7.1.105-universal

**Comment by Kaleidio** [comment]
https://pastebin.com/1n77sAwy

**Comment by Kaleidio** [comment]
happens on builds starting from 2.6.0.88

**Comment by BloCamLimb** [comment]
You should note that supported Java version starts with 11, Java 8 (your version) is not supported.

**Comment by Kaleidio** [comment]
I feel that is a bit much to ask for folks who are making modpacks, as their users don't tend to understand how to install a new java vm version.  but understood, I will keep using the old version from now on.

**Comment by DragarX** [comment]
Not sure why this issue was closed. Java 11+ is not fully supported with forge on 1.16.5, this really limits the compatibility with other mods and mod packs
Maybe you could have a legacy version built with java 8 for use in mod packs?

**Comment by BloCamLimb** [comment]
This issue is closed because it's duplicate. There's no other reason than the version is no longer supported. Version 2.6~2.7 uses a backport of V3 text engine. Only 2.5 supports Java 8 because it uses the V2 text engine. Currently, 3.5 uses V4 text engine.
