### ISSUE TITLE
[Bug] Localhost server not starting

### ISSUE THREAD

**Issue by DTX3** [BloCamLimb/ModernUI#105]
**Describe the bug**
When starting up my server with this mod installed, the server doesn't load.

**Crash log**
Mod File: ModernUI-1.18.2-3.4.5.106-universal.jar
Failure message: Modern UI (modernui) has failed to load correctly
java.lang.reflect.InvocationTargetException: null
Mod Version: 3.4.5.106
Mod Issue URL: https://github.com/BloCamLimb/ModernUI/issues
Exception message: java.lang.ClassNotFoundException: org.lwjgl.system.CustomBuffer

[Full log](https://controlc.com/19649c3c)

**Environment**
 - Mod Version: 1.18.2
 - Forge Version: 40.1.0
 - Operating System: Win 10
 - Graphics Card: 1080ti

**Comment by BloCamLimb** [comment]
From the CR, I can't tell if it only happens on Modern UI. Even if you don't have any mod, you can't start the server. You should check whether the server can find the lwjgl library.

**Comment by BloCamLimb** [comment]
There's a slim version for server https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3827595
