### ISSUE TITLE
[Suggestion] Add config for tooltip fade-in duration

### ISSUE THREAD

**Issue by goodtrailer** [BloCamLimb/ModernUI#106]
ModernUI's tooltip looks really nice, and the fade-in is cool. However, I find the speed at which it fades in too slow. There's already an option for menu background blur duration, so it makes sense to have a tooltip fade-in duration as well.

Playing on: [1.18.2-3.4.5.106](https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3765945)

**Comment by BloCamLimb** [comment]
Added in 3.4.6
