### ISSUE TITLE
[Bug] 导致Iceberg的自动换行功能失效

### ISSUE THREAD

**Issue by Dr-WeiAL** [BloCamLimb/ModernUI#107]
**Describe the bug**
ModernUI和Iceberg一起使用的时候会导致自动换行功能失效，有些很长的字段就超出屏幕了

**To Reproduce**
1. 安装这两个mod
2. 找一个很长的字段，例如NBT

**Expected behavior**
可以修复这个兼容性问题吗

**Screenshots**
![image](https://user-images.githubusercontent.com/47446553/172068284-c9626667-767b-4e17-af7c-2ba5e52c7d62.png)
![image](https://user-images.githubusercontent.com/47446553/172068408-f718ffce-a83d-4649-9414-99ad16e5fd30.png)

**Environment**
 - Mod Version: 3.4.5.106
 - Forge Version: 40.1.25
 - Operating System: Windows10
 - Graphics Card: RTX2060
 - Other Mods: Iceberg

**Comment by Dr-WeiAL** [comment]
好像是字体的问题(
把bootstrap文件里的值改成1就没这问题了

**Comment by BloCamLimb** [comment]
并非ModernUI问题，你知道很多模组写的就是大粪

**Comment by link-fgfgui** [comment]
> 好像是字体的问题( 把bootstrap文件里的值改成1就没这问题了

请问可以教下改成啥样吗?
