### ISSUE TITLE
[Bug] 1.18.2, Crash when entering world with Shimmer

### ISSUE THREAD

**Issue by qznfbnj** [BloCamLimb/ModernUI#108]
**Describe the bug**
Install Shimmer-1.18.2-0.4 and ModernUI-1.18.2-3.4.5.106-universal, then crash on entering world.
Each of them can work fine alone.
The latest.log file: https://gist.github.com/qznfbnj/abd2d13a6b4c46a9520f32932c1722ef
BakaXL的日志: https://gist.github.com/qznfbnj/2c80c0fb46c137bc4a762776db0af023

**To Reproduce**
1. Install Forge-40.1.48
2. Install Shimmer-1.18.2-0.4
3. Install ModernUI-1.18.2-3.4.5.106-universal
3. Enter a world
4. Crash

**Expected behavior**
After world 100% loaded, game crash.
【补充：将 config\ModernUI\bootstrap 中的 0 改为 1 关闭文本引擎，就能同时使用 Shimmer-1.18.2-0.4 和 ModernUI-1.18.2-3.4.5.106-universal】

**Screenshots**

**Environment**
 - Mod Version: 1.18.2-3.4.5.106
 - Forge Version: 40.1.48
 - Operating System: Windows11
 - Graphics Card: Geforce MX150
 - Other Mods: Shimmer-1.18.2-0.4

**Comment by BloCamLimb** [comment]
Paste your debug.log and crash-report

**Comment by qznfbnj** [comment]
> Paste your debug.log and crash-report

The debug.log file: https://gist.github.com/qznfbnj/47a2a2299f2e032f413251582d279f61
There is no crash-report.

**Comment by qznfbnj** [comment]
> > Paste your debug.log and crash-report
> 
> The debug.log file: https://gist.github.com/qznfbnj/47a2a2299f2e032f413251582d279f61 There is no crash-report.

The debug.log (create a new world) file: https://gist.github.com/qznfbnj/cfb1ddef3419fa4a7d19059b140d3370

**Comment by BloCamLimb** [comment]
The log shows nothing about the crash. I'll test it myself later.

**Comment by qznfbnj** [comment]
It seems like shimmer has add compatibility with ModernUI
https://github.com/Low-Drag-MC/Shimmer/issues/11#issuecomment-1152072361
Do I need to close this issue?
