### ISSUE TITLE
Font issue with § symbol

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#11]
In default minecraft, the color code § always escaped regardless of its usage (means §a is green color but §j is not a valid color)
Some servers use not valid color code sometimes like example of the images. So it may look dirty.
Here's the comparison images. (Item Description)

https://imgur.com/a/VrHo9AQ

There's a mod named SmoothFont, which doesn't make this issue.

you can also test this with command /give @s stone{display:{Name:'"\\\\u00a7jinvalid color code"'}}
A test stone item named §jinvalid color code (§j is invalid color code)

**Comment by BloCamLimb** [comment]
Is it the one of 1.15.2?

**Comment by jho5245** [comment]
Oh, forgot to notice the version. I'm using 1.16.1 and forge build is 32.0.98

**Comment by BloCamLimb** [comment]
I'll upload the new version later
