### ISSUE TITLE
Include a comprehensive guide on the necessary things to install for Modern UI to function in 1.18.2 on MacOS.

### ISSUE THREAD

**Issue by ShaeTsuPog** [BloCamLimb/ModernUI#111]
Seeing a lot of MacOS users confused as to why they cannot launch their favorite modpacks since Flux Networks got updated to 1.18.2. Many of them don't know what Vulkan is, much less Mesa, and have no idea how to resolve this issue. A comprehensive guide with links to the necessary software and the steps needed to set it up would be helpful for people, the error message they get thrown on launch isn't very readable or informative.

**Comment by BloCamLimb** [comment]
If you want to just use Flux Networks, you can wait for the next version, where Modern UI becomes an optional dependency.
If you want to set up Modern UI. Just follow https://github.com/KhronosGroup/MoltenVK/ and https://gitlab.freedesktop.org/mesa/mesa I don't think we need a more detailed guide.

**Comment by ShaeTsuPog** [comment]
I'm not a Mac user, just seeing a lot of confused Mac users. 

The issue is that no documentation was present with the mod other than a short blurb on the curseforge page and a truncated error message they get when trying to start the game, and building software from source isn't something the average player is going to know how to do, and since I'm not a Mac user, I cannot walk them through the intricacies of the process for their OS and the tools it uses. 

All that being said, becoming an optional dependency solves the issue as far as flux networks goes.

**Comment by BloCamLimb** [comment]
Try Flux Networks 7.0.1
