### ISSUE TITLE
[Bug] Tooltip Background doesnt cover all text

### ISSUE THREAD

**Issue by TheonlyTazz** [BloCamLimb/ModernUI#112]
**Describe the bug**
Seems as if the Tooltip background doesnt wrap completly around the text

**To Reproduce**
1. Hover over an item
2. ????
3. See broken tooltip background

**Expected behavior**
Wrap tooltip background around all text

**Screenshots**
![image](https://user-images.githubusercontent.com/3908847/174665233-95a675ef-cf3d-4bf0-b987-8ffc3347a190.png)

**Environment**
 - Mod Version:ModernUI-1.18.2-3.4.7.108-universal.jar

 - Forge Version:Forge 40.1.47

**Comment by BloCamLimb** [comment]
What's your configuration of the mod? Is there any other mod?

**Comment by BloCamLimb** [comment]
This issue should no longer exist in the latest version.

**Comment by Yakonche** [comment]
I have the same problem, i'm on fabric 1.20.1 and i tried with version 3.11.1.6 and 3.10.1.4.
The mod configuration files are the default ones, I haven't touched anything, regarding the list of mods, here it is :

```
animal_feeding_trough-1.1.0+1.20.1.jar                  litematica-fabric-1.20.1-0.15.4.jar
 appleskin-fabric-mc1.20.1-2.5.1.jar                     lithium-fabric-mc1.20.1-0.11.3.jar
 architectury-9.2.14-fabric.jar                          lithostitched-fabric-1.20.1-1.4.11.jar
 Authentication-0.4.0.jar                                livingthings-fabric-1.20.1-2.3.0.jar
 AxesAreWeapons-1.7.3-fabric-1.20.2.jar                  malilib-fabric-1.20.1-0.16.1.jar
 balm-fabric-1.20.1-7.3.33.jar                           mclogs-fabric-1.5.0-1.20.jar
 bclib-3.0.14.jar                                        midnightlib-fabric-1.4.1.1.jar
 better-end-4.0.11.jar                                   mineralchance-1.20.1-3.8.jar
 BetterFurnacesReforged-1.20.1-1.1.2518.1-fabric.jar     mine-spawners-1.1.5.jar
 betterstats-3.12.6+fabric-1.20.1.jar                    mns-1.0.1-1.20-fabric.jar
 BiomesOPlenty-fabric-1.20.1-19.0.0.96.jar               modernfix-fabric-5.24.3+mc1.20.1.jar
 BlueMap-5.3-fabric-1.20.jar                             moonlight-1.20-2.14.13-fabric.jar
 BlueMap-Chat-0.3.0.jar                                  moremobvariants-fabric+1.20.1-1.3.1.jar
 bluemap-offline-player-markers-3.0.1-fabric.jar         moveminecarts-1.20.1-3.7.jar
 BlueMapSignExtractor-1.5.jar                            noisium-fabric-2.3.0+mc1.20-1.20.1.jar
 c2me-fabric-mc1.20.1-0.2.0+alpha.11.16.jar              Nullscape_1.20.x_v1.2.8.jar
 cardinal-components-api-5.2.3.jar                       owo-lib-0.11.0+1.20.jar
 ChatImage-1.4.7+1.20+fabric.jar                         packetfixer-3.1.4-1.18-1.20.4-merged.jar
 Chunky-1.3.146.jar                                      Pehkui-3.8.3+1.14.4-1.21.jar
 chunky_extended-2.1.1.jar                               portalgun-6.0.1-mc1.20.1-fabric.jar
 cloth-config-11.1.118-fabric.jar                        Prism-1.20.1-fabric-1.0.5.jar
 collective-1.20.1-8.3.jar                               PuzzlesLib-v8.1.32-1.20.1-Fabric.jar
 Continents_1.21.x_v1.1.8.jar                            reinforced-chests-2.4.2+1.20.jar
 coroutil-fabric-1.20.1-1.3.7.jar                        replantingcrops-1.20.1-5.5.jar
 CreativeCore_FABRIC_v2.12.33_mc1.20.1.jar               rightclickharvest-fabric-4.5.3+1.20.1.jar
 cristellib-1.1.5-fabric.jar                             Searchables-fabric-1.20.1-1.0.3.jar
 dimensionalTracker-1.3.0.jar                            servercore-fabric-1.5.2+1.20.1.jar
 dimension_changer_fabric-1.0.0.jar                      servux-fabric-1.20.0-0.1.0.jar
 dragonloot-1.1.4.jar                                    shield-1.1.4.jar
 dungeons-and-taverns-3.0.3.f.jar                        smarterfarmers-1.20-2.1.2-fabric.jar
 dynamiclights-v1.8.8-mc1.17-1.21.7-mod.jar              StackDeobfuscatorFabric-1.4.3+08e71cc.jar
 elytraslot-fabric-6.4.4+1.20.1.jar                      starlight-1.1.2+fabric.dbc156f.jar
 emi-1.1.22+1.20.1+fabric.jar                            supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
 ExplorersCompass-1.20.1-2.2.3-fabric.jar                tcdcommons-3.12.3+fabric-1.20.1.jar
'Explorify v1.6.2 f10-48.jar'                            TerraBlender-fabric-1.20.1-3.0.1.10.jar
 fabric-api-0.92.6+1.20.1.jar                            the_bumblezone-7.8.0+1.20.1-fabric.jar
 fabric-language-kotlin-1.13.4+kotlin.2.2.0.jar         'The_Graveyard_3.1_(FABRIC)_for_1.20.1.jar'
 FactoryAPI-1.20.1-2.2.5-fabric.jar                      Towns-and-Towers-1.12-Fabric+Forge.jar
 FallingTree-1.20.1-4.3.4.jar                            travelersbackpack-fabric-1.20.1-9.1.37.jar
 farmers-cutting-betterend-1.20.1-1.0.jar                trinkets-3.7.2.jar
 FarmersDelight-1.20.1-2.4.0+refabricated.jar            UniversalEnchants-v8.0.0-1.20.1-Fabric.jar
 FarmersDelight-Expansion-1.2.2+1.20.1.jar               unloadedactivity-v0.6.3+1.20-1.20.1.jar
 ferritecore-6.0.1-fabric.jar                            vanillablocksplus-1.4.6.jar
 flatbedrock-fabric-3.0.1-build.18+mc1.20.1.jar          viewdistancefix-fabric-1.20.1-1.0.2.jar
 ForgeConfigAPIPort-v8.0.2-1.20.1-Fabric.jar             villagernames-1.20-4.5.1.jar
 geckolib-fabric-1.20.1-4.7.3.jar                        VisibleTraders-0.0.4.jar
 GlitchCore-fabric-1.20.1-0.0.1.1.jar                    waterframes-FABRIC-mc1.20.1-v2.1.12c.jar
'HopoBetterUnderwaterRuins-[1.20.1-1.20.4]-1.1.5b.jar'   watermedia-2.1.26.jar
 Iceberg-1.20.1-fabric-1.1.25.jar                        watut-fabric-1.20.1-1.2.3.jar
 IllagerInvasion-v8.0.7-1.20.1-Fabric.jar                waystones-fabric-1.20.1-14.1.16.jar
 imfast-FABRIC-1.20.1-1.0.3.jar                          worldedit-mod-7.2.15.jar
 immersive_optimization-fabric-1.20.1-0.0.4.jar          wraith-waystones-3.3.3+mc1.20.1.jar
 immersive-portals-3.3.9-mc1.20.1-fabric.jar             YungsApi-1.20-Fabric-4.0.6.jar
 Incendium_1.20.x_v5.3.5.jar                             YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
 infinitetrading-1.20.1-4.6.jar                          YungsBetterDungeons-1.20-Fabric-4.0.4.jar
 infinity-fabric-2.4.5+1.20.1.jar                        YungsBetterJungleTemples-1.20-Fabric-2.0.5.jar
 Jade-1.20-Fabric-11.13.1.jar                            YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
 jamlib-fabric-1.3.5+1.20.1.jar                          YungsBetterNetherFortresses-1.20-Fabric-2.0.6.jar
 konkrete_fabric_1.8.1_MC_1.20.1.jar                     YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
 Ksyxis-1.3.3.jar                                        YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar
 lazydfu-0.1.3.jar                                       YungsBridges-1.20-Fabric-4.0.3.jar
 libIPN-fabric-1.20-4.0.2.jar                            YungsExtras-1.20-Fabric-4.0.3.jar
```

**Comment by BloCamLimb** [comment]
> I have the same problem, i'm on fabric 1.20.1 and i tried with version 3.11.1.6 and 3.10.1.4. The mod configuration files are the default ones, I haven't touched anything, regarding the list of mods, here it is :
> 
> ```
> animal_feeding_trough-1.1.0+1.20.1.jar                  litematica-fabric-1.20.1-0.15.4.jar
>  appleskin-fabric-mc1.20.1-2.5.1.jar                     lithium-fabric-mc1.20.1-0.11.3.jar
>  architectury-9.2.14-fabric.jar                          lithostitched-fabric-1.20.1-1.4.11.jar
>  Authentication-0.4.0.jar                                livingthings-fabric-1.20.1-2.3.0.jar
>  AxesAreWeapons-1.7.3-fabric-1.20.2.jar                  malilib-fabric-1.20.1-0.16.1.jar
>  balm-fabric-1.20.1-7.3.33.jar                           mclogs-fabric-1.5.0-1.20.jar
>  bclib-3.0.14.jar                                        midnightlib-fabric-1.4.1.1.jar
>  better-end-4.0.11.jar                                   mineralchance-1.20.1-3.8.jar
>  BetterFurnacesReforged-1.20.1-1.1.2518.1-fabric.jar     mine-spawners-1.1.5.jar
>  betterstats-3.12.6+fabric-1.20.1.jar                    mns-1.0.1-1.20-fabric.jar
>  BiomesOPlenty-fabric-1.20.1-19.0.0.96.jar               modernfix-fabric-5.24.3+mc1.20.1.jar
>  BlueMap-5.3-fabric-1.20.jar                             moonlight-1.20-2.14.13-fabric.jar
>  BlueMap-Chat-0.3.0.jar                                  moremobvariants-fabric+1.20.1-1.3.1.jar
>  bluemap-offline-player-markers-3.0.1-fabric.jar         moveminecarts-1.20.1-3.7.jar
>  BlueMapSignExtractor-1.5.jar                            noisium-fabric-2.3.0+mc1.20-1.20.1.jar
>  c2me-fabric-mc1.20.1-0.2.0+alpha.11.16.jar              Nullscape_1.20.x_v1.2.8.jar
>  cardinal-components-api-5.2.3.jar                       owo-lib-0.11.0+1.20.jar
>  ChatImage-1.4.7+1.20+fabric.jar                         packetfixer-3.1.4-1.18-1.20.4-merged.jar
>  Chunky-1.3.146.jar                                      Pehkui-3.8.3+1.14.4-1.21.jar
>  chunky_extended-2.1.1.jar                               portalgun-6.0.1-mc1.20.1-fabric.jar
>  cloth-config-11.1.118-fabric.jar                        Prism-1.20.1-fabric-1.0.5.jar
>  collective-1.20.1-8.3.jar                               PuzzlesLib-v8.1.32-1.20.1-Fabric.jar
>  Continents_1.21.x_v1.1.8.jar                            reinforced-chests-2.4.2+1.20.jar
>  coroutil-fabric-1.20.1-1.3.7.jar                        replantingcrops-1.20.1-5.5.jar
>  CreativeCore_FABRIC_v2.12.33_mc1.20.1.jar               rightclickharvest-fabric-4.5.3+1.20.1.jar
>  cristellib-1.1.5-fabric.jar                             Searchables-fabric-1.20.1-1.0.3.jar
>  dimensionalTracker-1.3.0.jar                            servercore-fabric-1.5.2+1.20.1.jar
>  dimension_changer_fabric-1.0.0.jar                      servux-fabric-1.20.0-0.1.0.jar
>  dragonloot-1.1.4.jar                                    shield-1.1.4.jar
>  dungeons-and-taverns-3.0.3.f.jar                        smarterfarmers-1.20-2.1.2-fabric.jar
>  dynamiclights-v1.8.8-mc1.17-1.21.7-mod.jar              StackDeobfuscatorFabric-1.4.3+08e71cc.jar
>  elytraslot-fabric-6.4.4+1.20.1.jar                      starlight-1.1.2+fabric.dbc156f.jar
>  emi-1.1.22+1.20.1+fabric.jar                            supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
>  ExplorersCompass-1.20.1-2.2.3-fabric.jar                tcdcommons-3.12.3+fabric-1.20.1.jar
> 'Explorify v1.6.2 f10-48.jar'                            TerraBlender-fabric-1.20.1-3.0.1.10.jar
>  fabric-api-0.92.6+1.20.1.jar                            the_bumblezone-7.8.0+1.20.1-fabric.jar
>  fabric-language-kotlin-1.13.4+kotlin.2.2.0.jar         'The_Graveyard_3.1_(FABRIC)_for_1.20.1.jar'
>  FactoryAPI-1.20.1-2.2.5-fabric.jar                      Towns-and-Towers-1.12-Fabric+Forge.jar
>  FallingTree-1.20.1-4.3.4.jar                            travelersbackpack-fabric-1.20.1-9.1.37.jar
>  farmers-cutting-betterend-1.20.1-1.0.jar                trinkets-3.7.2.jar
>  FarmersDelight-1.20.1-2.4.0+refabricated.jar            UniversalEnchants-v8.0.0-1.20.1-Fabric.jar
>  FarmersDelight-Expansion-1.2.2+1.20.1.jar               unloadedactivity-v0.6.3+1.20-1.20.1.jar
>  ferritecore-6.0.1-fabric.jar                            vanillablocksplus-1.4.6.jar
>  flatbedrock-fabric-3.0.1-build.18+mc1.20.1.jar          viewdistancefix-fabric-1.20.1-1.0.2.jar
>  ForgeConfigAPIPort-v8.0.2-1.20.1-Fabric.jar             villagernames-1.20-4.5.1.jar
>  geckolib-fabric-1.20.1-4.7.3.jar                        VisibleTraders-0.0.4.jar
>  GlitchCore-fabric-1.20.1-0.0.1.1.jar                    waterframes-FABRIC-mc1.20.1-v2.1.12c.jar
> 'HopoBetterUnderwaterRuins-[1.20.1-1.20.4]-1.1.5b.jar'   watermedia-2.1.26.jar
>  Iceberg-1.20.1-fabric-1.1.25.jar                        watut-fabric-1.20.1-1.2.3.jar
>  IllagerInvasion-v8.0.7-1.20.1-Fabric.jar                waystones-fabric-1.20.1-14.1.16.jar
>  imfast-FABRIC-1.20.1-1.0.3.jar                          worldedit-mod-7.2.15.jar
>  immersive_optimization-fabric-1.20.1-0.0.4.jar          wraith-waystones-3.3.3+mc1.20.1.jar
>  immersive-portals-3.3.9-mc1.20.1-fabric.jar             YungsApi-1.20-Fabric-4.0.6.jar
>  Incendium_1.20.x_v5.3.5.jar                             YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
>  infinitetrading-1.20.1-4.6.jar                          YungsBetterDungeons-1.20-Fabric-4.0.4.jar
>  infinity-fabric-2.4.5+1.20.1.jar                        YungsBetterJungleTemples-1.20-Fabric-2.0.5.jar
>  Jade-1.20-Fabric-11.13.1.jar                            YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
>  jamlib-fabric-1.3.5+1.20.1.jar                          YungsBetterNetherFortresses-1.20-Fabric-2.0.6.jar
>  konkrete_fabric_1.8.1_MC_1.20.1.jar                     YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
>  Ksyxis-1.3.3.jar                                        YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar
>  lazydfu-0.1.3.jar                                       YungsBridges-1.20-Fabric-4.0.3.jar
>  libIPN-fabric-1.20-4.0.2.jar                            YungsExtras-1.20-Fabric-4.0.3.jar
> ```

We recommend that you use a binary search to identify the mod directly related to the issue. We do not have the energy to find the cause among so many mods.
