### ISSUE TITLE
[Bug] MC1.16.5 FTB 任务的渲染错误

### ISSUE THREAD

**Issue by Mthos-404** [BloCamLimb/ModernUI#113]
我在玩 [Engineer's Life 2 的 1.13 ](https://www.curseforge.com/minecraft/modpacks/engineers-life-2/files/3672212)版本时发现 FTB 任务的任务奖励的渲染错误

还有我在更换字体为 [思源黑体 CN](https://github.com/adobe-fonts/source-han-sans) 后分辨率特低

**截图**
![image](https://user-images.githubusercontent.com/96325829/175967028-f45576ed-e3fc-4858-91ff-4864b009fa2a.png)
![image](https://user-images.githubusercontent.com/96325829/175967114-867702e4-7558-40f4-8854-eebcedc706cb.png)

**环境**
  - 模组版本：ModernUI-1.16.5-2.6.4.92-universal
  - Forge 版本：36.2.20
  - 操作系统：Windows 10 家庭版 21H2
  - 显卡：3060 Laptop 驱动版本为 511.65
  - Java版本：[Alibaba_Dragonwell_11.0.15.11.9](https://github.com/alibaba/dragonwell11)

**Comment by BloCamLimb** [comment]
是VoxelMap的漏洞吧

**Comment by Mthos-404** [comment]
~~我去回的这么快~~

额~ 我把删了后也不行

**Comment by BloCamLimb** [comment]
那你自己一个一个增/删mod试，看看是哪个模组破坏了此行为

**Comment by Mthos-404** [comment]
好吧

**Comment by Mthos-404** [comment]
我傻了

我把除了 FTB 系列的mod 和 ModernUI 留下其他的全删了也不行

![image](https://user-images.githubusercontent.com/96325829/176094936-18f31d8e-3300-4981-9c80-627cefef7f22.png)

**Comment by Mthos-404** [comment]
搞定了 FTB 任务版本太低
