### ISSUE TITLE
Update LWJGL for Mac ARM CPU Support

### ISSUE THREAD

**Issue by bryce-happel-walton** [BloCamLimb/ModernUI#114]
The version of LWJGL used in the mod is 3.2.1 SNAPSHOT which does not support MacOS arm64 CPUs, which means any Apple silicon mac will not work with this mod. The oldest version compatible is 3.3.0.

**Comment by BloCamLimb** [comment]
Minecraft 1.18 uses LWJGL 3.2.1 so far. The library is downloaded by game launchers, I cannot update it. Minecraft 1.19 uses LWJGL 3.3.1 SNAPSHOT.

**Comment by MrTaco9001** [comment]
Hmm if that's the case then perhaps I've installed Mesa incorrectly. Looking now I assume the `.../` in the JVM arguments is supposed to be replaced with the installation directory of Mesa. Stupid mistake on my part if that's the case. I installed using homebrew.
