### ISSUE TITLE
Weird interaction with Functional Storage

### ISSUE THREAD

**Issue by StarskyXIII** [BloCamLimb/ModernUI#115]
**Describe the bug**
When Install Modern UI, it will make Frequency icons of Liking Tool looks weird.

**To Reproduce**
Install both mods, and use Liking Tool left click on Ender Drawer to get its frequency.

**Expected behavior**
Frequency icons looks clearly.

**Screenshots**
Without Modern UI
![image](https://user-images.githubusercontent.com/71606873/178891805-93045ac2-ce68-461c-bd07-c68f613e2dc7.png)

With Modern UI
![image](https://user-images.githubusercontent.com/71606873/178891828-e11cee06-45e9-4ed0-b060-0e4aecba4441.png)

**Environment**
 - Mod Version: Modern UI v3.5.0.109, Functional Storage v0.0.19
 - Forge Version: 40.1.60
 - Operating System: Windows 11
 - Graphics Card: EVGA GeForce RTX 3060 XC GAMING
 - Other Mods:

**Comment by BloCamLimb** [comment]
I looked into Functional Storage source code, I'm sure this rendering glitch is caused by its incorrect use of PoseStack and improper use of Forge's RenderTooltipEvent and event priority.

**Comment by StarskyXIII** [comment]
Thank you for prompt reply!

**Comment by BloCamLimb** [comment]
btw, I come up with a solution, to fix the rendering order issues.
