### ISSUE TITLE
[Question] How to overwrite font

### ISSUE THREAD

**Issue by teddyxlandlee** [BloCamLimb/ModernUI#119]
I am writing my own mod which adds several characters (not in unicode) to the main font.  
What should I do in order to compat ModernUI?

**Comment by BloCamLimb** [comment]
In any case, you have to use a Unicode character to represent it, you can find a infrequently used Unicode code point and make a custom TTF font. If it is a colored image, you can put it in the emoji folder and enable bitmap replacement.

**Comment by teddyxlandlee** [comment]
1. I am going to use PUA codepoints from 0xF1B00 to 0xF1C3F  
2. Where should I put the true type fonts?

**Comment by BloCamLimb** [comment]
Anywhere you like. For instance, `/assets/namespace/font/x.ttf`, then add `namespace:font/x.ttf` to Modern UI font family config.

**Comment by BloCamLimb** [comment]
Can we close this issue now?
