### ISSUE TITLE
[Bug] CustomName Tag background bug

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#12]
**Describe the bug**
When entities have custom name tag, the name tag's background is not visible.

**To Reproduce**
in minecraft world, summon an entity with /summon creeper ~ ~ ~ {CustomNameVisible:1}

**Expected behavior**
A creeper with name tag with visible tag background.

**Screenshots**
https://imgur.com/a/6FTRKyA

**Versions you are on**
 - Mod Version: ModernUI-1.16.1-2.0.1.58-universal
 - Forge Version: 1.16.1-forge-32.0.98

**Comment by BloCamLimb** [comment]
Fixed 39a946c, released on [curseforge](https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3021465)
