### ISSUE TITLE
[Bug] Modern UI Graphics Engine is disabled on amd latest windows drivers

### ISSUE THREAD

**Issue by jochuan** [BloCamLimb/ModernUI#120]
**Describe the bug**
Modern UI Graphics Engine is disabled on Windows but when the game is played on Linux with the mesa drivers it works normally, so maybe there is something weird that amd made with its windows drivers that needs a compatibility patch for this mod to work.

**To Reproduce**
1. Use the 22.7.1 radeon drivers
2. Open minecraft
3. See error

**Expected behavior**
The Graphics Engine should work as intended since my GPU supports OpenGL 4.6
![image](https://user-images.githubusercontent.com/11268912/181265071-a4a76ffa-d3f5-4faf-b718-08777279d3d6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/11268912/181264733-47929436-6b8e-41c4-9d6c-f1a8c0715523.png)

**Environment**
 - Mod Version: 3.5.2.111
 - Forge Version: 40.1.57
 - Operating System: Windows 10
 - Graphics Card: Radeon 540x
 - Other Mods: A lot of them

**Comment by BloCamLimb** [comment]
If driver reports wrong values, you can skip GL errors by manully changing the config file. `/config/ModernUI/client.toml` -> `skipGLCapsError=true`

**Comment by BloCamLimb** [comment]
It seems to be a feature of latest AMD driver. When requesting OpenGL version lower than 4.3, `explicit_uniform_location` will not be converted to ARB extension. But Minecraft always requests OpenGL 3.2, I found better-loading-screen mod ignores this behavior and gives you a OpenGL 4.6 context.

**Comment by jochuan** [comment]
I will see if i can use it
