### ISSUE TITLE
[Bug] 1.18.2 FluxNetworks makes the server reject clients with ModernUI

### ISSUE THREAD

**Issue by 9-Extra** [BloCamLimb/ModernUI#121]
**Describe the bug**
A client with only ModernUI can join into a server without any mod successfully. But if with FluxNetworks installed on client or both, the connection failed because of mismatched mod list. 

**To Reproduce**
1. Install FluxNetworks both on client and server.
2. Install ModernUI only on client
3. Try join into the server

There are situations I have tried:

  Client        | Server | Result 
-------- | ----- | -------
  ModernUI only     | No mod | Ok       
  ModernUI and FluxNetworks  | No mod | Failed
ModernUI and FluxNetworks  | FluxNetworks | **Failed**
ModernUI and FluxNetworks  | FluxNetworks and ModernUI-server | Ok
ModernUI and FluxNetworks  | FluxNetworks and ModernUI | Ok     

**Expected behavior**
I have joined in a server witch installed FluxNetworks without ModernUI. And because of this, I can't install ModernUI on my client. I expect that ModernUI can stay "client only" capability for servers have FluxNetworks or not. 

**Screenshots**
![图片](https://user-images.githubusercontent.com/77375513/182003043-16ca18cc-90d3-499d-b290-92c72c40754a.png)

**Environment**
 - Mod Version: ModernUI-1.18.2-3.5.2.111-universal ModernUI-1.18.2-3.5.2.111-server FluxNetworks-1.18.2-7.0.2.3
 - Forge Version: 1.18.2-Forge_40.1.68 (both server and client)
 - Operating System: Windows 11
 - Graphics Card: RTX 3070 LAPTOP
 - Other Mods:  FluxNetworks-1.18.2-7.0.2.3

**Comment by 9-Extra** [comment]
It may be a problem of Flux-Networks. I should try the newest version of that.

**Comment by 9-Extra** [comment]
Oh, it is still there

**Comment by 9-Extra** [comment]
Mod Version: ModernUI-1.18.2-3.5.2.111-universal FluxNetworks-1.18.2-**7.0.6.7**
With ModernUI and FluxNetworks installed on client and FluxNetworks on server, the connection still fails.

**Comment by BloCamLimb** [comment]
This is not a Modern UI bug. See FAQ on curseforge:

> Q: Is this mod a client-only mod? Do I need to install it on the server?

> A: If any mod that is using Modern UI as a dependency for the client/server interaction model, then Modern UI is required on the server side.

But what you said is also right. Because Modern UI is optional for Flux Networks, and related content is still under development, there may be some issues. I'll add a config to Flux Networks to control this behavior.
