### ISSUE TITLE
[Bug] wrapLines breaks font

### ISSUE THREAD

**Issue by Luke100000** [BloCamLimb/ModernUI#122]
There is a incompatibility with my mod, Immersive Armors, which breaks the pixel-font e.g. in the mainmenu.
Screenshots are in this issue: https://github.com/Luke100000/ImmersiveArmors/issues/47

Took me some time to track it down to https://github.com/Luke100000/ImmersiveArmors/blob/1.18.2/common/src/main/java/immersive_armors/util/FlowingText.java
specifically the wrap method. It doesn't need to be called, just referencing it is enough.

I further minimized the methode, and from here I'm stuck:
```java
    public static List<Text> wrap(Text text, int maxWidth) {
        // this line breaks it
        MinecraftClient.getInstance().textRenderer.getTextHandler().wrapLines(text, 100, Style.EMPTY);

        // this line does not
        MinecraftClient.getInstance().textRenderer.getTextHandler().wrapLines(new LiteralText(""), 100, Style.EMPTY);

        return List.of(text); // unrelated, just return to not break dependency
    }
```

Both calls to `wrapLines` should be the same, and since it never called I can't imagine why it would affect the font.

**Comment by BloCamLimb** [comment]
They are completely unconnected. The font used in each run is calculated by scoring algorithm based on Typeface and the Unicode char sequence in the context. What font do you get by searching `Loaded typeface:` in the log? I can tell it's fallback to Segoe UI in the second screenshot.

**Comment by Luke100000** [comment]
I have to correct myself, this method is indeed called before the main screen, my print just didn't got logged.

When broken
```
[06Aug2022 09:54:44.341] [Render thread/INFO] [ModernUI/Core]: Loaded typeface: {Noto Sans,SansSerif}
```

When working
```
[06Aug2022 09:59:49.192] [modloading-worker-0/INFO] [ModernUI/Core]: Loaded typeface: {Minecraft,Source Han Sans CN Medium,Noto Sans,SansSerif}
```

It works fine if I prevent wrap from being called before the game is fully loaded. Are there constraints on when I should use the textHandler/textRenderer?

**Comment by BloCamLimb** [comment]
ClientSetupEvent and submit to render thread, `Minecraft.getInstance().tell()`

**Comment by Luke100000** [comment]
I see, thanks!
