### ISSUE TITLE
1.16.5 Modfile not compatible with corresponding Java version [Resulting Error Code 1]

### ISSUE THREAD

**Issue by tronytroo** [BloCamLimb/ModernUI#125]
Im not a code wiz by any means, I dont understand what half of this is, but from what I could see, the latest version of MondernUI that was uploaded for MC 1.16.5 appears to be from 1.18.2. I have tried updating Java to see if that was a problem, but resulted in no change

_No idea whether this is a real issue or a technical failure on my part, but I would appreciate some assistance_

[crash-2022-08-20_11.32.55-fml.txt](https://github.com/BloCamLimb/ModernUI/files/9387841/crash-2022-08-20_11.32.55-fml.txt)

**Comment by BloCamLimb** [comment]
I didn't see anything wrong here. CurseForge shows the latest version for MC 1.16.5 is [ModernUI-1.16.5-2.7.1.105](https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3765938)
