### ISSUE TITLE
[Bug] Lots of Text Sign will Cause huge lag when Modern Text Engine is enabled.

### ISSUE THREAD

**Issue by Longtianmu** [BloCamLimb/ModernUI#126]
**Describe the bug**
When turn on the Modern Text Engine,the frame rate will decrease from about 200 to 24.

**Expected behavior**

**Screenshots**
Modern Text Engine Enabled:
![image](https://user-images.githubusercontent.com/60567448/187382864-ca54b119-eb9c-4502-9b54-1fd215bf2a03.png)

Modern Text Engine Disabled
![image](https://user-images.githubusercontent.com/60567448/187383299-6fa10519-3cd8-4209-878d-e8babf47a9fd.png)

**Environment**
 - Mod Version:3.5.4.113
 - Forge Version:1.18.2-40.1.74
 - Operating System:Windows 11 22H2
 - Graphics Card:RX 580
 - Other Mods:Rubidium and Oculus

**Comment by BloCamLimb** [comment]
Yes, this is how anti-aliasing works. The only solution is disabling linear sampling, anti-aliasing and color emoji.

**Comment by Longtianmu** [comment]
well,disabling these function could still not improve performance

**Comment by BloCamLimb** [comment]
Because Modern UI text rendering pipeline is not a *fixed* pipeline in Minecraft Vanilla, so it's actually 'immediate rendering', and it is hard to implement deferred rendering (batch rendering). This also happens in those mods which create a custom rendering pipeline.

**Comment by Longtianmu** [comment]
That's unfortunately.
btw, I found a strange thing that when use Modern UI with Optifine,the frame rate is doubled comparing to Modern UI with Sodium/Rubidium.

**Comment by BloCamLimb** [comment]
OptiFine has a better optimization scheme. So Modern UI ensures the compatibility with OptiFine.

Can we close this issue for now? I may introduce a new method to optimize text rendering in game world. Since my initial purpose is to provide text rendering in GUI.

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI/commit/72b92027db723a7dd8550d017f1419d854dd6594
