### ISSUE TITLE
[Bug] Broken Mod

### ISSUE THREAD

**Issue by Desher02** [BloCamLimb/ModernUI#128]
**Describe the bug**
Mod simply does not work in 1.16.5 
It crashes the game before going to main menu
i have tried it on its own and with other mods, it simply does not work but it has great features would love to use

**To Reproduce**
1. launch game with mod in mods folder
2. game crashes before even going to main menu

**Expected behavior**
to at least open to main menu

**Screenshots**

**Environment**
 - Mod Version:ModernUI-1.16.5-2.7.1.105-universal.jar as well as ModernUI-1.16.5-2.7.1.104-universal.jar and ModernUI-1.16.5-2.6.4.92-universal.jar (have not tried earlier as of this report)
 - Forge Version: 36.2.36
 - Operating System: Windows 11
 - Graphics Card: GEFORCE RTX 3060
 - Other Mods: none

**Comment by BloCamLimb** [comment]
Where is your crash report?

**Comment by Desher02** [comment]
> Where is your crash report?

it does not give a crash report, it starts loading and immediately closes giving exit code 0

**Comment by BloCamLimb** [comment]
But there must be debug.log and latest.log
