### ISSUE TITLE
[Bug] When use with Tinker Construct 3, some characters maybe loss

### ISSUE THREAD

**Issue by Cactusstudent** [BloCamLimb/ModernUI#129]
**Describe the bug**
与匠魂使用时，打开匠魂手册，材料的名称长的材料会少几个字。

**To Reproduce**
1、下载匠魂与前置（本人使用的是3.5.1.31）
2、打开游戏找到5本指导书的任意一本
3、翻到材料列表处，点击材料名称较长的材料即可看见本现象

**Expected behavior**
将出现此状况的全部修复（这玩意不好写Expect，太多了，估计问题可能出在地幔）

**Screenshots**
（图1是装载汉化时的效果*【汉化来源于官库】 图2是未装载汉化的 [Traveler盔甲的效果] ）
![image](https://user-images.githubusercontent.com/97865546/189465797-1dd8376a-b272-4bec-ae9d-6bfda53e7976.png)
![image](https://user-images.githubusercontent.com/97865546/189465938-c56a82dc-9e36-4792-a676-adfe84ffa709.png)
预期应为：图1：属性强化 升级强化
图2：Traveler‘s Pants Traveler‘s Boots
**Environment**
 - Mod Version: Tinker Construct 3 3.5.1.31
 - Forge Version: 40.1.80
 - Operating System: Windows 10
 - Graphics Card: RTX 3080 (个人认为与显卡无关)
 - Other Mods: Mantle, JEI, JER

**Comment by BloCamLimb** [comment]
Modern UI 版本是 3.5.4.113 吗？

**Comment by Cactusstudent** [comment]
是的

**Comment by BloCamLimb** [comment]
这就和 Modern UI 没有关系了，有些模组会自己做多行布局，兼容很差。
