### ISSUE TITLE
[Suggestion] Bold font rendering

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#13]
Can you add feature to bold the text by rendering the font thickly when using the highest priority font as bold?
I mean, if you set the font name in config with bold type font, and use chat color code (§l bold) to double - bold styled font.

Minecraft font rendering system (from 1.13) and Smooth Font mod's font rendering system implemented similarly as I informed.
render as regular and + if text is bold by chat color (§l), double render but slightly move to right so the text looks bold even if the font is already bold.

**Comment by jho5245** [comment]
Here's example of Minecraft font rendering system using bold font, bold chat color rendering.
https://imgur.com/a/c0cW1ZJ
It may look dirty, but anti aliasing can make it look better as Smooth Font implemented.

**Comment by BloCamLimb** [comment]
yep, smooth font just uses vanilla's system

**Comment by BloCamLimb** [comment]
I tend to never support this, the user preference should be a typeface (i.e. font family) rather than a font, I would make it clear in the config comments.
