### ISSUE TITLE
[Bug] Compatibility with resourcepacks that modify character bitmap to implement custom UI

### ISSUE THREAD

**Issue by muink** [BloCamLimb/ModernUI#132]
**Describe the bug**
Enable `Modern Text Engine` will break such resourcepacks (replace character bitmaps to load custom UI images)  
[In-Game Brewing Guide][]  
[Redstone Tweaks][]  

**To Reproduce**
1. Install ModernUI
2. Load resourcepack [In-Game Brewing Guide][] or [Redstone Tweaks][]
3. Change the game language to `en_us`
4. Open the `Brewing stand` UI
5. Custom UI displayed as HD character instead of `custom-ui.png`

**Expected behavior**
Make Custom UI based on character bitmap display normally
Such Custom UI methods typically use Private Use Area characters U+E000 — U+F8FF to define `custom-ui.png`

**Screenshots**
![EngineOFF](https://i.imgur.com/AhGKG3S.png "EngineOFF")  
![EngineON](https://i.imgur.com/lfXCDqL.png "EngineON")  

**Environment**
 - Mod Version: 1.19.2-3.6.0.114
 - Forge Version: 43.1.24

[In-Game Brewing Guide]: https://www.curseforge.com/minecraft/texture-packs/in-game-brewing-guide
[Redstone Tweaks]: https://www.curseforge.com/minecraft/texture-packs/redstone-tweaks

**Comment by BloCamLimb** [comment]
Implemented in d50186585d25b9179eb0115e0fb768eb108a243a, try this one later and report here.

**Comment by BloCamLimb** [comment]
This is implemented in ModernUI-1.18.2-3.8.0.1
