### ISSUE TITLE
Compatibility with special fonts from other mods

### ISSUE THREAD

**Issue by StarskyXIII** [BloCamLimb/ModernUI#133]
**Describe the bug**
If enabled Modern Text Engine, it will break other mods' special fonts.

**To Reproduce**
1. Install ModernUI
2. Enabled Modern Text Engine
3. Install Runelic, Pig Pen Cipher and Dark Utilities
4. Open the game, and serch for Runelic Tome, Pig Pen Tome and so on.

**Expected behavior**
Display correct fonts

**Screenshots**
Disabled Morden Text Engine
![image](https://user-images.githubusercontent.com/71606873/198545992-09aa4c6b-89a5-4847-b127-265706a0d19c.png)

Enabled Morden Text Engine
![image](https://user-images.githubusercontent.com/71606873/198547323-da68f2d7-ecdb-4716-8bac-3379fc51ecc2.png)

**Environment**
 - Mod Version: 3.5.4.113
 - Forge Version: 40.1.84
 - Operating System: Windows 11
 - Graphics Card: GTX 3060
 - Other Mods: Runelic, Pig Pen Cipher and Dark Utilities

tbh, I don't really care about this issue, I never use this to change texts font on ths sign.
But other players maybe not? So I just report it here.

**Comment by BloCamLimb** [comment]
Currently, any bitmap font given in Minecraft resource packs will not work with Modern UI text layout engine, neither does the atlas stitcher.
