### ISSUE TITLE
[Bug] fancymenu can't use

### ISSUE THREAD

**Issue by 764069075** [BloCamLimb/ModernUI#134]
**Describe the bug**
当我点击fancymenu的新建布局，游戏就会崩溃。

**To Reproduce**
1. 安装最新版fancymenu及其前置，以及modernUI
2. 在主界面点击fancymenu的新建布局
3. 游戏奔溃

**Screenshots**
[crash-2022-11-01_00.28.20-client.txt](https://github.com/BloCamLimb/ModernUI/files/9903010/crash-2022-11-01_00.28.20-client.txt)

**Environment**
 - Mod Version:2.7.1.105
 - Forge Version:36.2.39
 - Operating System:window 11
 - Graphics Card:
 - Other Mods:fancymenu，auudio，konkrete

**Comment by BloCamLimb** [comment]
The crash says nothing about Modern UI.

**Comment by 764069075** [comment]
ok thanks i will report a issues to fancymenu😉
