### ISSUE TITLE
[Bug] The font of some of characters SOMETIMES goes wrong

### ISSUE THREAD

**Issue by cotangent0** [BloCamLimb/ModernUI#135]
**Describe the bug**
问题1：在整合包(All the Mods 7 - To the Sky)里加了ModernUI，部分文本的字体仍然是原版像素字体。
问题2：此问题表现为随机事件，启动了10次游戏，有2次正常，其余均存在问题。
以下包内有本模组config，10次启动的log文件和截图。日志中刷了太多OpenGL错误，为分析带来不便实在抱歉。
[问题信息.zip](https://github.com/BloCamLimb/ModernUI/files/9925785/default.zip)

(已尝试排除其他模组的问题，最终确定问题在ModernUI本身)
(我在玩ATM7时加上此模组从未出过问题)

**To Reproduce**
1. 安装整合包(ATM7S)
2. 自行追加了ModernUI(版本：1.18.2-3.5.4.113-universal), Rubidium及其附属, ChunkPregenerator, JourneyMap, InventoryProfilesNext（这些模组貌似与问题关系不大）
3. 第一次启动后出现问题。将本模组配置文件中fontFamily删除了default.ttf，设置showGLCapsError为false，设置skipGLCapsError为true
4. 又先后启动了9次游戏，只有两次正常

**Screenshots**
以下三张是正常时的截图：
![Snipaste_2022-11-01_21-43-35](https://user-images.githubusercontent.com/97280131/199649120-67e32863-5f0e-4802-94df-324ded82e0b0.png)
![Snipaste_2022-11-01_21-45-10](https://user-images.githubusercontent.com/97280131/199649160-f3da311e-9c11-4d55-ad98-c9d8c1585e2a.png)
![Snipaste_2022-11-01_21-47-42](https://user-images.githubusercontent.com/97280131/199649182-6195c52a-f3ea-47e4-b466-361a48c87494.png)

下面的是有问题时的具体表现：
![Snipaste_2022-11-02_19-34-47](https://user-images.githubusercontent.com/97280131/199649285-f5e524de-4935-4511-a361-c6cc39312425.png)
这一行字是像素字体

![Snipaste_2022-11-02_19-40-00](https://user-images.githubusercontent.com/97280131/199649375-aca67a5c-6440-44a0-bd3f-a757e609f191.png)
Tooltip是像素字体

![Snipaste_2022-11-02_19-41-11](https://user-images.githubusercontent.com/97280131/199649475-ba5b8552-d864-4a19-9907-a922d8187f8b.png)
Rubidium配置界面，左侧选项卡、“十字准星”“应用”“完成”是像素字体

![Snipaste_2022-11-02_19-41-44](https://user-images.githubusercontent.com/97280131/199649712-ebf0233e-5da2-4282-90d4-6aa64ac5da74.png)
左上角TOP，能量条中的数字和字母是像素字体

![Snipaste_2022-11-02_19-42-54](https://user-images.githubusercontent.com/97280131/199649869-338f3f07-32fd-4c4d-8541-b2b63641adee.png)
但匠魂宝典中没有问题

![Snipaste_2022-11-02_19-43-39](https://user-images.githubusercontent.com/97280131/199649917-c00ece18-762a-4982-ab81-199b446ac867.png)
像素字体超出了边框

![Snipaste_2022-11-02_19-44-30](https://user-images.githubusercontent.com/97280131/199650049-8ab854c2-152d-4b91-8f20-6e095e147bfd.png)
热力的gui，左侧有问题，右侧正常

![Snipaste_2022-11-02_19-46-06](https://user-images.githubusercontent.com/97280131/199650178-18666b64-45be-4560-87ec-7e41146afdd2.png)
Apotheosis的附魔台，只有“位阶”“量子化”“阿卡那”三个词正常

![Snipaste_2022-11-02_19-47-21](https://user-images.githubusercontent.com/97280131/199650573-6381831f-5c24-4aed-ab9b-3872ad4c035c.png)
Apotheosis的宝石镶孔在Tooltip中正常

![Snipaste_2022-11-02_19-52-37](https://user-images.githubusercontent.com/97280131/199650662-33e079a6-8149-4953-bba4-a403c9ec8f48.png)
左上角：Rubidium的帧率与坐标有问题
左侧：Iron Jetpacks正常
右上角：JourneyMap正常
右下角：字幕有问题
下方：快捷栏和InventoryHud正常

![Snipaste_2022-11-02_19-54-48](https://user-images.githubusercontent.com/97280131/199650875-f6931e42-1334-44fa-9ace-a742536c0785.png)
![Snipaste_2022-11-02_19-55-39](https://user-images.githubusercontent.com/97280131/199650996-b8441d36-cacb-4cac-8195-9eda3e68f8b1.png)
通用机械里的像素字体

![Snipaste_2022-11-02_19-58-50](https://user-images.githubusercontent.com/97280131/199651156-6ed32fe9-666e-48b5-9d02-328fd10770d5.png)
聊天栏内的字有问题

![Snipaste_2022-11-02_20-00-22](https://user-images.githubusercontent.com/97280131/199651203-070b045f-e3bf-41f0-93bb-eaf9ca3620c9.png)
标题页面右下角“Copyright...”一行字有问题

另外在原版button内的字都有问题
(啰嗦了一大堆，希望对解决问题有帮助）

**Expected behavior**
确定是我的操作有误还是模组的bug，希望可以解决问题
(自己乱改整合包的确很容易出问题，但没了ModernUI我实在看不下去)

**Environment**
 - Mod Version: 1.18.2-3.5.4.113-universal
 - Forge Version: 40.1.80
 - Operating System: Windows 10
 - Graphics Card: Intel(R) UHD Graphics 610 
 - Other Mods: Modpack=>All the Mods 7 - To the Sky，自己追加了Rubidium及其附属, ChunkPregenerator, JourneyMap, InventoryProfilesNext

**Comment by BloCamLimb** [comment]
字体加载没什么问题，仅仅是和emojiful不兼容。这个我已经在很多地方解释过了，没有办法兼容emojiful，所以将它移除就好。 #47
