### ISSUE TITLE
Is this really under LGPL?

### ISSUE THREAD

**Issue by zhenlige** [BloCamLimb/ModernUI#136]
GitHub shows that this project is released under LGPL-3.0, but CurseForge shows that it is All Rights Reserved, and the FAQ mentioned that it is not allowed to maintain an unofficial version on CurseForge. So is this project free (libre) or not?

**Comment by BloCamLimb** [comment]
It depends on whether you see Modern UI as a 'product' or an open source project. The source code is surely under LGPLv3, you can build or modify from source code yourself under LGPLv3. But the official release on CurseForge is the binary and embedded libraries, they are different.

**Comment by zhenlige** [comment]
So is it OK to modify the source code here and maintain an unofficial version?

**Comment by BloCamLimb** [comment]
That's true.
