### ISSUE TITLE
[Bug] Extensions OpenGL backward compatibility issues

### ISSUE THREAD

**Issue by TexBlock** [BloCamLimb/ModernUI#137]
**Describe the bug**
在整合包 FTB StoneBlock 3 中添加了本模组，但字体渲染不正常，tooltip仍为原版。

**To Reproduce**
1. 安装整合包
2. 删除Emojiful，添加 Modern UI + Rubidium + Rubidium Extra + TexTrue's Rubidium Options + I18nUpdateMod-NLTS + Better Loading Screen + SmoothBoot (Reloaded) + Catalogue
3. 启动游戏后出现此问题，然后在配置文件的`fontfamily`删除`default.ttf`
4. 再次启动，问题依旧存在

日志文件：[latest.log](https://github.com/BloCamLimb/ModernUI/files/10235008/latest.log)

**Screenshots**
字体问题：
![image](https://user-images.githubusercontent.com/65154269/207801533-4a8c6b2f-e390-4532-bb7d-810675644590.png)
tooltip问题：
![image](https://user-images.githubusercontent.com/65154269/207801625-91ddcbad-44dd-4ab9-b8ea-205064af06a0.png)

**Environment**
 - Mod Version: 1.18.2-3.5.4.113
 - Forge Version: 40.1.84
 - Operating System: Windows 11 专业版 Insider Preview 25262.1000
 - Graphics Card: Intel(R) HD Graphics 2500 （OpenGL4.0）
 - Other Mods: FTB StoneBlock 3 (除Emojiful) + Modern UI + Rubidium + Rubidium Extra + TexTrue's Rubidium Options + I18nUpdateMod-NLTS + Better Loading Screen + SmoothBoot (Reloaded) + Catalogue

**Comment by BloCamLimb** [comment]
更新 Intel HD Graphics Driver 至 10.18.10.4252 或更高

**Comment by TexBlock** [comment]
> 更新 Intel HD Graphics Driver 至 10.18.10.4252 或更高

![image](https://user-images.githubusercontent.com/65154269/207811369-5a3b4597-71ae-42d1-814b-37777cb7caac.png)

**Comment by BloCamLimb** [comment]
没救了，建议上英伟达显卡
