### ISSUE TITLE
Any plans to support Fabric?

### ISSUE THREAD

**Issue by zhenlige** [BloCamLimb/ModernUI#138]
**I am sorry that I cannot access Discord due to my location, so I put this suggestion here.**
This mod is fantastic, but it is a pity that it does not support Fabric. Since Fabric is becoming more and more popular nowadays, and there are lots of mods that are only available on Fabric, it will be better to release a Fabric version.

**Comment by BloCamLimb** [comment]
The code migration to a new repository is already in progress, and a place will be reserved for Fabric version. But I will not maintain the Fabric version (and modding APIs for it).

**Comment by Jack253-png** [comment]
I tried to port the glsl part to fabric platform and I found it works (rounded-rect, circle, guassian blur), the link: github.com/Jack253-png/BetterUI

**Comment by BloCamLimb** [comment]
I have a plan for the Fabric support in Minecraft 1.20.1
See https://github.com/BloCamLimb/ModernUI-MC

**Comment by Zorklis** [comment]
Seems to support it as of [Modern UI 3.8.1.5 (Fabric)](https://modrinth.com/mod/modern-ui/version/fiYL31XK)
