### ISSUE TITLE
[Bug] NullPointerException at start

### ISSUE THREAD

**Issue by enimog** [BloCamLimb/ModernUI#139]
**Describe the bug**
When trying to launch the game, it crash (sometimes, not always) with a nullpointer exception.

See the included crash log for more details.

[crash-2022-12-18_17.50.38-client.txt](https://github.com/BloCamLimb/ModernUI/files/10254833/crash-2022-12-18_17.50.38-client.txt)

**Environment**
 - Mod Version: 3.6.3.117
 - Forge Version: 43.2.0
 - Operating System: Linux
 - Graphics Card: AMD

**Comment by enimog** [comment]
nevermind it was a user error, sorry

**Comment by Gavin456b** [comment]
What did you do to fix this?

**Comment by enimog** [comment]
It happens when you are missing a dependency for a mod and forge is trying to display the screen that say what mod you are missing. By adding the missing dependency the error do not happen.
