### ISSUE TITLE
[Bug] Crash with NullPointerExcpetion

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#14]
**Describe the bug**
I was spectator game mode and spectating a player in multiplayer server.
And suddenly the game crashes.

**To Reproduce**
Spectate a player for a long  time in multiplayer.

Here's crash log
https://pastebin.com/WyaPLSdP

**Versions you are on**
 - Mod Version: ModernUI-1.16.1-2.0.2.59
 - Forge Version: 1.16.1-forge-32.0.98

**Comment by BloCamLimb** [comment]
Fixed
