### ISSUE TITLE
[Bug] When use this mod with JEI, the search bar of JEI will change style. 在与JEI一起使用时会导致JEI搜索框样式改变。

### ISSUE THREAD

**Issue by HuanGeiWoLiuGeBi** [BloCamLimb/ModernUI#140]
Bug Describe
Bug介绍
When use this mod with JEI, the search bar of JEI will change style.
在与JEI一起使用时会导致JEI搜索框样式改变。

Reproduce
复现
Use this mod with JEI.
与JEI一同使用。

Expected Behavior
期望效果
Change the search bar of JEI back.
将JEI的搜索框改回去。

Screenshots
屏幕截图
![image](https://user-images.githubusercontent.com/113269187/210486785-3af0f29f-c0ac-442a-acd7-81b4950b2760.png)

Environment
测试环境
Mod Version: 1.18.2-3.5.4.113-universal
模组版本：1.18.2-3.5.4.113-universal
Forge Version: 40.2.0
Forge版本：40.2.0
Operating System: Windows 11
操作系统：Windows 11
Graphics Card: RTX 3060 Laptop GPU
显卡：RTX 3060 Laptop GPU
Other Mods: Just Enough Items
其它模组：JEI

**Comment by BloCamLimb** [comment]
I can't reproduce it on the latest version. I suppose Modern UI would not cause issues like that.

**Comment by HuanGeiWoLiuGeBi** [comment]
我下载了最新的 Modern UI（仍然是之前的版本），但与 JEI 一同使用时仍然会造成 Bug。这次我将提供更详细的信息。

模组版本：ModernUI-1.18.2-3.5.4.113-universal.jar
JEI 版本：jei-1.18.2-9.7.1.255.jar
Forge 版本：40.2.0
启动器：Curseforge
同样游戏内环境请在此处下载整合包：https://github.com/HuanGeiWoLiuGeBi/Test-Repository

屏幕截图
![image](https://user-images.githubusercontent.com/113269187/213334885-e18b804c-ca97-483e-9057-9b4439969c88.png)
（同时使用 Modern UI 与 JEI）
![image](https://user-images.githubusercontent.com/113269187/213334890-0a2ac508-f80c-4e27-8836-831658c1b1b9.png)
（仅使用 JEI）

**Comment by BloCamLimb** [comment]
我感觉更像是 JEI 的问题，毕竟 Modern UI 压根就没有更改搜索框渲染的代码。
但是呢，1.18.2终究是不更新了，所以这个问题也是无解。

**Comment by HuanGeiWoLiuGeBi** [comment]
别吧

**Comment by BloCamLimb** [comment]
那看来是没办法了。这个边框渲染是来源于原版，但我复制了一遍这段代码到新版中，此外优化输入框文本的渲染性能、优化指针移动和改善选区样式。理论上讲是没有区别的，JEI 那边会继承原版的类，然后不知道哪里搞砸了就这样了。反正你看 1.19.2 的 JEI 又没这个问题。
