### ISSUE TITLE
[Bug] Creeper Overhaul Firework

### ISSUE THREAD

**Issue by FanRenLa** [BloCamLimb/ModernUI#141]
**Describe the bug**
Creeper Overhaul Firework crash, but the other side said they had nothing to do with it.
I did see information about modernizing UI in previous crash reports.
加入烟花苦力怕改革爬崩溃，但对方说他们与此无关。
在以往的崩溃报告中确实有看到过现代化 UI相关信息。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - Mod Version:ModernUI-1.19.2-3.6.3.117-universal
 - Forge Version:43.1.57
 - Operating System:Windows 10 (amd64) version 10.0
 - Graphics Card:NVIDIA GeForce RTX 3060 Laptop GPU
 - Other Mods:Creeper Overhaul Firework

**Comment by BloCamLimb** [comment]
你得提供完整日志，在 Forge 中如果有其他 mod 加载失败，也会造成 Modern UI 加载失败，进而引发 Modern UI 崩溃。你看这个报告，有一行
`creeperoverhaul-2.0.5-forge.jar |Creeper Overhaul |creeperoverhaul |2.0.5 |ERROR |Manifest: NOSIGNATURE` 明确告诉你了只有 creeperoverhaul 是 ERROR 阶段（抛出了运行时异常），其他都是 COMMON_SET 阶段（正常加载的某个阶段）。
