### ISSUE TITLE
[1.19.2] "icyllis.modernui.graphics.font.LayoutCache.sCache" returning null

### ISSUE THREAD

**Issue by HockeyZman2000** [BloCamLimb/ModernUI#144]
[latest.log](https://github.com/BloCamLimb/ModernUI/files/11256521/latest.log)
[crash-2023-04-17_18.23.58-client.txt](https://github.com/BloCamLimb/ModernUI/files/11256523/crash-2023-04-17_18.23.58-client.txt)

Not sure what's causing this error with the mod installed, removing Modern UI allows the game to load. I've tried removing multiple mods with seemingly no fix.

Mod Version: 1.19.2-3.6.3.117
Forge Version: 43.2.8

**Comment by BloCamLimb** [comment]
`modernfix-mc1.19.2-3.3.1.jar                      |ModernFix                     |modernfix                     |3.3.1               |ERROR     |Manifest: NOSIGNATURE`
This mod crashed.
