### ISSUE TITLE
[Bug] [1.19.2] Refuses to load with mod installed, works fine without

### ISSUE THREAD

**Issue by HockeyZman2000** [BloCamLimb/ModernUI#146]
**Describe the bug**
Loading a modpack with the mod causes loading to be terminated with no crash report, only once did I get the game to load without changing any mods around, odd? Without Modern UI installed the game loads normally. My guess is that it's a mod compatability thing but I'm not entirely sure which mod is to blame because I can't pinpoint anything unusual inside of the logs.

**Expected behavior**
Game loads normally with the mod installed.

Modern UI version 3.6.3.117
Forge version 43.2.8

[latest.log](https://github.com/BloCamLimb/ModernUI/files/11327232/latest.log)

[debug.log](https://github.com/BloCamLimb/ModernUI/files/11327233/debug.log)

**Comment by BloCamLimb** [comment]
I didn't see anything wrong with these logs, if there is no crash-report generated, check if there is hs_err_xx. Also try starting the game without mods but Modern UI.

**Comment by HockeyZman2000** [comment]
[hs_err_pid20472.log](https://github.com/BloCamLimb/ModernUI/files/11336265/hs_err_pid20472.log)

There are a bunch of these in the folder and this one is the most recent.
Modern UI by itself works/loads as intended.

**Comment by BloCamLimb** [comment]
It seems that there's an unsafe access to stack memory. You may want to discover which mod crashed with Modern UI, by checking those mods one by one.

**Comment by HockeyZman2000** [comment]
Okay so this is what I've gathered so far:

In my modpack I'm trying to run, I've so far identified 3 mods as being the problem mods

Better Invisibility Version 1.0.4 - https://www.curseforge.com/minecraft/mc-mods/better-invisibility/files/4023568
Entity Collision FPS Fix Version 2.0.0 - https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix/files/3829972
Modern UI (same version as above)

The Tricky Bit
Game fails to load with the unsafe access to stack memory mentioned above under 3 different conditions:
1. Taking out Better Invisibility still fails loading, with other 2 mods still installed
2. Loading all 3 mods together also fails loading
3. Taking out Entity Collision FPS Fix also fails loading, with other 2 mods still installed

Game loads correctly without Modern UI with the other 2 installed.

However loading up a pack with only those 3 mods active loads the game correctly as it should, which leads me to believe there might even be a 4th mod involved that I haven't discovered yet

**Comment by HockeyZman2000** [comment]
Oddly enough, I think the cause of everything was the Upgraded Tools mod for some reason. After removing it and also removing Better Invisibility (that one also didn't work still), I was able to get the game to launch with Modern UI and the FPS Fix. It also enabled me to add in ModernFix without it crashing like it did previously

**Comment by BloCamLimb** [comment]
But I can't find the possible code in Upgraded Tools that could crash.

**Comment by HockeyZman2000** [comment]
If you would like I can send you the modpack so you can try it out if that would help at all

**Comment by HockeyZman2000** [comment]
I think I've just about given up because I still get the error when I remove random mods from the pack

**Comment by BloCamLimb** [comment]
It may be a graphics driver error, why not get NVIDIA cards.
