### ISSUE TITLE
[Bug] Doesn't support custom Fonts in Components

### ISSUE THREAD

**Issue by Speiger** [BloCamLimb/ModernUI#147]
**Describe the bug**
https://github.com/TinyModularThings/UniqueEnchantments/issues/87

**To Reproduce**
Install Modern UI install Unique Enchantments

**Expected behavior**
That custom fonts would be respected

**Screenshots**
![S](https://user-images.githubusercontent.com/85009668/235145971-21fd28f9-5be5-4d6a-9e39-2a2e7c4a6a00.png)

**Environment**
 - Mod Version: Latest (Repost so no idea)
 - Forge Version: Latest (Repost so no idea)
 - Operating System: Repost so no idea
 - Graphics Card: Repost so no idea
 - Other Mods: Assuming UE/ModernUI

**Comment by BloCamLimb** [comment]
Vanilla-compatible custom fonts are supported in MC 1.18+, no more updates for MC 1.16.5
