### ISSUE TITLE
[Bug] 无法解析拥有特定本地名称的字体

### ISSUE THREAD

**Issue by marioplus** [BloCamLimb/ModernUI#148]
**Describe the bug**
一些拥有特定本地名称的字体的字体，使用本地名称在字体列表中设置时，无法正确解析该字体。

**To Reproduce**
1. 在`client.toml`中添加字体`微软雅黑`
![image](https://github.com/BloCamLimb/ModernUI/assets/26264731/7e3eade7-fe59-4da7-a2d0-1832d91c84f8)
3. 启动游戏
4. 无法加载设置的字体
![image](https://github.com/BloCamLimb/ModernUI/assets/26264731/9e986749-f2fc-4a22-92cb-20e706450b4d)

**Expected behavior**
在游戏中使用`微软雅黑`渲染字体

**Screenshots**

**Environment**
 - Mod Version: 2.7.1.105 / 1.16.5
 - Forge Version: 36.2.39
 - Operating System: windows 11
 - Graphics Card: 2080S
 - Other Mods: 整合包 [Enigmatica6 1.8.0](https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/4437691)

感觉 [ModernUIForge.java#LL251C13-L253C34](https://github.com/BloCamLimb/ModernUI/blob/766aba29e84bd0052a4a7c8c0a81fbb58d752361/mod-forge/src/main/java/icyllis/modernui/forge/ModernUIForge.java#LL251C13-L253C34) 可以加上对本地名称的匹配。
```java
Optional<Font> font = Typeface.sAllFontFamilies.stream()
                    .filter(f -> f.getFamily(Locale.ROOT).equalsIgnoreCase(cfg) || f.getFamily(Locale.getDefault()).equalsIgnoreCase(cfg))
                    .findFirst();
```

**Comment by BloCamLimb** [comment]
1.16 已经不更新了，用Microsoft YaHei UI

**Comment by marioplus** [comment]
![image](https://github.com/BloCamLimb/ModernUI/assets/26264731/2a5be8ea-6a5d-45a3-bac2-2d2138534dc0)
对于一般人来说当然是直接从系统里面找字体的名称，之前的想法确实只能解决一部分问题，这样也可以
```java
List<String> configs = Arrays.asList(
        "微软雅黑",
        "Microsoft YaHei"
);
for (String cfg : configs) {
    boolean hasFail = !Font.DIALOG.equals(cfg);
    if (hasFail) {
        Font cfgFont = new Font(cfg, Font.PLAIN, 1);
        String cfgFontFamily = cfgFont.getFamily(Locale.ROOT);
        if (!Font.DIALOG.equals(cfgFontFamily)) {
            hasFail = sAllFontFamilies.stream()
                    .noneMatch(f -> f.getFamily(Locale.ROOT).equalsIgnoreCase(cfgFontFamily));
        }
    }
}
```
