### ISSUE TITLE
[Bug] 界面尺寸问题

### ISSUE THREAD

**Issue by Dr-WeiAL** [BloCamLimb/ModernUI#149]
**Describe the bug**
在安装了这个模组之后，窗口化的界面尺寸最大为2，最大化窗口后才能使用3和4
每次设置为3后重启游戏，就会还原成2，每次启动都得手动改

**To Reproduce**
1. 启动游戏
2. 最大化窗口
3. 设置界面尺寸为3
4. 重启游戏
5. 界面尺寸会被强制改回2

**Expected behavior**
让窗口化的界面尺寸上限能跟最大化窗口的界面尺寸上限一致？

**Screenshots**
![image](https://github.com/BloCamLimb/ModernUI/assets/47446553/6ec0e08e-d96e-45b3-9197-2183bf14afb8)
![image](https://github.com/BloCamLimb/ModernUI/assets/47446553/645514c4-6692-4ed9-9cfd-9b14127a8df9)
![image](https://github.com/BloCamLimb/ModernUI/assets/47446553/63dbbfac-1877-4067-84e0-e4cc498c0d5a)

**Environment**
 - Mod Version: 1.19.2-3.6.3.117
 - Forge Version: 43.2.11
 - Operating System: Windows 10
 - Graphics Card: RTX 2060
 - Other Mods: Rubidium（装不装都会出现这个问题）

**Comment by BloCamLimb** [comment]
当真？Options.txt里会保存之前设置的比例，比如之前在全屏下设置为4，重启后在窗口化界面下，由于分辨率太小，实际生效的值是2，但是全屏后依然会变成4。如果有别的模组冲突，可以把窗口模式设成最大化，还可以在启动器里修改窗口大小。

**Comment by Dr-WeiAL** [comment]
但确实是这样，我加您QQ了，可以屏幕分享看看(

**Comment by BloCamLimb** [comment]
Fixed

**Comment by Dr-WeiAL** [comment]
话说在哪里更新了吗(
curseforge最后更新日期在2022年

**Comment by BloCamLimb** [comment]
在 https://github.com/BloCamLimb/ModernUI-MC 仓库，目前仍在内测

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI-MC/releases/tag/v3.7.0

**Comment by genderneutralnoun** [comment]
Will this problem be fixed for older Minecraft versions?
