### ISSUE TITLE
[Bug] title text's antialiasing & shadow

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#15]
**Describe the bug**
A title message (i.g. /title command) with antialiasing and shadow is rendered strangely.
Other texts without shadow (i.g. sign, actionbar, or scoreboard) doesn't make this issue.

Font name: Malgun Gothic Bold

**To Reproduce**
Simply use /title @s title "Text Shadow Glitch" command

**Expected behavior**
A title message rendered correctly.

**Screenshots**
![Text Shadow Glitch](https://user-images.githubusercontent.com/11700801/89180518-e3cb0800-d5cc-11ea-8eb6-2580bf140ce7.png)

**Versions you are on**
 - Mod Version: ModernUI-1.16.1-2.0.3.60-universal
 - Forge Version: 1.16.1-forge-32.0.98

**Comment by BloCamLimb** [comment]
It can't be fixed

**Comment by jho5245** [comment]
But look at this screen shot
![Text Shadow](https://user-images.githubusercontent.com/11700801/89183236-e2500e80-d5d1-11ea-83fe-a2ca93420762.png)
This is from with the mod ModernUI-1.16.1-2.0.2.59-universal and looks clear.

**Comment by BloCamLimb** [comment]
The last version was: if there is water (or other translucent block) behind the text, you will find other problems. And also an entity custom tag name with a strikethrough line.
You can only choose between last version and current one

**Comment by jho5245** [comment]
This screenshot is from with last version mod
![screen shot from last version](https://user-images.githubusercontent.com/11700801/89184200-60f97b80-d5d3-11ea-86c9-85ca9443e319.png)
It looks good, I also think that last version will be better!

**Comment by BloCamLimb** [comment]
![image](https://user-images.githubusercontent.com/14106648/89184356-3efbfb00-d5cb-11ea-981e-55b53a64e024.png)
You will find that these places will discard the rendering of water, and render the block behind the water

**Comment by jho5245** [comment]
Oh yes, it's because of anti aliasing but... my opinion is title glitch looks worse.

**Comment by jho5245** [comment]
tried with current (version 60) and the name tag in front of water looks quite transparent
![current (version 60) screenshot](https://user-images.githubusercontent.com/11700801/89186424-bc793880-d5d6-11ea-8cff-52a039ca6e95.png)

**Comment by BloCamLimb** [comment]
Yes, because text renders behind the water

**Comment by BloCamLimb** [comment]
I did a quick test, the reason for no glitch in the last version of title rendering is that I forced all previous rendering layers to be finished, which causes a massive lag

**Comment by BloCamLimb** [comment]
Then the vanilla font system doesn't have the above glitch, because there are no translucent pixels.

**Comment by jho5245** [comment]
hmm, so the keyward is 'good view' or 'good performance'?

**Comment by BloCamLimb** [comment]
There is no buffer system like this in 1.12, so 1.12 just needs to disable depth writing.

The solution I can think of is is to use non-realtime rendering. That is let the font renderer collect all the rendering info, and then render them in correct z-order at the appropriate rendering phase. But if to do this, it's better to use multi-threaded rendering. But I don't expect mojang to change render system much soon.

As far as I'm concerned, I think it's the best now. I don't know if anyone else can solve this issue, at least I can't.

**Comment by BloCamLimb** [comment]
btw, I found the title rendering can be fixed, all HUD can be modified by Forge API
