### ISSUE TITLE
其他模组添加的告示牌上面写字渲染有问题

### ISSUE THREAD

**Issue by MeiyuanaQ** [BloCamLimb/ModernUI#150]
任何mod的告示牌上面,第一行字左侧渲染有问题,而且抬头或者侧头看告示牌上面的文字会不渲染

![QQ图片20230610221655](https://github.com/BloCamLimb/ModernUI/assets/55645051/064d692e-6058-430a-99c4-40f87a2b91bd)

 - Mod Version:ModernUI-1.19.2-3.7.0.0-RC1-universal
 - Forge Version:43.2.10

**Comment by BloCamLimb** [comment]
你开了光影，这个没法修复
