### ISSUE TITLE
[Question/Help] Crash with biggerstacks

### ISSUE THREAD

**Issue by PORTB** [BloCamLimb/ModernUI#151]
**Describe the bug**
(I am the developer of bigger stacks)

A custom ui component is causing a crash with this mod, and I am not sure why.
The custom component is just the vanilla editbox but with a different border colour. The renderButton code was copied from the vanilla code and I changed a value.
Code: https://codeberg.org/PORTB/BiggerStacks/src/branch/1.18/src/main/java/portb/biggerstacks/gui/EditBoxWithADifferentBorderColour.java

How can I fix this?

**To Reproduce**
1. Install biggerstacks and this mod
2. open a world and run `/biggerstacks quicksetup` (it opens the gui that uses that editbox)
3. crash

**Expected behavior**
No crash

**Screenshots**

**Environment**
 - Mod Version:  ModernUI-1.18.2-3.5.4.113-universal
 - Forge Version: 40.2.9
 - Operating System: windows 10 x64
 - Graphics Card:rtx 3070 8gb
 - Other Mods: biggerstacks

## Crashlog
[crash-2023-06-14_09.02.59-client.txt](https://github.com/BloCamLimb/ModernUI/files/11740097/crash-2023-06-14_09.02.59-client.txt)

**Comment by BloCamLimb** [comment]
There is an optimization that formatter can return null values, which means leaving as is. If you rewrite EditBox#renderButton, you have to call setFormatter in ctor (you can skip BiDi text support just like vanilla).
