### ISSUE TITLE
[Bug] Untitled

### ISSUE THREAD

**Issue by StarRemained** [BloCamLimb/ModernUI#152]
**Describe the bug**
ModernUI just turn every letter on the display board of Create Mod into boxes.

**To Reproduce**
1. Get ModernUI and Create installed
2. put a display board down

**Expected behavior**
Every letter on the display board is box. Nothing can be displayed.

**Screenshots**
![2023-06-17_20 24 09](https://github.com/BloCamLimb/ModernUI/assets/135506768/5cb7508c-96fe-4732-951e-ce79b73285b5)

**Environment**
 - Mod Version: ModernUI-1.19.2-3.6.3.117-universal   
 - Forge Version: 43.2.13
 - Operating System: Win10
 - Graphics Card: GTX3060ti g6x
 - Other Mods: create-1.19.2-0.5.1.b

**Comment by BloCamLimb** [comment]
It has been fixed in 3.7.0
