### ISSUE TITLE
[Bug] Compatibility with resourcepacks that modify character bitmap to implement custom UI

### ISSUE THREAD

**Issue by RuNan2** [BloCamLimb/ModernUI#153]
**Describe the bug**
Enable Modern Text Engine will break such resourcepacks (replace character bitmaps to load custom UI images)

**Expected behavior**
appear to be the same problem as https://github.com/BloCamLimb/ModernUI/issues/132

**Environment**
 - Mod Version:ModernUI-1.18.2-3.5.4.113
 - Forge Version: 1.18.2-40.2.9

**Comment by BloCamLimb** [comment]
It has been implemented since 1.19.2, please do not report this issue again.
1.18.2 support is dropped.

**Comment by RuNan2** [comment]
1.18.2 is one of the more popular versions that people use. Can you please update it?

**Comment by BloCamLimb** [comment]
This is implemented in ModernUI-1.18.2-3.8.0.1
