### ISSUE TITLE
[1.19.2] Modern UI text engine doesn't display sign text when Oculus shaders are enabled

### ISSUE THREAD

**Issue by seancrain** [BloCamLimb/ModernUI#154]
See https://github.com/Asek3/Oculus/issues/346

**Comment by BloCamLimb** [comment]
We added compatibility in ModernUI-1.19.2-3.8.0.2. Disable `text shaders in 3D world`

**Comment by seancrain** [comment]
I can't seem to locate the download for this new release. Is it on CurseForge yet, or has it moved to another platform?

**Comment by BloCamLimb** [comment]
There's something wrong with CurseForge moderation. I have also uploaded it to Modrinth, but it's still under review. You can download it here for now https://github.com/BloCamLimb/ModernUI-MC/releases
