### ISSUE TITLE
[Bug] Not compatible with feytweaks

### ISSUE THREAD

**Issue by qznfbnj** [BloCamLimb/ModernUI#156]
**Describe the bug**
Modern UI is not compatible with [feytweaks (forge port)](https://www.curseforge.com/minecraft/mc-mods/feytweaks/files/4621411).
If it's feytweaks (forge port)'s fault, I'll report it to [CCr4ft3r](https://github.com/CCr4ft3r).
If this conflict can not be fixed, close the issue directly. Or if there is no need to install feytweaks for better performance after installing ModernUI, please let me know.
[crash-2023-07-07_13.50.26-client.txt](https://gist.github.com/qznfbnj/283e65abf8643ffda435d1b6ca6c8a46)
[debug.log](https://gist.github.com/qznfbnj/5e30de710ecb39b6015044669e1bdc21)

**To Reproduce**
1. Install Modern UI and feytweaks (forge port)
2. Launch
3. Crash on startup

**Expected behavior**
I can use Modern UI's text engine while getting optimizations from feytweaks.

**Screenshots**
N/A

**Environment**
 - Mod Version: 1.19.2-3.7.0.3
 - Forge Version: 43.2.13
 - Operating System: Windows 11
 - Graphics Card: NVIDIA GeForce MX150/PCIe/SSE2
 - Other Mods: feytweaks-1.19.2-1.2.5-all.jar

**Comment by BloCamLimb** [comment]
This can't be fixed, because entire Font class has been overwritten by Modern UI. But it's possible for feytweaks mod to turn off optimization for glowing signs.

**Comment by qznfbnj** [comment]
For others:
Edit feytweaks.mixins.json in feytweaks's jar, comment the "TextRendererMixin".
This way you can still use some feytweaks optimizations. You can still hide the glow effect in the distance (probably doesn't make much sense).
![image](https://github.com/BloCamLimb/ModernUI/assets/100760086/0d4dbcd6-8158-46ef-a036-12f7ca8ac169)
