### ISSUE TITLE
[Question] Reloaded EMI in 90s

### ISSUE THREAD

**Issue by qznfbnj** [BloCamLimb/ModernUI#157]
**Describe the bug**
Modernui seems to greatly increase emi reload time. I want to know what is wrong or which mod is to blame.
~~(I haven't tested other versions of emi and ModernUI under the same mc version. I will try the old version tomorrow when I have time.)~~
[debug-2937](https://gist.github.com/qznfbnj/7b0735a9778262b038b5d71e2527b35a)
[debug-1214](https://gist.github.com/qznfbnj/49b5c6345d676974a8af0c2a3ed3b721)
[debug-89539](https://gist.github.com/qznfbnj/8d1128ad87c5ddaac8062b8ef1a9478c)

**To Reproduce**
1. Remove ModernUI from my mods folder (2937ms)
2. Leave only emi (1214ms)
3. Leave only emi and ModernUI (89539ms)

**Expected behavior**
I can use Modernui without emi reload time increase.

**Screenshots**
1. Remove ModernUI from my mods folder (2937ms)
![MUI-EMI-3](https://github.com/BloCamLimb/ModernUI/assets/100760086/dd6de255-883f-4ed0-9cee-315277d155b8)
2. Leave only emi (1214ms)
![MUI-EMI-2](https://github.com/BloCamLimb/ModernUI/assets/100760086/870c462a-4903-4ef9-a6ac-34a8916c6e8c)
3. Leave only emi and ModernUI (89539ms)
![MUI-EMI-1](https://github.com/BloCamLimb/ModernUI/assets/100760086/617cbe9c-2374-4b1c-8eff-8148b4161437)

**Environment**
 - Mod Version: 1.19.2-3.7.1.1
 - Forge Version: 43.2.13
 - Operating System: Windows 11
 - Graphics Card: NVIDIA GeForce MX150/PCIe/SSE2
 - Other Mods: [emi-1.0.9+1.19.2+forge](https://www.curseforge.com/minecraft/mc-mods/emi/files/4636479)

**Comment by BloCamLimb** [comment]
Currently text layout engine needs to be synced with render thread, so what I'm thinking about is delaying font atlas stitching and line boundary analysis.

**Comment by BloCamLimb** [comment]
I tend not to support asynchronous text layout, vanilla FontSet class is not thread safe and EMI shouldn't do this in background thread. Currently our implementation will block on any other thread.

**Comment by qznfbnj** [comment]
## Temporary workaround
emi-1.0.4+1.19.2+forge + ModernUI-1.19.2-3.7.1.1-universal -> Reloaded EMI in 1013ms

**Comment by emilyploszaj** [comment]
![image](https://github.com/BloCamLimb/ModernUI/assets/14813658/02db8700-b037-4a74-b369-dd02e4853e0c)
Basically all of this is coming down to calling `Font.width()` off thread and ModernUI completely replacing the system. It is entirely reasonable for EMI to be calling `ItemStack.getTooltip()` off thread to bake a search index, and it is quite reasonable for mods (such as create) using simple text utilities like getting width from text.

The version of EMI releasing later today removes calls to things off thread that create tooltip components and half solves this issue in vanilla, but as shown in this profile mods like Create can still trigger issues similar to it.

It is not reasonable for EMI to bake a large search index on the render thread and freeze the game for several seconds even on a good computer, something needs to be done on ModernUI's side.

**Comment by BloCamLimb** [comment]
This is improved in 3.8.0, but async operations may cause problems. Because Modern UI allow typeface and font size to be changed at runtime, but other mods don't know these metrics data needs to be re-computed.
