### ISSUE TITLE
[Bug] 在渲染神化Boss的名字时崩溃

### ISSUE THREAD

**Issue by Floatttttt** [BloCamLimb/ModernUI#158]
**Describe the bug**
神化Mod生成Boss时会随机赋予Boss名字，无论Boss实体id，当某一Boss名称带有§k（例如Steve the §kAlien§r）且玩家尝试渲染该名称时则会导致崩溃.

**To Reproduce**

1. 启动游戏.
2. 进入存档.
3. 等待或手动生成神化Boss.
4. 当Boss名称带有§k且玩家试图渲染该名称时则会导致崩溃.

**Expected behavior**
让Boss名称正常渲染，不会发生崩溃？

**Screenshots**
[emmm，没有截图，倒是有崩溃报告：](https://gist.github.com/Floatttttt/f03ba2154fcfa53b3ff3b467ededc69b)

**Environment**
 - Mod Version: 1.19.2-3.7.0.3
 - Forge Version: 43.2.19
 - Operating System: Windows 10
 - Graphics Card: NVIDIA GTX 750
 - Other Mods: Patchouli-1.19.2-77 , Apotheosis-1.19.2-6.2.1 , Placebo-1.19.2-7.3.0 , Bookshelf-Forge-1.19.2-16.3.20 , EnchantmentDescriptions-Forge-1.19.2-13.0.14

**Comment by BloCamLimb** [comment]
你能不能更新模组啊，已经修了
