### ISSUE TITLE
[Bug] 文本编辑框单行文本超过128字符时崩溃

### ISSUE THREAD

**Issue by SQwatermark** [BloCamLimb/ModernUI#159]
**Describe the bug**
如题，在基于ModernUI制作模组时发现，已在只安装了ModernUI的情况下进行复现。
[崩溃报告：](https://pastebin.com/mjfeEEsc)

**To Reproduce**
在ModernUI操作中心字体族文本编辑框中任意一行输入大量字符

**Environment**
 - Mod Version:1.20.1-3.7.1.3
 - Forge Version:47.1.36
 - Operating System:Windows 10 (amd64) version 10.0
 - Graphics Card:NVIDIA GeForce RTX 2060
 - Other Mods:无

**Comment by BloCamLimb** [comment]
Known issue.

**Comment by BloCamLimb** [comment]
Done, will be available in version 3.8
