### ISSUE TITLE
[Bug] Name Tag not become transparent

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#16]
**Describe the bug**
when name tags are blocked by blocks, (or sneaking player's name tag) the name tag become half-transparent in vanilla minecraft, but after mod installed, the name tag doesn't become transparent even it's blocked.

**To Reproduce**
Name a mob with minecraft name tag item and place block you (player) and the mob.
and you can see the name tag is still bright visible.
+ Edit : or just /summon creeper ~ ~ ~ {CustomNameVisible:1,NoAI:1}

**Expected behavior**
The name tag should be half-transparent

**Screenshots**
![name tag not become transparent](https://user-images.githubusercontent.com/11700801/89182773-3ad2dc00-d5d1-11ea-9d1e-5db445e1d623.png)
(the creeper is behind the iron block wall)

**Versions you are on**
 - Mod Version: ModernUI-1.16.1-2.0.3.60-universal
 - Forge Version: 1.16.1-forge-32.0.98

**Comment by BloCamLimb** [comment]
I disabled Entity Font Renderer, it's not a bug and can't be fixed

**Comment by BloCamLimb** [comment]
Fixed, [curseforge](https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3025704)
