### ISSUE TITLE
[Bug] ModernUI允许阴影时，通用机械机器GUI内物品信息无法正常显示

### ISSUE THREAD

**Issue by Harvey2433** [BloCamLimb/ModernUI#161]
Describe the bug
如题，在使用ModernUI制作整合包并启用允许阴影时发现，已在只安装了ModernUI和通用机械的的情况下复现。

To Reproduce
在任意通用机械的机器内,ModernUI关闭允许阴影的情况下鼠标对准任意物品不显示物品信息

Environment

Mod Version:1.18.2-3.5.4.113
Forge Version:40.2.9
Operating System:Windows 10 (amd64) version 10.0
Graphics Card:AMD Radeon（TM）R5 M315
Other Mods:[通用机械] Mekanism-1.18.2-10.2.5.465

**Comment by BloCamLimb** [comment]
您能按照模板发issue吗

**Comment by Harvey2433** [comment]
> 您能按照模板发issue吗

改完了

**Comment by BloCamLimb** [comment]
Fixed in ModernUI-1.18.2-3.8.0.1
