### ISSUE TITLE
[Bug] 在1.19.2使用Oculus开光影时使用本mod，会与告示牌等渲染冲突，导致字体消失

### ISSUE THREAD

**Issue by LrbsX** [BloCamLimb/ModernUI#162]
**Describe the bug**
在1.19.2使用Oculus开光影时使用本mod，会与告示牌等渲染冲突，导致字体消失。

**To Reproduce**
1.安装Oculus+Rubidium(这是Oculus的前置) 在1.19.2 forge任意可运行版本。
2.安装ModernUI 在1.19.2 forge任意可运行版本。
3.任意开一个光影。
4.拿出告示牌打字并观察，或观察生物的命名和玩家头上的名字。
5.观察到：开光影时，第三步操作后出现的字体，无法被观察到。

**Expected behavior**
希望解决渲染问题。
最简单解决方法建议：增加控制告示牌等渲染是否使用现代文本引擎的配置文件配置。因为这一部分的渲染不用现代文本引擎也其实已经算是能看的程度(即为将字体文件作为资源包加载进原版Minecraft，显示出的告示牌和命名显示的效果)。

**Screenshots**
图一图二：开光影和没开光影的告示牌对比
图三图四：开光影和没开光影的命名显示对比
图五：上文所述“这一部分的渲染不用现代文本引擎也其实已经算是能看的程度(即为将字体文件作为资源包加载进原版Minecraft，显示出的告示牌和命名显示的效果)”

![2023-08-02_08 58 57](https://github.com/BloCamLimb/ModernUI/assets/95033532/3e6ca428-6f4f-438f-9050-67146126231c)
![2023-08-02_08 59 00](https://github.com/BloCamLimb/ModernUI/assets/95033532/c76cacfc-ba55-4cc8-8ae5-8cd0f09070e8)
![2023-08-02_08 58 37](https://github.com/BloCamLimb/ModernUI/assets/95033532/43c2ed7e-9ae0-43ec-9e90-c79519581f04)
![2023-08-02_08 58 21](https://github.com/BloCamLimb/ModernUI/assets/95033532/d01cbd5e-3f20-4db7-83be-4da2c506d039)
![2023-08-02_09 01 51](https://github.com/BloCamLimb/ModernUI/assets/95033532/1407f798-10d9-4ac5-9ebf-23fffa019627)

**Environment**
 - Mod Version: ModernUI-1.19.2-3.7.1.1-universal
 - Forge Version: 1.19.2-Forge_43.2.14
 - Operating System: Windows 11 22631.2115
 - Graphics Card: NVIDIA GeForce RTX 3050 Laptop
 - Other Mods: oculus-mc1.19.2-1.6.4  和  rubidium-0.6.2b

**Comment by qznfbnj** [comment]
关联问题：https://github.com/BloCamLimb/ModernUI/issues/154

**Comment by BloCamLimb** [comment]
原因是Iris覆盖了原版的shader，并且不接受其他shader。可以兼容，关闭ModernUI的文字着色器，但是ModernUI的一些功能：抗锯齿、批量渲染（半透明排序）、SDF文字渲染，在GUI中仍可生效，但在3D世界中不再生效。布局引擎不受影响。

**Comment by LrbsX** [comment]
> 原因是Iris覆盖了原版的shader，并且不接受其他shader。可以兼容，关闭ModernUI的文字着色器，但是ModernUI的一些功能：抗锯齿、批量渲染（半透明排序）、SDF文字渲染，在GUI中仍可生效，但在3D世界中不再生效。布局引擎不受影响。

那么如何关闭文字着色器呢

**Comment by BloCamLimb** [comment]
我说可以兼容，意思是正在做

> > 原因是Iris覆盖了原版的shader，并且不接受其他shader。可以兼容，关闭ModernUI的文字着色器，但是ModernUI的一些功能：抗锯齿、批量渲染（半透明排序）、SDF文字渲染，在GUI中仍可生效，但在3D世界中不再生效。布局引擎不受影响。
> 
> 那么如何关闭文字着色器呢

**Comment by LrbsX** [comment]
> 我说可以兼容，意思是正在做
> 
> > > 原因是Iris覆盖了原版的shader，并且不接受其他shader。可以兼容，关闭ModernUI的文字着色器，但是ModernUI的一些功能：抗锯齿、批量渲染（半透明排序）、SDF文字渲染，在GUI中仍可生效，但在3D世界中不再生效。布局引擎不受影响。
> > 
> > 那么如何关闭文字着色器呢
> 
> 

好的，谢谢

**Comment by Naireem-sudo** [comment]
Sorry, but is there any Info? What do i have to do to make it work?

**Comment by BloCamLimb** [comment]
It's done in https://github.com/BloCamLimb/ModernUI-MC/commit/982d28515ec110a52cd55b6986ed20eee1eaf4e9, wait for next release

**Comment by BloCamLimb** [comment]
We added compatibility in ModernUI-1.19.2-3.8.0.2. Disable `text shaders in 3D world`
