### ISSUE TITLE
[Bug] Clicking on "Font Family" textbox will input NULs at text cursor

### ISSUE THREAD

**Issue by imhe6** [BloCamLimb/ModernUI#163]
**Describe the bug**
Clicking on "Font-family" textbox in Modern UI's Configuration Center will always input NULs at the original position. It seems to replace all selected characters to NUL. The game crashes on load after closing and restarting.

**To Reproduce**
1. Go to Modern UI's Configuration Center by pressing Ctrl + K
2. Go to Preferences
3. Click or drag-select on "Font Family" 

**Expected behavior**
Nothing changes on font-family items when click or select characters

**Screenshots**
![QQ202383-101426](https://github.com/BloCamLimb/ModernUI/assets/95729258/d5593347-66a1-48b2-804b-b3f376186451)
![image](https://github.com/BloCamLimb/ModernUI/assets/95729258/04355736-8194-4813-9660-3697e35296ee)

**Environment**
 - Mod Version: 3.7.1.2
 - Forge Version: 47.1.0
 - Operating System: Windows 11
 - Graphics Card: Nvidia GeForce RTX 3060
 - Other Mods: Optifine, Inventory Profile Next, MouseTweaks and some optimization mods

**Comment by BloCamLimb** [comment]
Can't reproduce. I tested from source code, there is no '\0' char in the original char sequence. What Java vendor + version are you using?

**Comment by imhe6** [comment]
I've found the issue no longer happens after removing a mod named [IMBlocker](https://www.curseforge.com/minecraft/mc-mods/imblocker) which is intended to auto-switching IME for East Asian Language. Maybe there's an compatibility issue. Sorry for bothering.

**Comment by qznfbnj** [comment]
我说我怎么有一次配置文件全是NUL
可能的关联问题：https://github.com/reserveword/IMBlocker/issues/22

**Comment by BloCamLimb** [comment]
Wait for Modern UI 3.8
