### ISSUE TITLE
[Bug] Ars Nouveau crashes when typing in spellbook text field with ModernUI

### ISSUE THREAD

**Issue by sandalle** [BloCamLimb/ModernUI#164]
**Describe the bug**
When having both Ars Nouvou ( https://www.curseforge.com/minecraft/mc-mods/ars-nouveau ) and ModernUI and I try to create a new spell, when typing in the name field to name my spell it crashes the client (but not the dedicated server): [crash-2023-08-08_20.08.06-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/12297855/crash-2023-08-08_20.08.06-client.txt)

**To Reproduce**
1. Press "C" to open your Ars Nouveau spellbook
2. Start typing in the "Name" field in the bottom left to name your spell.
3. Client crashes. :)

Bug filed for Ars Nouveau: https://github.com/baileyholl/Ars-Nouveau/issues/1060

**Expected behavior**
The name I type should appear in the text field.

**Screenshots**
"Spell Name" text field is the bottom left field:
![Ars Nouveau Spell Name](https://github.com/baileyholl/Ars-Nouveau/assets/2447608/0144c045-70b4-44bc-b1c2-a9e4d62bcf03)
Typing in the "Search" field in the top right causes the same crash.

**Environment**
- MC: 1.20.1
- Forge: 41.7.3
- Ars Nouveau: 1.20.1-4.2.4
- ModernUI: 1.20.1-3.7.1.3
- Operating System: Windows 10 x86_64
- Graphics Card: nVidia GeForce GTX 970
- Other Mods: https://github.com/sandalle/nst-trailsandtales/tree/main

**Comment by BloCamLimb** [comment]
Duplicated of #151

Because Modern UI has an optimization here, but for compatibility reasons, I would to take another approach in the next version.

**Comment by BloCamLimb** [comment]
Done in ModernUI-1.20.1-3.8.0.4

**Comment by sandalle** [comment]
It's fixed with ModernUI 1.20.1-3.8.0.4, thanks!
