### ISSUE TITLE
Task bar is not hidden in Fullscreen borderless

### ISSUE THREAD

**Issue by Quinnnnnq** [BloCamLimb/ModernUI#165]
**Describe the bug**
Task bar is not hidden in Fullscreen borderless

**Expected behavior**
Hide task bar

**Screenshots**
![image](https://github.com/BloCamLimb/ModernUI/assets/107864301/0e39abf9-cff9-4d0d-806c-1dce9df80a51)

![image](https://github.com/BloCamLimb/ModernUI/assets/107864301/fc2ad284-9e35-4f1e-a921-c90c9195648a)

**Environment**
 - Mod Version:1.20.1-3.8.0.4
 - Forge Version:47.1.43
 - Operating System:Windows 10 Pro 22H2
 - Graphics Card:GTX 960
 - Other Mods:Rubidium 0.6.5 Oculus 1.6.4

**Comment by BloCamLimb** [comment]
This is not a bug, it is due to the limitations of GLFW.

If you have a fullscreen window (and borderless) that covers the taskbar, the window is always topmost, and there won't be any window shown above it, except the taskbar and floating windows. Then the borderless mode becomes meaningless, because users want to show the game window and other windows at the same time. For now, I would recommend choosing to `automatically hide the taskbar`.

**Comment by BloCamLimb** [comment]
We improved fullscreen borderless in 3.8.1

**Comment by BloCamLimb** [comment]
你看看3.8.1还有问题吗

**Comment by bling-yshs** [comment]
> > This is not a bug, it is due to the limitations of GLFW.
> > If you have a fullscreen window (and borderless) that covers the taskbar, the window is always topmost, and there won't be any window shown above it, except the taskbar and floating windows. Then the borderless mode becomes meaningless, because users want to show the game window and other windows at the same time. For now, I would recommend choosing to `automatically hide the taskbar` in OS settings.
> 
> Thank you for answering! BTW, using [Watt Toolkit](https://github.com/BeyondDimension/SteamTools) can create a perfect borderless window without taskbar. ![image](https://private-user-images.githubusercontent.com/107864301/260520512-84c3c9d7-a4a5-4650-b2ee-6cba0eea8f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Mzc4MTIsIm5iZiI6MTcxNDYzNzUxMiwicGF0aCI6Ii8xMDc4NjQzMDEvMjYwNTIwNTEyLTg0YzNjOWQ3LWE0YTUtNDY1MC1iMmVlLTZjYmEwZWVhOGY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwODExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjEzNTA5MWFlYTQ3Mzc3ZWY4ZTcwM2JkYjc2YmY2ZDZmYjAwNjVlNzQxMmY1ODRjOTIwZTc3MTg0NGVmMzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OmpuqJNl43DNrYlXjC6CEEIPoC1CvfpEu3TAL3p3Ozc) ![image](https://private-user-images.githubusercontent.com/107864301/260520804-6570efe6-c767-4300-b5ca-e753a591e0a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Mzc4MTIsIm5iZiI6MTcxNDYzNzUxMiwicGF0aCI6Ii8xMDc4NjQzMDEvMjYwNTIwODA0LTY1NzBlZmU2LWM3NjctNDMwMC1iNWNhLWU3NTNhNTkxZTBhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwODExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDU0ZThmNDQzMDA3NmYyM2Y3NTMzZmI1MDlkMDdhYTk4NzRiNjVjMTdkOTk2MTU0NTdhZTU4MWM2YWE1M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.emuCKx39rAKzzaC_HqRfwtco4AfQBr7H3hI5mt9fqf0) 无边框窗口化 First, then 最大化

感谢，帮大忙了
