### ISSUE TITLE
[Bug] Imcompatibility with the Modern UI 1.18.2-3.8.0.1 and Flux Networks 1.18.2-7.0.8.12.

### ISSUE THREAD

**Issue by Visoral** [BloCamLimb/ModernUI#166]
**Describe the bug**
The latest version (1.18.2-3.8.0.1) of Modern UI causes a crash when you load with the Flux Networks 1.18.2-7.0.8.12, while you can load it normally with Modern UI 1.18.2-3.5.4.113

**To Reproduce**
1. Install both ModernUI-1.18.2-3.8.0.1-universal.jar and FluxNetworks-1.18.2-7.0.8.12.jar

**Expected behavior**
The client starts without error.

**Screenshots**
N/A

**Environment**
 - Mod Version: 1.18.2-3.8.0.1
 - Forge Version: 40.2.0
 - Operating System: Windows 11 Pro
 - Graphics Card: NVIDIA GeForce GTX 1080 Ti
 - Other Mods: Flux Networks 1.18.2-7.0.8.12

**Comment by BloCamLimb** [comment]
I know that. We will work on Flux Networks side.
