### ISSUE TITLE
[Bug] Crash after an option changed

### ISSUE THREAD

**Issue by qznfbnj** [BloCamLimb/ModernUI#168]
**Describe the bug**
Crash after an option changed
[debug.log](https://gist.github.com/qznfbnj/3e0f3107600f0ad7ccfc1a5defb5c03f#file-debug-log)
[crash-2023-08-21_23.23.33-client.txt](https://gist.github.com/qznfbnj/8aef60a30d3b3f31e40cec2e8a8215af#file-crash-2023-08-21_23-23-33-client-txt)

**To Reproduce**

https://github.com/BloCamLimb/ModernUI/assets/100760086/ca62943b-92c9-404d-9a1e-1aae1ac141a1

**Expected behavior**
No crash happened

**Screenshots**

**Environment**
 - Mod Version: 3.8.0.2
 - Forge Version: 43.2.13
 - Operating System: Windows 11
 - Graphics Card: NVIDIA GeForce MX150/PCIe/SSE2
 - Other Mods: None

**Comment by BloCamLimb** [comment]
Fixed in 3.8.1.+
