### ISSUE TITLE
[Bug] FTB Library's button have no text when used with ModernUI

### ISSUE THREAD

**Issue by Maypul** [BloCamLimb/ModernUI#169]
**Describe the bug**
When ModernUI is used with FTB Library, I do not get to see the text of FTB Library's button in game.

**To Reproduce**
1. Install ModernUI, FTB Library ands architectury
2. Start single player or multiplayer world, click "E" to open up the gui
3. Hover over the buttons on top left, no text is visible, only the background.

**Expected behavior**
Buttons would provide the text as when without ModernUI

**Screenshots**
1.19.2 with said mods: 
![image](https://github.com/BloCamLimb/ModernUI/assets/98578889/ecc097d8-051f-4e29-b934-e662a9ee00d1)
Mod versions: 
![image](https://github.com/BloCamLimb/ModernUI/assets/98578889/c3dfcdd2-da5b-4741-bd9f-b9ad906ee858)

1.19.2 without ModernUI:
![image](https://github.com/BloCamLimb/ModernUI/assets/98578889/387b61dc-be78-4a8c-ab65-389196c606db)

**Environment**
 - Mod Version: 1.19.2-3.8.0.2
 - Forge Version: 43.2.21
 - Operating System: Windows 10 x64
 - Graphics Card: AMD Radeon 6900 XT
 - Other Mods: architectury-6.5.85-forge and ftb-library-forge-1902.4.1-build.236

Edit: Disabling Text Engine for Minecraft in ModernUI fixes it but those buttons are only thing negatively aggected by it so far

**Comment by BloCamLimb** [comment]
Fixed in 3.8.1.2

**Comment by Maypul** [comment]
Confirming it works now, thank you.
