### ISSUE TITLE
[Bug] Conflicting Fabric Mods

### ISSUE THREAD

**Issue by Zorklis** [BloCamLimb/ModernUI#170]
**Describe the bug**
Upon launch these mods could not run due to ModernUI.

**To Reproduce**
1. Start Minecraft with listed mods.

**Expected behavior**
For all to run in unity.

**Environment**
 - Mod Version: [Modern UI 3.8.1.5 (Fabric)](https://modrinth.com/mod/modern-ui/version/fiYL31XK)
 - Fabric Version: Fabric Loader 0.14.22 -1.20.1
 - Operating System: W10
 - Graphics Card: GTX 1060

Other Mods:
**Debugify-1.20.1+2.0** - Doesn't crash with just ModernUI and Debugify. It does crash if ModernUI + Debugify and collective are present. Without ModernUI they both work fine together
[MUI+Collective and Debugify crash-2023-09-06_21.50.42-client.txt](https://github.com/BloCamLimb/ModernUI/files/12541382/MUI%2BCollective.and.Debugify.crash-2023-09-06_21.50.42-client.txt)

**feytweaks-1.20-1.2.7** crash log with just ModernUI and Feytweaks.
[With just Feytweaks crash-2023-09-06_21.41.48-client.txt](https://github.com/BloCamLimb/ModernUI/files/12541347/With.just.Feytweaks.crash-2023-09-06_21.41.48-client.txt)

**Comment by BloCamLimb** [comment]
We don't support compatibility with other Fabric mods on text rendering.

**Comment by BloCamLimb** [comment]
We fixed the compatibility with Debugify in 3.9.0
