### ISSUE TITLE
[Bug] Crash when starting the launcher 1.18.2

### ISSUE THREAD

**Issue by Billetiado10** [BloCamLimb/ModernUI#171]
**Describe the bug**
When I install Modern UI I get this error and the start menu and other mods do not load correctly.
https://bytebin.lucko.me/rwrg8vIBWs

**To Reproduce**
1. Download the Mod
2. Start the game
3. 3. A clear and concise description of what you expected to happen.

**Expected behavior**
This menu is expected to appear correctly with the other mods.
![image](https://github.com/BloCamLimb/ModernUI/assets/76263374/47a92a22-7777-4d11-b28f-8e0bce85dc10)

But this error occurs with the mod installed
![image](https://github.com/BloCamLimb/ModernUI/assets/76263374/7ca4323c-563b-4679-8fe7-e6cad95d2763)
![image](https://github.com/BloCamLimb/ModernUI/assets/76263374/9646208d-aa77-4524-b8b9-aff05fd43de6)

**Environment**
 - Mod Version: ModernUI-1.18.2-3.8.1.1-universal.jar
 - Forge Version: 40.2.10
 - Operating System: Windows 10
 - Graphics Card: GTX 1050 ti
 - Other Mods: 433 other mods

**Comment by BloCamLimb** [comment]
You should paste a full `debug.log` on https://mclo.gs/

**Comment by Billetiado10** [comment]
All right

**Comment by BloCamLimb** [comment]
Where's the link?

> All right

**Comment by Billetiado10** [comment]
https://mclo.gs/COM0y3V

**Comment by BloCamLimb** [comment]
Can you give a minimal reproducible example? It seems to be caused by some resource loading errors.

**Comment by BloCamLimb** [comment]
I believe this was fixed in 3.8.2
