### ISSUE TITLE
[Bug] The icon is misaligned when using Create Engineer's Goggles

### ISSUE THREAD

**Issue by in1t1a1** [BloCamLimb/ModernUI#172]
![C){MTJQR}$0(%WASAO`YHDD](https://github.com/BloCamLimb/ModernUI/assets/71259497/9c980f70-d21f-4a45-9d02-cbcc35baac05)
![%SOS$V()3M(JQI51LIC9U@Y](https://github.com/BloCamLimb/ModernUI/assets/71259497/e57f13fa-124f-4b7c-bfd1-b3f5d5c87f13)
![image](https://github.com/BloCamLimb/ModernUI/assets/71259497/5c843463-eaa8-4a3a-98fc-98f7d897167f)

**Environment**
 - Mod Version:ModernUI-1.20.1-3.8.1.4
 - Other Mods:Create

**Comment by BloCamLimb** [comment]
This may be due to an incorrect implementation of Create. A mod must measure multiple space characters together to get its width for indentation. Also do this after resource are reloaded. Please transfer this issue to Create.
