### ISSUE TITLE
[Bug] Strange level display when used with ImmediatelyFast mod

### ISSUE THREAD

**Issue by Soochaehwa** [BloCamLimb/ModernUI#173]
**Describe the bug**
Levels are displayed behind the experience bar

**To Reproduce**
1. Using Modern UI with ImmediatelyFast

**Expected behavior**
Levels should display correctly

**Screenshots**
![2023-09-13_12 00 11](https://github.com/BloCamLimb/ModernUI/assets/43947445/2af48214-c0e7-4286-9ce4-e790c7fd8169)

**Environment**
Minecraft 1.20.1, Modern UI 3.8.1.5, ImmediatelyFast 1.2.3
Fabric, Forge same

**Comment by BloCamLimb** [comment]
Disable ImmediatelyFast's hud_batching and font_atlas_resizing
