### ISSUE TITLE
[Bug] Crash when starting the game Minecraft 1.18.2 again

### ISSUE THREAD

**Issue by Billetiado10** [BloCamLimb/ModernUI#174]
**Describe the bug**
In this case I put a video to detail the crash.
https://bytebin.lucko.me/wm9317Nz7r
VIDEO LINK
https://youtu.be/qquRdsaedF8
LOG debug
https://mclo.gs/HCQDjId

**To Reproduce**
1. Install mod ModernUI-1.18.2-3.8.1.1-universal.jar
2. Click on Launcher
3. See error

**Expected behavior**
Loading the custom FANCY MENU mod.
![image](https://github.com/BloCamLimb/ModernUI/assets/76263374/5e1069df-6b95-4e84-9c1f-57c92d682856)

**Screenshots**

**Environment**
Mod Version: ModernUI-1.18.2-3.8.1.1-universal.jar
Forge Version: 40.2.10
Operating System: Windows 10
Graphics Card: GTX 1050 ti
Other Mods: 433 other mods

**Comment by BloCamLimb** [comment]
Have you tried ModernUI-Forge-1.18.2-3.8.2.1?

**Comment by Billetiado10** [comment]
It doesn't appear in the download section

**Comment by BloCamLimb** [comment]
> It doesn't appear in the download section

https://modrinth.com/mod/modern-ui/versions

**Comment by Billetiado10** [comment]
I was reviewing on Curseforge, I'll try this version

**Comment by Billetiado10** [comment]
Now it works Thank you very much
