### ISSUE TITLE
[Bug] Imcompatibility with the Modern UI 1.19.2-3.8.2.2 and Flux Networks 1.19.2-7.1.13

### ISSUE THREAD

**Issue by Well2333** [BloCamLimb/ModernUI#176]
**Describe the bug**
Modern UI 1.19.2-3.8.2.2 is incompatible with Flux Networks 1.19.2-7.1.13. When I attempt to open items from the mod (e.g., "flux point"), it doesn't display the interface as expected. Concurrently, the console displays the following message:
Modern UI 1.19.2-3.8.2.2 与 Flux Networks 1.19.2-7.1.13 存在不兼容问题。当我尝试打开某模组的物品（如“flux point”）时，它并不如预期显示其界面。同时，控制台显示了以下提示：

```
[11:49:51] [Render thread/WARN] [minecraft/MenuScreens]: Failed to create screen for menu type: fluxnetworks:flux_menu
```

Upon clicking the **same** item again, the message `Access denied: Another player is using` is displayed.
当再次点击**相同**的物品时，会提示 `Access denied: Another player is using`

![44dcfd10f1ec063dd287c58fdf315d21](https://github.com/BloCamLimb/ModernUI/assets/40534114/b6256e7f-7157-4eb8-a216-6ace61c1c939)

When I remove Modern UI and reload the game, flux works normally. If I reload Modern UI, no other errors occur besides the one mentioned (i.e., flux functions are normal but configuration is inaccessible).
在移除 Modern UI 并重新加载游戏后，flux 可以正常工作。如果再次加载 Modern UI，也不会导致任何其他问题（也就是说 flux 是正常的，只是无法配置）

I tested versions 7.1.12 and 7.1.13. Since the latest version, 7.1.14, doesn't support my current forge version (I'm using 43.1.55, minimum required: 43.2.8), I did not test it.
我测试了版本 7.1.12 和 7.1.13。由于当前的最新版本 7.1.14 不支持我使用的 forge 版本（我使用的是 43.1.55，而它要求的最低版本是 43.2.8），所以我没有测试。

**Environment**
 - Mod Version: 7.1.12 - 7.1.13
 - Forge Version: 43.1.55
 - Operating System: Windows 10 Professional
 - Graphics Card: Intel Arc A770 16G
 - Other Mods: Using MODPack [cryptopolis](https://www.curseforge.com/minecraft/modpacks/cryptopolis) version 1.0.1

**Comment by BloCamLimb** [comment]
Update Forge to 43.2.8 and Flux Networks to 7.1.14or downgrade Modern UI to 3.6
