### ISSUE TITLE
[Bug] icyllis/modernui/forge/MixinConnector has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by esvarc** [BloCamLimb/ModernUI#177]
**Describe the bug**
Game crash with error:

java.lang.UnsupportedClassVersionError: icyllis/modernui/forge/MixinConnector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**
1. Just start game from launcher

**Expected behavior**
Game would start

**Environment**
 - Mod Version: modernui-1.16.5-2.7.1.105-universal.raj 
 - Forge Version: 1.16.5-forge-36.2.39
 - Minecraft Version: 1.16.5

[debug.log](https://github.com/BloCamLimb/ModernUI/files/12745952/debug.log)

**Comment by BloCamLimb** [comment]
Do you read FAQ on CurseForge/Modrinth?

Duplicated of
https://github.com/BloCamLimb/ModernUI/issues/104
https://github.com/BloCamLimb/ModernUI/issues/81
