### ISSUE TITLE
[Bug] Compatibility issues with Modern UI 1.20.1-3.8.2.4 and Loot Beams: Relooted! 1.20.1-1.2.2, and Obscure Tooltips 2.2.

### ISSUE THREAD

**Issue by Lenatus** [BloCamLimb/ModernUI#178]
Please let me know if the text is unclear, as I translated it using DeepL.

**Describe the bug**
When the "Option to display equipment attributes in tooltips" in Obscure Tooltips and "Option to draw tooltips on world drop items" in Loot Beams: Relooted! are enabled (when attempting to draw Obscure Tooltips contents in the world), the following error message appears in the Modern UI and the screen blacks out while the user is looking at an item whose attributes are displayed, such as a sword.
This bug only occurs when you are looking at the item, not when you are not looking at the item.

`Reloaded text layout engine, res level: 3 to 2, locale: ja_JP, layout RTL: false`

It occurs regardless of the Minecraft language or mod settings, but if you remove one of the mods listed in the Environment, it will stop occurring.

**To Reproduce**
1. Install the mods listed under Environment.
2. Set the following configurations(Probably OK by default):
	- `Equipment Icons` in `obscure-api-client.toml` is `true`.
	- `advanced_tooltips` in `lootbeams-client.toml` is `true`.
	- `worldspace_tooltips `in `lootbeams-client.toml` is `true`.
3. Drop items such as swords, axes, etc., whose attributes are displayed by Obscure Tooltips in the inventory, into the world.
4. The screen blacks out when the dropped item is seen.

**Expected behavior**
Tooltips are drawn in the world as if Modern UI were not installed.

**Environment**
MOD Version(Dependencies are omitted):

- [Modern UI 1.20.1-3.8.2.4](https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/4750809)
- [Loot Beams: Relooted! 1.20.1-1.2.2](https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips/files/4686579)
- [Obscure Tooltips 2.2](https://www.curseforge.com/minecraft/mc-mods/loot-beams/files/4755574)

FML Version: Forge - 47.2.1
Operating System: W11
Graphics Card: RTX 3060Ti

Thank you.

**Comment by BloCamLimb** [comment]
I can't reproduce. I have only three mods loaded.

* lootbeams-1.20.1-1.2.2
* ModernUI-Forge-1.20.1-3.8.2.4-universal
* Obscure-Tooltips-2.2

Also, there's no `obscure-api-client.tom` for Obscure-Tooltips-2.2, it seems that it only exists in 1.19

**Comment by Lenatus** [comment]
Thank you for your reply.
I will forward the content to `Loot Beams` issue.

The file `obscure-api-client.toml` was a configuration file for the `Obsucure API`, a dependent mod of `Obsucure Tooltips`. Sorry for the lack of information.

**Comment by amoooooo** [comment]
Hi loot beams dev here - that code actually shouldn't do anything. It is called in the wrong place. If it's causing issues, you are updating the ui too frequently. This has already been removed in the next update, but please double check what you are using to listen to the ui scale change. It changes so fast that it will never actually do anything.

**Comment by BloCamLimb** [comment]
I just set `OptionInstance#onValueUpdate` to call `Minecraft#resizeDisplay`, this ensures that guiScale can be applied in any case, otherwise simply changing this value won't do anything. Also under normal circumstances, guiScale won't be frequently changed.

**Comment by BloCamLimb** [comment]
I forced it to be executed in the next tick, so it should be ok now.
