### ISSUE TITLE
[Bug] [隔壁ModernUI-MC] TextRenderType.preloadShaders导致过早加载RenderType

### ISSUE THREAD

**Issue by USS-Shenzhou** [BloCamLimb/ModernUI#179]
**Describe the bug**
在`MixinRenderSystem`的
```java
    @Inject(
        method = {"initRenderer"},
        at = {@At("TAIL")},
        remap = false
    )
    private static void onInitRenderer(int debugLevel, boolean debugSync, CallbackInfo ci) {
        TextRenderType.preloadShaders();
    }
```
导致`TextRenderType`的父类`RenderType`在此时也被加载；

**Expected behavior**
`RenderType`通常的顺序是在Mod被加载之后加载。

（我一个新项目需要在`RenderType`的静态初始化块里折腾，又依赖`ModList.get()`所以触发了这个问题。

或许考虑把`TextRenderType#preloadShaders()`和里面的几个字段挪到一个独立的Helper里面去？要是愿意的话我发个pr也行，thx.

**Comment by BloCamLimb** [comment]
It will be moved to `GameRenderer.preloadUiShader`.
