### ISSUE TITLE
[Bug][1.18.2] When using [Glow Ink Sac] on [Sign], it can cause the text on the sign to not glow.

### ISSUE THREAD

**Issue by sweetymajo** [BloCamLimb/ModernUI#180]
**Describe the bug**
As the title, when using [Glow Ink Sac] on [Sign], it can cause the text on the sign to not glow.

**To Reproduce**
1. Place a sign.
2. Input any text.
3. Place any dye on the sign.
4. place glow ink sac on the sign.
5. Set the option [useTextShadersInWorld] to false.
6. See error: the text on the sign to not glow.
7. When I keep a distance from the sign, the text on the sign can light up.

**Expected behavior**
I hope the text on the sign can light up normally when I use shaders, like the old version,

**Screenshots**
![2023-10-09_15 23 58](https://github.com/BloCamLimb/ModernUI/assets/115923988/1a22b696-8eb5-4774-9fdf-7f24c24e7974)

**Environment**
 - Mod Version:3.8.2.1
 - Forge Version:40.2.10
 - Operating System: windows 10
 - Graphics Card: NVIDIA RTX 4090
 - Other Mods: No

**Comment by BloCamLimb** [comment]
The only way is to remove text outline.

**Comment by sweetymajo** [comment]
> The only way is to remove text outline.

How to remove it? Set the value of outlineOffset to 0?

**Comment by BloCamLimb** [comment]
> > The only way is to remove text outline.
> 
> How to remove it? Set the value of outlineOffset to 0?

You can't, I will work on this.

**Comment by sweetymajo** [comment]
> > > The only way is to remove text outline.
> > 
> > 
> > How to remove it? Set the value of outlineOffset to 0?
> 
> You can't, I will work on this.

Thank you very much.

**Comment by Rozbiynk** [comment]
any progress on this?

**Comment by Rozbiynk** [comment]
still issue on 3.9.0.4
![изображение](https://github.com/BloCamLimb/ModernUI/assets/95433246/98125516-d262-4a44-ae81-8fc9c2245da8)

**Comment by BloCamLimb** [comment]
> still issue on 3.9.0.4 ![изображение](https://user-images.githubusercontent.com/95433246/284408420-98125516-d262-4a44-ae81-8fc9c2245da8.png)

It's glow, just in black and no outline, so there is no visual difference. Modern UI outline text only works on modern text shaders enabled, to save GPU memory.

**Comment by Rozbiynk** [comment]
how can i enable it?

**Comment by BloCamLimb** [comment]
> how can i enable it?

In the config file or Preferences screen. Besides, text outline only works for outline fonts (TrueType/OpenType).
