### ISSUE TITLE
[BUG]物品栏全满时通过Corail's Tombstone捡回物品时导致游戏崩溃

### ISSUE THREAD

**Issue by simon2035** [BloCamLimb/ModernUI#181]
发现一个会导致游戏崩溃的bug；

情况：

添加ModernUI后，Corail's Tombstone在curios里增加的收纳袋槽和魔法书槽会不显示（单机档不显示槽，服务器会显示槽但是没有贴图，收纳袋等能正常放入）；然后从Corail's Tombstone的墓碑里捡回物品时，精妙背包不会自动装备在curios槽里，而是装备在胸甲栏；

移除ModernUI后，Corail's Tombstone在curios里增加的收纳袋槽和魔法书槽正常显示且有贴图，从Corail's Tombstone的墓碑里捡回物品时，精妙背包会自动装备在curios的背饰槽里；

bug触发：

死亡后从墓碑捡回物品，如果物品栏有空位，背包会装备在胸甲栏，胸甲则进入物品栏，不会崩溃，但是如果死亡的时候物品栏全满，再从墓碑捡回物品的时候，就会导致游戏崩溃并且坏档，猜测是背包和胸甲同时进入胸甲栏导致的冲突。

移除ModernUI后，由于背包会正常进入背饰槽，没有再出现游戏崩溃的情况；
同时经过测试，其他mod内的饰品，比如植物魔法的戒指，启用ModernUI后，从墓碑捡回物品时不会自动装备到curios里对应的槽位；移除ModernUI后，捡回物品时饰品会自动装备到curios里对应的槽位；

mod版本：

minecraft - 1.19.2

ModernUI - 3.8.2.2

curios - 5.1.4.1

sophisticatedbackpacks - 3.18.58.907

tombstone - 8.2.12

forge - 43.3.0

**Comment by BloCamLimb** [comment]
Post your debug.log and crash-report

**Comment by Maypul** [comment]
Can't comment about crashes as I do not use all listed mods, but ModernUI conflits with Corail Tombstone in a way it breaks curios icons on the server - https://prnt.sc/LnCv5Q50DKbc

**Comment by simon2035** [comment]
> Post your debug.log and crash-report

我重新测试了崩溃原因，导致崩溃的mod是ChinaCraft，并不是以上mod，抱歉；
不过modernUI导致Corail Tombstone中收纳袋和魔法书的curios槽的问题（单人模式不显示，服务器内贴图丢失）以及从墓碑捡回物品时无法正确自动装备到curios槽的问题依旧存在。

**Comment by BloCamLimb** [comment]
Fixed, though I think it's more likely a Forge bug.
