### ISSUE TITLE
[Bug] GUI Scale Auto Gets Set to 6 Instead of 8

### ISSUE THREAD

**Issue by Numorphan** [BloCamLimb/ModernUI#184]
**Describe the bug**
When adding Modern UI to a modpack (or making a fresh modpack with just Modern UI), the GUI scale Auto option defaults to scale 6, instead of 8. I'm not sure if it's different on a smaller monitor, but on a 4k display, Auto should point to 8, the biggest option available.

In addition, there seems to be some interaction with some other mod, because when adding Modern UI to a modpack, the GUI scale option outright removes scales 7 and 8. I've seen this happen with the UniversIO, Prey An Expansive RPG Nightmare Modpack, and The Chocolate Edition modpacks. I haven't tried any other modpacks. There is a workaround; you can still edit options.txt in the modpack to manually put the GUI scale at 7 or 8, but the slider has those two sizes missing.

**To Reproduce**
1. Install Modern UI.
2. Go to Video Settings.
3. View that the GUI Scale option's Auto setting points to 6 instead of 8, and that in a modpack the 7 and 8 scales are completely gone.

**Expected behavior**
When GUI Scale is set to Auto, on a 4k monitor it should be equivalent to setting it to 8. In addition, the options for 7 and 8 should exist and be choose-able via the slider when the mod is in a modpack.

**Screenshots**
Screenshots are from a 1.20.1 forge modpack with only this mod installed.

Auto pointing to 6:
![image](https://github.com/BloCamLimb/ModernUI/assets/25555391/ed0b9231-3200-49bc-aaef-2a1643158d6a)

8 is the actual biggest:
![image](https://github.com/BloCamLimb/ModernUI/assets/25555391/779e7275-8cc6-47e4-bb48-627f6de2a45a)

UI in-game at Auto (6):
![image](https://github.com/BloCamLimb/ModernUI/assets/25555391/3c718e37-b8f8-4fc9-918f-807b15334bc0)

UI in-game at 8:
![image](https://github.com/BloCamLimb/ModernUI/assets/25555391/a2a4236f-668f-4015-9128-ee1bc333f01e)

**Environment**
 - Mod Version: 3.8.2.4 for 1.20.1, and 3.8.2.2 for 1.19.2
 - Forge Version: 47.2.0 on 1.20.1. For 1.19.2, the following forge versions all had the same result: 43.2.10, 43.2.23, and 43.3.2
 - Operating System: Windows 11
 - Graphics Card: Nvidia RTX 4090 FE
 - Other Mods: The Auto issue happens without any mods. The issue with scales 7 and 8 disappearing happens with modpacks, which have the following mod lists:
 - UniversIO: https://www.curseforge.com/minecraft/modpacks/universio/relations/dependencies
 - Prey: https://www.curseforge.com/minecraft/modpacks/prey-beta/relations/dependencies
 - Chocolate Edition: https://www.curseforge.com/minecraft/modpacks/mc-chocolate-edition/relations/dependencies

**Comment by BloCamLimb** [comment]
This is not a bug.

In Modern UI and on high-resolution monitors, Auto GUI scale tends to be smaller than the maximum available GUI scale, this means presenting more content. Then you have to specify a GUI scale instead of Auto, if you want the maximum scale.

In addition, to prevent any mods from overriding the GUI scale slider, we also added GUI scale option to Modern UI preferences screen in the upcoming version.

**Comment by Numorphan** [comment]
Ah okay, with that option added to the Modern UI config then it should be okay. Thanks!
