### ISSUE TITLE
Compatibility with my mods (TipTheScales and Controlling)

### ISSUE THREAD

**Issue by jaredlll08** [BloCamLimb/ModernUI#185]
I'm the author of the TipTheScales and Controlling, 2 of the mods that you list as being replaced on the CurseForge page:
> Controlling (ver 1.15; reason: another way of implementation)
> TipTheScales (ver 1.15 ~ 1.20, forge only; reason: another way of implementation)

Firstly, I don't see anywhere in your code where you touch the key binding screen to replace my Controlling mod, I would appreciate if you can remove that note since it is not true.

Secondly, I am incredibly disappointed that you didn't even bother to reach out to me about the supposed incompatibilities with TipTheScales and instead decided the best course of action would be to [crash the game](https://github.com/BloCamLimb/ModernUI-MC/blob/2e554b92ee88f2cc1269563a5ab2a70e167859ed/forge/src/main/java/icyllis/modernui/mc/forge/ModernUIForge.java#L76), I know you changed it to show a warning instead, but it is honestly just as bad. 

I'm not really bothered that your mod has the same feature as my mod, however I have a user asking me to use the mods together because they really do not like the way that your mod has implemented the feature compared to how my mod has implemented it, and they don't want their users to have to dismiss your warning screen every time they load the pack, so is there any way we can work on this together?

What issues does my mod supposedly have that made you have to show the warning? Is it something that I can fix? I am happy to add code to make our mods work together.

**Comment by BloCamLimb** [comment]
For the first one, we rewrite the entire Control screen in MC1.15, so it is not compatible with Controlling in, and only in MC1.15. See https://github.com/BloCamLimb/ModernUI/blob/1.15/src/main/java/icyllis/modernui/impl/module/SettingControls.java

For the second one, I rewrite the `Window.calculateScale`, which Auto (value=0) does not always mean the maximum GUI scale anymore. There are two reasons:
1. The Vanilla maximum GUI scale is too large, which makes the screen display less content. Therefore, on high-resolution monitors, Modern UI's Auto will be smaller than the maximum possible GUI scale.
2. Modern UI provides resolution-independent outline fonts. When Force Unicode Font is enabled, Modern UI allows users to select any GUI scale. Unlike Vanilla, which can only choose even GUI scales.

Then neither the vanilla GUI scale option nor TipTheScales option can select the maximum possible GUI scale and bypass restrictions on Force Unicode Font. For this, Modern UI provides a new GUI scale option, which completely overrides the functionality of TipTheScales. The warning only tells the user that TipTheScales will no longer have any effect.

Meanwhile, TipTheScales can't work with sodium, rubidium and OptiFine. But we have a way to work with them, we have also added this modified GUI scale option in our own settings GUI.

We can't remove the warning unless TipTheScales can satisfy these requirements.

**Comment by jaredlll08** [comment]
From the sounds of what you have said, I don't see a good way for our mods to be compatible, if need be I'm happy to just disable my mod if yours is installed (like I do for optifine and sodium), but I would appreciate if the warning screen would be removed, there is no harm having both mods installed at the same time, so telling people to remove mods is not the right thing to do.
