### ISSUE TITLE
[Bug] Chat onHover tooltips color are always black -> cant read tooltip

### ISSUE THREAD

**Issue by Omena0** [BloCamLimb/ModernUI#186]
**Describe the bug**
The hover tool tips (for example advancement hovers) are always black even when changing the color in the tellraw command

**To Reproduce**
1. Go to a creative world
2. Either run a tellraw command with an onHover event or get an advancement
3. Hover tooltip
4. Tooltip text is black and unreadable

**Expected behavior**
Tooltip color is the one set in tellraw

**Screenshots**
![image](https://github.com/BloCamLimb/ModernUI/assets/82773737/0b39dd98-88dc-49fd-b376-4d1a6f7f1760)

**Environment**
 - Mod Version: 3.8.2.4
 - Forge Version: (fabric) mc-1.20.1 fabric-0.14.22
 - Operating System: Windows 10 Pro
 - Graphics Card: NVIDIA GeForce GTX 950M
 - Other Mods: sodium-fabric-mc1.20.1-0.5.3.jar, ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar, fabric-api-0.90.0+1.20.1.jar

Issue does not persist without modern ui installed. (so its not a sodium issue)

**Comment by Omena0** [comment]
Text also black even when specifying hover color in tellraw command
![image](https://github.com/BloCamLimb/ModernUI/assets/82773737/21ee7450-c7e4-460a-b238-8a089c7d3f46)

**Comment by BloCamLimb** [comment]
We confirmed that this reproduces when
1. Sodium is installed
2. Modern Tooltip is enabled
3. Neither Iris shaders nor ModernUI blur effect (a shader) is enabled

**Comment by BloCamLimb** [comment]
I tried a dozen methods, but none of them seem to fix this problem. Because Sodium is no longer actively maintained, either you stop using Sodium or you disable Modern Tooltip in ModernUI preferences.

**Comment by BloCamLimb** [comment]
I have re-implemented non-rounded tooltip style in 3.10.0. Now you can play Modern Tooltip with Sodium, what you need is to turn off Preferences -> Tooltip -> Border Style -> Rounded Corners
