### ISSUE TITLE
[Bug] The mod Isn't working

### ISSUE THREAD

**Issue by SirRoderic2** [BloCamLimb/ModernUI#187]
**Describe the bug**
The tooltip border works fine, and the text in the mod's config screen is actually changed, but nothing else is, and I've also tried it with no other mods at all and it still doesnt work

**Screenshots**
https://imgur.com/a/86KFwjM

**Environment**
 - Mod Version: 3.9.0.2
 - Forge Version: 43.3.5
 - Operating System: Windows 10 Pro
 - Graphics Card: RTX 3060 12GB
 - Other Mods: none

**Comment by BloCamLimb** [comment]
Are you saying that the text engine is not working?
In versions 3.9.0.2 and above, the vanilla ASCII font is included by default. If you don't want it, you either
1. turn on *Force Unicode Font* in Options > Language
2. change *Default Font Behavior* to *Keep Other* in Modern UI Center > Preferences > Text Layout

**Comment by SirRoderic2** [comment]
Thank you, I didn't know I had to turn Force Unicode on ( and set the text layout preferences to Keep other so it doesn't revert to vanilla font every time I restart the game)
