### ISSUE TITLE
[Bug] “fallback” falls back to that dogsh font

### ISSUE THREAD

**Issue by ChromaPIE** [BloCamLimb/ModernUI#188]
**Describe the bug**

`firstFontFamily = "[directory redacted]/NBArchitektStdNeue-Bold.otf"` it's a font without simplified chinese support
`fallbackFontFamilyList = ["[redacted]/字魂创粗黑.ttf"]` it should look like [this](https://izihun.com/shangyongziti/574.html)

whats expected is that for the english letters and numbers and stuff they use NB Architekt Std Neue and for the chinese characters they use 字魂创粗黑.

For 1.12.2 SmoothFont it's easily achieved by double clicking 字魂创粗黑, it'll get it highlighted in yellow, meaning that it's selected as a fallback font, then just select NB Architekt Std Neue and apply the settings.

But for ModernUI it falls all the way back to that kind of ugly as serif font. see the screenshot below.

<details> 
    <summary><b>final result</b></summary>
    <img src="https://github.com/BloCamLimb/ModernUI/assets/56111366/64760b51-e47e-4b94-ad4d-430d58fe453c">
</details>

Don't think extra info is actually needed but let me know if any of those are necessary.

**Comment by BloCamLimb** [comment]
Tooltip and config description have not been corrected, only registered fonts can be used as fallback fonts. Registered fonts refer to font files in the "modernui:font/" in resource packs.

For now, you have to create a resource pack, then either put font files in "modernui:font/" or append ttf providers in "minecraft:font/default.json".

I plan to add a new option "Preferred Asian Font Family" to improve this.

**Comment by BloCamLimb** [comment]
Now fallback list accepts font files, your setup should work in 3.10.0 releases
