### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by benjaminBJ** [BloCamLimb/ModernUI#19]
**Describe the bug**
When looking at a player or entity with a nametag, every block entity or mob is visible trough objects.

**To Reproduce**
1. enter a server
2. look to another player
3. Entities or mobs now are visible

**Expected behavior**
It shouldn't happen basicaly

**Screenshots**
![2020-08-25_18 58 16](https://user-images.githubusercontent.com/54908517/91236081-000e2080-e705-11ea-9a81-10410ded2e74.png)

**Versions you are on**
 - Mod Version: 1.16.1-2.0.3.60
 - Forge Version: 32.0.108

**Comment by BloCamLimb** [comment]
outdated version
