### ISSUE TITLE
[提問] 告示牌字體(繁中)

### ISSUE THREAD

**Issue by liangmoe** [BloCamLimb/ModernUI#190]
我要怎麼設定才可以讓告示牌的字體和其他設定等等的字體一樣圓潤？或是其實沒有這個設定嗎
告示牌不圓潤的字體：
![image](https://github.com/BloCamLimb/ModernUI/assets/135343248/0f1c7569-b05e-4456-a8b5-3d72de34285a)
![image](https://github.com/BloCamLimb/ModernUI/assets/135343248/ccb4a12a-f1a9-4f4d-935c-209fd96885d6)
設定欄位圓潤的字體：
![image](https://github.com/BloCamLimb/ModernUI/assets/135343248/c90cf73a-896d-4118-a72f-e21edf79f450)
我目前的設定檔(來自config/ModernUI)：
[text.txt](https://github.com/BloCamLimb/ModernUI/files/13443524/text.txt)

使用版本：Modern UI 3.9.0.5 Fabric

**Comment by BloCamLimb** [comment]
This is normal.

In 3D, ModernUI will use SDF (signed distance field) rendering, but this requires custom shaders, which are not compatible with ShaderPack (OptiFine, Iris). Then it will fallback into bitmap rendering, you can find such options and descriptions in Preferences, Text Rendering.

这是正常的。

在3D中，ModernUI会使用SDF（符号距离场）渲染，但这需要自定义着色器，而这些着色器与光影包（OptiFine、Iris）不兼容。因此它将退化到位图渲染，您可以在“偏好设置”、“文本渲染”中找到这样的选项和描述。

**Comment by liangmoe** [comment]
thanks for the explanation!! i'm new to this mod and i love it, thanks
