### ISSUE TITLE
[Bug] Non-critical error on exiting the game with 'X', mod conflict

### ISSUE THREAD

**Issue by Maypul** [BloCamLimb/ModernUI#193]
**Describe the bug**
There is an error log generated upon closing the game with 'X' window button instead of exiting it normally via Exit Game button. The error is not impacting the game in any way as far as I know and just spams log file. This is definitely a mod conflict with something as it does not happen while this mod is standalone or removed from this "pack".

**To Reproduce**
1. Have following mods: https://pastebin.com/SYRaAvjy
2. Run the game
3. Exit the game via 'X' window button
4. Check logs and see at the end of the log: https://pastebin.com/wTGZw5qA

**Expected behavior**
No error, clean log :)

**Screenshots**
Log: https://pastebin.com/wTGZw5qA

**Environment**
 - Mod Version: Newest, 3.9.0.2
 - Forge Version: 43.2.21 / MC 1.19.2
 - Operating System: Windows 10
 - Graphics Card: Radeon RX 5900
 - Other Mods: https://pastebin.com/SYRaAvjy

**Comment by BloCamLimb** [comment]
This is not a compatibility issue. I added a "shutdown" program to make a clean exit, but it executed at the wrong time in your case. I will move it inside a more reasonable method.

**Comment by BloCamLimb** [comment]
Should be fixed in 3.10.0

**Comment by Maypul** [comment]
Seems so, my pack seems to exit normally with no errors now. Thanks
