### ISSUE TITLE
[Bug] Rendering issue with No Chat Reports

### ISSUE THREAD

**Issue by Maypul** [BloCamLimb/ModernUI#194]
**Describe the bug**
Rendering issue with No Chat Report mod. Some of its added text is not visible with ModernUI enabled.

**To Reproduce**
1. Install ModernUI and No Chat Report + Other Mods (with only these two text loads fine, a third unknown mod must be meesing it up)
2. Load a single player world
3. Press / button to open up chat
4. Look and bottom right corner
5. Hover over the checkmark button
6. See no text

**Expected behavior**
Text is visible

**Screenshots**
No Chat Reports only installed: https://prnt.sc/-Lo3VM8GW8XX
Modern UI + No Chat Reports only + Other Mods: https://prnt.sc/zxbOcM9JjcXi but also second button works https://prnt.sc/EU8-GyYSymyV
No Chat Reports only + Other Mods: https://prnt.sc/Bd8o4xGkNy8A

**Environment**

    Mod Version: Newest, 3.9.0.2
    Forge Version: 43.2.21 / MC 1.19.2
    Operating System: Windows 10
    Graphics Card: Radeon RX 5900
    Other Mods: https://pastebin.com/SYRaAvjy

**Comment by BloCamLimb** [comment]
From your screenshot, it appears that you are using the old version of config files. Then I think you should turn off ModernUI tooltip fade-in effect (by setting tooltip fade-in duration to 0).

**Comment by Maypul** [comment]
Thanks for the tip about old config, I usually look for warning in log that says "Correcting..." when mod updates its config file, have forgotten that some mods do not do that. After regenerating config and changing values back to the ones I had before, now it works just fine.
https://prnt.sc/f1ZQF9InjcZU
https://prnt.sc/j5zl1QUFwOHG
