### ISSUE TITLE
[Bug] 1.20.4 support [Fabric]

### ISSUE THREAD

**Issue by Zorklis** [BloCamLimb/ModernUI#197]

**Comment by BloCamLimb** [comment]
This is impossible for now. Our dependency mod https://github.com/Fuzss/forgeconfigapiport has not been updated yet. Our toolchain architectury still has some bugs.

**Comment by Zorklis** [comment]
Any updates? Forge Config Api Port is on 1.20.4 version now (since 2023-12-21).
So is it just Architectury remaining with problems? But that too seems to be on Fabric 1.20.4 (since 2023-12-09)

**Comment by BloCamLimb** [comment]
1.20.4 support is done, but I need to backport all changes to 1.18.2, 1.19.2, 1.19.4, and 1.20.1 before releasing them.
