### ISSUE TITLE
Clunky Camera movement while running

### ISSUE THREAD

**Issue by DatrixTHLK** [BloCamLimb/ModernUI#2]
**Describe the bug**

The character runs but the camera jerks everytime a step is taken by the character. 

**To Reproduce**

Steps to reproduce the behavior: (For the Freeze uo.)
1. Start up a new world
2. Start running

**Expected behavior**

What I expected to happen was it not to be so jerky

**Screenshots**

Video of Running Camera Clunkiness (Inside Zip folder): 
[Minecraft_ 1.15.2 - Singleplayer 2020-04-11 17-18-40.zip](https://github.com/BloCamLimb/ModernUI/files/4465428/Minecraft_.1.15.2.-.Singleplayer.2020-04-11.17-18-40.zip)

**Versions you are on**
 - Mod Version: 1.3.5.30-universal
 - Forge Version: 31.1.43

**Comment by BloCamLimb** [comment]
Have you installed any other mods?

**Comment by DatrixTHLK** [comment]
I have 112 other mods. If you are unable to reproduce it...then, I'm going to have to do the old school searching method for which mod is causing the glitchy issues. Oh well, when I find out which mod it is I'll let you know. Might as well close this issue until I can back with you on this. If you'd rather I'll just go to the mod author whose mod is causing the issue when I find it out.

**Comment by DatrixTHLK** [comment]
Hi again, I went through each mod started the game up to 12 different times walked around and the camera movement was just fine.  Whatever mod was causing the issue has updated possibly.  If it comes around again, I'll let you know.
