### ISSUE TITLE
Beds, chests all overlay when sign is placed on bed.

### ISSUE THREAD

**Issue by jbefu** [BloCamLimb/ModernUI#20]
With sign on bed:
![image](https://user-images.githubusercontent.com/43292177/92308570-7547e400-ef96-11ea-8ee0-dffef628bfcc.png)

Without sign on bed:
![image](https://user-images.githubusercontent.com/43292177/92308580-885ab400-ef96-11ea-8eb4-4cd6ac1db0ca.png)

**Comment by jbefu** [comment]
Also, this only occurs if the sign has something written on it.

**Comment by BloCamLimb** [comment]
Can't reproduce

**Comment by BloCamLimb** [comment]
Turning off OptiFine Fast Render would definitely solve this problem
