### ISSUE TITLE
[Bug] 处于多人游戏的服务器列表时崩溃，发生空指针异常

### ISSUE THREAD

**Issue by 0Lynk** [BloCamLimb/ModernUI#200]
**Describe the bug**
具体描述：处于多人游戏的服务器列表时崩溃，多发于从服务器退出并留在服务器列表等待一段时间后，崩溃报告提示空指针异常

**To Reproduce**
1. 加入本地服务器
2. 退出本地服务器
3. 留在服务器列表界面等待一段时间
4. 崩溃发生（并不总是发生，但有很高几率）

**Environment**
 - Mod Version:3.9.0.4
 - Forge Version:47.1.85（1.20.1，neoforge）
 - Operating System:windows 10
 - Graphics Card:2060s
 - Other Mods:很多，具体见崩溃报告

崩溃报告：https://mclo.gs/zuaEDrP

**Comment by 0Lynk** [comment]
logs：https://mclo.gs/uLfKuwm

**Comment by BloCamLimb** [comment]
这和ModernUI没有任何关系，而且这是Minecraft原版的一个bug。
