### ISSUE TITLE
[Bug] 遇到锦致装饰路标时发生崩溃

### ISSUE THREAD

**Issue by Le7emps** [BloCamLimb/ModernUI#201]
**Describe the bug**
遇到锦致装饰路标时发生崩溃（客户端），再次登录上线后就没事了

**Environment**
 - Mod Version:3.10.0.4
 - Forge Version:47.2.20
 - Operating System:windows
 - Graphics Card:
 - Other Mods:

详见崩溃报告：https://mclo.gs/xbr6HWP

**Comment by BloCamLimb** [comment]
看不出哪有问题，Modern UI只是调用原版的方法加载模糊效果。这要么是你的显卡驱动有一些问题，要么是其他模组改了原版的东西，也可能是显存不够。如果总是崩溃，你可以关闭Modern UI的界面背景模糊。
