### ISSUE TITLE
Text display bug when the "Rounded Corners" function is enabled

### ISSUE THREAD

**Issue by Erdexad** [BloCamLimb/ModernUI#202]
**Describe the bug**
When "Rounded Corners" is enabled, all text becomes unreadable

**To Reproduce**
1. Go to the “Settings” section.
2. Click Border Style.
3. Click Rounded Corners.
4. Enter "[аук]" into the chat
5. Press Enter
6. Click on your message "[товары на аукционе]"
7. Review the error

**Expected behavior**
I expect normal text display

**Screenshots**
https://youtu.be/sU4D-FN2PU0

**Environment**
 - Mod Version: 3.10
 - Forge Version: Fabric 0.15.6
 - Operating System: Windows 11
 - Graphics Card: Rtx 4070
 - Other Mods: Sodium (without Sodium there is no bug)
 - Server eu.restartcraft.fun. Lapis SkyBlock Mode

**Also**
This happens in all menus that were opened after clicking on certain link fragments in the text in the chat
If you open the menu by entering a command into the chat, all the text will be readable, if you open the same menu by clicking on the text in the chat, all the text will be unreadable

**Comment by BloCamLimb** [comment]
Duplicated with #186

I couldn't find a way to fix the tooltip compatibility with Sodium, so I gave up. The disabling of rounded corners that you see is the expected behavior on Fabric, which is also the solution I mentioned on Modrinth. Other workarounds are: enable Iris Shaders;  enable Blur Effect in all GUIs (including chat screen).

**Comment by BloCamLimb** [comment]
I have an idea. Drop the use of canvas to render tooltips, avoiding interop between Modern UI standalone render pipeline and Minecraft render pipeline.

**Comment by BloCamLimb** [comment]
I just renewed tooltip rendering with better shadow effect and performance. Switching to Minecraft RenderType also fixes this rendering glitch with Sodium.

**Comment by Erdexad** [comment]
Did I understand correctly? So you will fix this problem in the next version of the mod?

**Comment by BloCamLimb** [comment]
> Did I understand correctly? So you will fix this problem in the next version of the mod?

That's right.

**Comment by Erdexad** [comment]
Hooray! Text now displays correctly along with the corner rounding feature!
Thanks!
