### ISSUE TITLE
[Bug] 某些情况会出现字体混乱？

### ISSUE THREAD

**Issue by djkcyl** [BloCamLimb/ModernUI#208]
![image](https://github.com/BloCamLimb/ModernUI/assets/59153990/7f076ed8-4b84-4627-8934-cf91c047686f)
![f90c5791bf91ef5f9f740ca9b3e508ba](https://github.com/BloCamLimb/ModernUI/assets/59153990/00bc7914-2e67-44fb-b93d-fefda078cc66)
![7de1ebf067e1ec248be7b65e82b0e6e9](https://github.com/BloCamLimb/ModernUI/assets/59153990/79e8d10b-9596-45a4-b8d6-1f25d9dbe595)
![91cdda445eac8cb4411ee0468db70ba5](https://github.com/BloCamLimb/ModernUI/assets/59153990/0829b4fa-27a1-4ca6-a10d-33dffa50c41b)

没有任何征兆的就变成这样了

**Comment by BloCamLimb** [comment]
请按照模板反馈bug
提供debug.log latest.log
显卡型号
系统信息

**Comment by djkcyl** [comment]
- GPU: GTX 1660
- 系统是 windows 10

日志暂时没有了，是偶然情况，今天遇到的话再补充

补充一个细节：在语言菜单中开关 unicode 或者切换语言都可以使字体修复

**Comment by BloCamLimb** [comment]
如果你装了ImmediatelyFast，请检查它的 hud_batching、font_atlas_resizing 和 fast_text_lookup 是否已经禁用。

**Comment by djkcyl** [comment]
> 如果你装了ImmediatelyFast，请检查它的 hud_batching、font_atlas_resizing 和 fast_text_lookup 是否已经禁用。

没有装这个mod，这个问题到现在也没有再遇到过了

**Comment by BloCamLimb** [comment]
你是否安装了Emojiful、Embeddium？

**Comment by BloCamLimb** [comment]
This can be attributed to Emojiful.
