### ISSUE TITLE
cant enable debug mode to get screen class names

### ISSUE THREAD

**Issue by peow** [BloCamLimb/ModernUI#211]
![image](https://github.com/BloCamLimb/ModernUI/assets/105888751/a8e968e4-fb07-4892-906e-d4c371d08701)

I tried to follow this tutorial because a mod that adds a camera (https://modrinth.com/mod/polaroidcamera) is getting a blurry image because of the Modern UI, I saw that there was a blacklist to put the name of the mod screen class, but following the tutorial no file called debug.log was created in my minecraft logs folder, I also tried looking in latest.log but I didn't find anything

------------
screenshots of the mod

![2024-04-12_16 48 30](https://github.com/BloCamLimb/ModernUI/assets/105888751/74e304f2-6a12-486b-bfae-1bd9ac1b7ce3)
![2024-04-12_16 48 31](https://github.com/BloCamLimb/ModernUI/assets/105888751/25bbb284-fbcf-45dd-8240-63abaf7d7d52)

my log: https://gist.github.com/peow/dd4140cf80e2f6359cb911ccfe9a5726

my "common.toml" file:
![image](https://github.com/BloCamLimb/ModernUI/assets/105888751/f97c17b1-dfe0-4f1f-b1cd-129137e67158)

**Comment by BloCamLimb** [comment]
You may use Ctrl+Shift+P to print a debug message. For the mod you mentioned, the screen class name is `net.hyper_pigeon.polaroidcamera.client.render.CameraScreen`.

We use the issue tracker specifically for bug reports and feature requests. It is better to ask questions in our Discord channel.
