### ISSUE TITLE
[Bug] Crash Radeon/AMD Graphics Card? 1.20.1-3.10.1.4

### ISSUE THREAD

**Issue by HalestormXV** [BloCamLimb/ModernUI#213]
**Describe the bug**
Access Violation Crash on Start while Loading Game. This is a report from a friend of mine so my means of testing is limited as I utilize an NVIDIA card. I do know it is related to this mod though because once the Mod is disabled there is no longer a crash. Perhaps it is related to the use of an AMD card? Or an older AMD card? See logs attached.

**To Reproduce**
1. I had them simply start the game
2. It crashed on loading
3. I then told them to provide me with the report since it works fine for me.

**Expected behavior**
Game to load just as it did for my two other friends (who were running NVIDIA Cards) as we were all on a Discord call while i was having them test.

**Screenshots**
See attached log

**Environment**
 - Mod Version: 1.20.1-3.10.1.4
 - Forge Version: 47.2.30
 - Operating System: Windows 10 , 64 bit Build 19041
 - Graphics Card: AMD Radeon RX 580
 - Other Mods: See Modpack Link: https://www.curseforge.com/minecraft/modpacks/mageknight-chronicles

[hs_err_pid12036.log](https://github.com/BloCamLimb/ModernUI/files/15282799/hs_err_pid12036.log)

**Comment by BloCamLimb** [comment]
No fault can be found on ModernUI side, it's possibly a bug inside AMD driver. What's the AMD graphics driver version? Could you provide a debug.log?

I have AMD Ryzen 7 4800H with Radeon Graphics and a driver version of 31.0.21912.14, and it works well.

Get the latest driver: https://www.amd.com/en/support/downloads/drivers.html/graphics/radeon-600-500-400/radeon-rx-500-series/radeon-rx-580.html

Similar issues: https://github.com/sp614x/optifine/issues/4065 https://github.com/sp614x/optifine/issues/4089 https://github.com/TheCherno/Hazel/issues/440

**Comment by HalestormXV** [comment]
I can't get the person to re-do the testing. It seems they have vanished lol. This could be as you mentioned a bad driver on their end. It still works fine for me and the last I heard from them is that they did in fact have a driver update. As it is unrelated to ModernUI and as I said, unfortunatley this is one of those incidents where I am trying to report for the player and therefore have to rely on them to get me the information i will close this out. Thank you again for the time.
