### ISSUE TITLE
[Bug] 與FeyTweaks不相容

### ISSUE THREAD

**Issue by IamNotBrianZ** [BloCamLimb/ModernUI#214]
**Describe the bug**
同時加入FeyTweaks與ModernUI會導致遊戲崩潰

**To Reproduce**
如上所述

**Expected behavior**
應該要有跳窗提示模組不相容
想在cobblemon官方模組包中加入您的模組，花了點時間才找出問題

**Screenshots**

**Environment**
 - Mod Version:3.10.1.4(Fabric)
 - Fabric Version:0.15.10
 - Operating System:Win10
 - Graphics Card:1650Ti
 - Other Mods:FeyTweaks

**Comment by BloCamLimb** [comment]
FeyTweaks won't provide your performance improvement once you have Modern Text Engine enabled, then that mod is completely useless. You either disable Modern Text Engine or remove FeyTweaks. The imcompatibility hint will be added in the next version.

To disable Modern Text Engine, open `.minecraft/config/ModernUI/bootstrap.properties` or create one if none, add line `modernui_mc_disableTextEngine=true`.

**Comment by IamNotBrianZ** [comment]
Thanks for your reply.
Your mod adds a lot of features(and i appreatiate that)
That, it has a high probability to be incompatible/replace other mods.
The problem is that, when i try to add ModernUI to a random modpack, it is very possible to crash the game.
I don't have other problems, have a nice day!
