### ISSUE TITLE
[Bug] smooth scrolling in sophisticated storage GUIs

### ISSUE THREAD

**Issue by Lucky-56** [BloCamLimb/ModernUI#215]
**Describe the bug**
Smooth scrolling does not work with an sophisticated storage GUI (I have to scroll multiple times)

**To Reproduce**
1. install [Sophisticated Storage](https://curseforge.com/minecraft/mc-mods/sophisticated-storage) and [Sophisticated Core](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
2. either have GUI scale set to 4 or have a small screen
3. place a double gold chest (in example) or higher tier
4. open it
5. place items inside
6. scroll
7. observe

**Expected behavior**
I did not expect anything just would've been nice to be able to blacklist some GUIs
"For the scrolling to work properly"

**Screenshots**
Idle:
![2024-05-21_01 49 34](https://github.com/BloCamLimb/ModernUI/assets/55949451/c2c6ae4b-615f-43f4-8849-415d90b096c7)

Scrolled once:
![2024-05-21_01 49 38](https://github.com/BloCamLimb/ModernUI/assets/55949451/4909eb9e-4459-4fb4-b264-9d09ae54e705)

Scrolled twice:
![2024-05-21_01 49 41](https://github.com/BloCamLimb/ModernUI/assets/55949451/68074dd8-b543-4156-b650-a7b496ce82de)

**Environment**
 - Mod Version: 3.10.1.4
 - Forge Version: 47.2.32
 - Operating System: Win11
 - Graphics Card: GeForce RTX 3060
 - Other Mods: 
   - Sophisticated Core *0.6.22.611*
   - Sophisticated Storage *0.10.25.804*

**Comment by Lucky-56** [comment]
not the only issue but the most noticable one at a glance

**Comment by BloCamLimb** [comment]
That mod only `updateSlotsYPosition` on `mouseScrolled` and `mouseDragged`, it ignores scroll animation. The smooth scrolling is done by updating `scrollDistance` every frame, there's no callback method can be used to notify subclasses the scroll changes, so there's nothing we can do. To solve this issue, you need to ask the author of that mod to find the `scrollDistance` change during the `render` call.

https://github.com/P3pp3rF1y/SophisticatedCore/blob/f10ed7eaa2fc604ab283bcf8f637a79bf8503372/src/main/java/net/p3pp3rf1y/sophisticatedcore/client/gui/controls/InventoryScrollPanel.java#L90-L101
