### ISSUE TITLE
[Bug] Strange mask with refined storage 2 in fabric

### ISSUE THREAD

**Issue by link-fgfgui** [BloCamLimb/ModernUI#216]
**Describe the bug**
Install modern ui and refined storage 2. When the mouse is on the button next to the terminal/synthetic terminal, a special mask will form a circle and clear part of the UI.
安装modern ui 和 refined storage 2,当鼠标待在终端/合成终端的边上的按钮时,会有特殊的遮罩围成一圈并清除一部分ui

**To Reproduce**
1. place a grid
2. open the grid
3. move mouse to the button
4. see the strange mask

**Expected behavior**
There shouldn't be this mask.
不应该有这个遮罩
**Screenshots**
![image](https://github.com/BloCamLimb/ModernUI/assets/96362154/1246a1a0-da9d-4bd8-ab86-af3bed86da70)
![image](https://github.com/BloCamLimb/ModernUI/assets/96362154/8659031c-847a-411d-b7b8-591b0610215d)

**Environment**
 - Mod Version:Fabric-1.20.1-3.10.1.4
 - Forge Version:Fabric 0.15.11
 - Operating System:windows 11 23h2 22631.3593
 - Graphics Card:rtx4050
 - Other Mods:refined storage 2

**Comment by BloCamLimb** [comment]
This is a drawing order issue in Refined Storage.

If the shadow effect of the tooltip is enabled, the coverage area of fragment output will be larger, and depth test is enabled on Minecraft's main target. To ensure transparency work, not only do you need to ensure Painter's Order, but you also need to ensure that the depth is greater than the depth of the existing fragments. The tooltip has a depth of 400, so you only need to make the tooltip the last draw operation of the render pass.

Relevant issue: https://github.com/neoforged/NeoForge/issues/992
