### ISSUE TITLE
Incorrect display of apostrophe in Ukrainian language

### ISSUE THREAD

**Issue by pgmtags** [BloCamLimb/ModernUI#217]
**To Reproduce**
1. Go to 'Multiplayer'

2. See error

**Expected behavior**
Apostrophe must be without a pause [ **Пряме з'єднання** ]

**Screenshots**
![зображення](https://github.com/BloCamLimb/ModernUI/assets/62100293/03fa15ee-93a7-4683-919c-3c96bbd9a301)

**Environment**
 - Mod Version: 3.10.1.4
 - Forge Version: 47.3.0
 - Operating System: Windows 11 Pro x64
 - Graphics Card: GTX 750 Ti
 - Other Mods: https://drive.google.com/file/d/1No2xI347-q6XROa_IqyeljsTNN9imqTI/view?usp=sharing

**Comment by pgmtags** [comment]
**The defect is displayed without the package**
An update is needed, I installed this modification after archiving the package to google drive

**Comment by BloCamLimb** [comment]
From https://en.wikipedia.org/wiki/Apostrophe, there are three characters that represent apostrophe in Unicode:
* U+0027 ' APOSTROPHE
* U+2019 ’ RIGHT SINGLE QUOTATION MARK
* U+02BC ʼ MODIFIER LETTER APOSTROPHE

What you typed is U+0027, what is displayed in the game is U+2019, some people consider U+02BC the proper character for Ukrainian apostrophe.

Most search engines will consider U+0027 and U+2019 as the same character. In most fonts, U+2019 and U+02BC display the same. However, the default font used by ModernUI is for displaying CJK Unified Ideographs, the U+2018 and U+2019 are used for single quotation marks in Chinese and Korean, then they are designed as full-width characters.

There are two solutions:
* Give feedback to Mojang to discuss a more appropriate apostrophe character for Ukrainian language.
* Choose another font as your preferred font in game, for example, Segoe UI.

**Comment by pgmtags** [comment]
I didn't know about the possibility of changing the font, 

I also noticed that the letter ` Є ` was too small, as I realised it was also a feature of the standard font

Thanks for your full answer :)
