### ISSUE TITLE
[Bug] Font color ignored in world renderer with OptiFine shaders

### ISSUE THREAD

**Issue by HwuSam** [BloCamLimb/ModernUI#22]
Vanilla
![n1](https://user-images.githubusercontent.com/72545569/95433935-333e0380-0983-11eb-9111-234cd5884798.JPG)
![n2](https://user-images.githubusercontent.com/72545569/95433939-346f3080-0983-11eb-934c-ef2d6363e810.JPG)

Modded
![n3](https://user-images.githubusercontent.com/72545569/95433941-3507c700-0983-11eb-9c63-f380416dc4f9.JPG)
![n4](https://user-images.githubusercontent.com/72545569/95433943-35a05d80-0983-11eb-9c1a-249c5ad88241.JPG)

**Comment by BloCamLimb** [comment]
please tell the versions (minecraft, forge and mod) you're on and steps to reproduce this bug

**Comment by HwuSam** [comment]
> please tell the versions (minecraft, forge and mod) you're on and steps to reproduce this bug

Minecraft1.6.3
Forge 1.16.3 - 34.1.0
mods installed:
XaerosWorldMap_1.11.0_Forge_1.16.3
Xaeros_Minimap_20.25.0_Forge_1.16.3
OptiFine_1.16.3_HD_U_G3_MOD
ModernUI-1.16.3-2.2.0.64-universal

**Comment by HwuSam** [comment]
Thanks again.
After few hours testing.
i found out the mod globalRenderer = true
 is incompatible with shaders mod
it will caused the font color missing

**Comment by BloCamLimb** [comment]
Can't reproduce again since MC 1.18.2 and Modern UI 3.8.0
