### ISSUE TITLE
[Bug] 对于灰度图等非32位颜色的图片，渲染上存在问题

### ISSUE THREAD

**Issue by AW-CRK14** [BloCamLimb/ModernUI#220]
在Canvas中渲染Image时，若图像源使用的是灰度等8位或其它非32位图像，其内容将会出现问题，例如透明背景变为不透明黑色，图像内容变为绿色或其它变色情况。如，针对一张如下的使用8位灰度存储的图像：
![04ce3f634649d77eb36521c99af0c205](https://github.com/BloCamLimb/ModernUI/assets/63481832/2dcb2ecc-2e10-4a55-b213-3029c58797f6)
其渲染效果将变为
![ac59cd96dcab7a304b8bace9aeaa3d4c](https://github.com/BloCamLimb/ModernUI/assets/63481832/eebc5b53-f33c-451e-84c8-425a0cf76590)

**Comment by BloCamLimb** [comment]
Fixed in 3.11
