### ISSUE TITLE
Legendary Tooltips Incompatibility

### ISSUE THREAD

**Issue by Shodelat** [BloCamLimb/ModernUI#221]
There is nothing to desrcibe honestly. ModernUI overrides it or smth. LT doesn't any of its features.

**Comment by BloCamLimb** [comment]
Disable Modern Tooltip if you prefer to Legendary Tooltips.

**Comment by Shodelat** [comment]
> Disable Modern Tooltip if you prefer Legendary Tooltips.

I don't :(
Is there any chance it'll work in future updates?
