### ISSUE TITLE
[Bug] 在1.20.1Fabric中与IBE产生冲突，导致IBE的SNBT编辑器功能无法使用

### ISSUE THREAD

**Issue by yizhi9jiyan9** [BloCamLimb/ModernUI#223]
版本：1.20.1 Fabric 0.15.10
IBE版本：2.2.8
ModernUI版本：3.10.1.4
FabricAPI版本：0.92.2
描述：
在加载了ModernUI后，使用IBE的SNBT编辑功能会使IBE发送一条报错信息，内容如下：
[error.log](https://github.com/user-attachments/files/16179539/error.log)

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI-MC/commit/710db92583118d9cb394e7a7b824cf4ceebb599c 应该修复了

**Comment by BloCamLimb** [comment]
Fixed in 3.11
