### ISSUE TITLE
[Bug] 在调整字体时滑动会导致字体消失

### ISSUE THREAD

**Issue by adsioho** [BloCamLimb/ModernUI#224]
版本：1.20.1,Forge 47.2.32,Mod版本 3.10.1.4
复现：
打开面板找到调整字体的页面，然后打开此页面
找到上下滑块，鼠标按住，此时字体页面消失变为空的一片(但字体切换功能正常）
切换一遍字体后字体切换页变为正常(可以继续复现)

https://github.com/user-attachments/assets/5e6dddfa-7f3e-4f43-af64-2844f9814d1c

**Comment by adsioho** [comment]
不会压根没做滑块罢

**Comment by BloCamLimb** [comment]
Right, there are some known issues with popup windows.

**Comment by adsioho** [comment]
滑块功能已删除，无需解决（不是哥们
