### ISSUE TITLE
[Bug] 使用VC跨服 显示不正常 forge

### ISSUE THREAD

**Issue by windy664** [BloCamLimb/ModernUI#225]
**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/MohistMC/Mohist/issues/3235)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - Mod Version:[选装][现代化 UI] ModernUI-Forge-1.20.1-3.10.1.4-universal
 - Forge Version:47 .3 .5
 - Operating System:wind10
 - Graphics Card:
 - Other Mods:

**Comment by BloCamLimb** [comment]
发送 debug.log

**Comment by windy664** [comment]
经测试，仅mohist跨服会出现，其他服务器核心不会。
