### ISSUE TITLE
[Bug]Can't working on mac os

### ISSUE THREAD

**Issue by sasdj2418** [BloCamLimb/ModernUI#23]
I heard that openGL is not supported since mac mojave, not sure if this is the reason.

**Error message**

> [Render thread/FATAL] [ModernUI/Render]: Explicit attrib location is not supported
> [Render thread/FATAL] [ModernUI/Render]: Vertex array object is not supported
> [Render thread/FATAL] [ModernUI/Render]: Uniform buffer object is not supported
> [Render thread/FATAL] [ModernUI/Render]: Separate shader objects is not supported
> [Render thread/FATAL] [ModernUI/Render]: Explicit uniform location is not supported

**Screenshots**
![Error](https://i.imgur.com/NPAWPrv.jpg)

**Versions you are on**
 - Mod Version:
ModernUI-1.16.3-2.2.0.64-universal
OptiFine_1.16.3_HD_U_G3
Hwyla-forge-1.10.11-B78_1.16.2
jei-1.16.2-7.1.3.20
NaturesCompass-1.16.2-1.8.5
sit-1.16.2-v1.3
u_team_core-1.16.3-3.1.9.181
useful_backpacks-1.16.3-1.11.5.82
worldedit-forge-mc1.16.3-7.2.0-beta-05
Xaeros_Minimap_20.23.0_Forge_1.16.3
XaerosWorldMap_1.11.0_Forge_1.16.3-tw

 - Forge Version: 34.1.0
 - OS Version:  Mac OS Catalina 10.15.7
 - Java Version: Java 8 update 261

**Comment by BloCamLimb** [comment]
what graphics card are you with

**Comment by sasdj2418** [comment]
> what graphics card are you with

AMD Radeon Pro 555X
MacBook pro 15" 2018 with touch bar

**Comment by BloCamLimb** [comment]
It's just an incorrect message, and there's actually nothing wrong with the mod. It's okay to ignore it and the message will be hidden in later versions

**Comment by sasdj2418** [comment]
> It's just an incorrect message, and there's actually nothing wrong with the mod. It's okay to ignore it and the message will be hidden in later versions

It's NOT just an incorrect message, Minecraft UI is still original, only the font functions properly.
I will try to use this mod on bootcamp (win10) to confirm whether it is a graphics card or system problem.

**Comment by BloCamLimb** [comment]
Currently, Modern UI doesn't change UI at all
