### ISSUE TITLE
[Bug] AllMusic安装现代化UI后字体显示出现问题

### ISSUE THREAD

**Issue by Harvey2433** [BloCamLimb/ModernUI#230]
**Describe the bug**
相较于未安装ModernUI时，allmusic hud字体变粗变模糊

**To Reproduce**
1.同时安装Modern UI和AllMusic Client Mod
2.搭建带有allmusic的服务器
3.进入服务器，播放歌曲，在歌曲hud上即可发现问题

**Expected behavior**
字体显示应和全局其他字体相同

**Screenshots**
![image](https://github.com/user-attachments/assets/3e0b86a2-34e9-4fad-bd6d-8daca0770cb2)

**Environment**
 - Mod Version:3.10.0.1
 - Game Version:1.18.2
 - Forge Version:40.2.21
 - Operating System:Windows 11
 - Graphics Card:RTX 3060
 - Other Mods:
 AllMusic Client 3.0.0

**Comment by BloCamLimb** [comment]
说来也是搞笑，原版RenderType的blend和ShaderInstance的blend不一致。原版先应用RenderType里的blend，然后再应用ShaderInstance的blend。而RenderType的blend由GlStateManager控制状态切换，ShaderInstance的由BlendMode实例控制状态切换，再用GlStateManager控制状态切换，这就导致了有时候Blend不生效。
不过这个问题可以单方面在ModernUI里解决，因为ModernUI用自定义Shader。

**Comment by BloCamLimb** [comment]
单独安装
* forge-1.18.2.AllMusic_Client-3.0.3
* ModernUI-Forge-1.18.2-3.10.1.1-universal

没遇到问题

**Comment by BloCamLimb** [comment]
Cannot reproduce.
