### ISSUE TITLE
[Bug] All the text is deleted

### ISSUE THREAD

**Issue by Flouffly** [BloCamLimb/ModernUI#231]
**Describe the bug**
The mod delete all of the text in game

**Screenshots**
![image](https://github.com/user-attachments/assets/b805e864-36c1-442c-8fff-e06fb792794e)

**Environment**
 - Mod Version: 3.10.1.2
 - Forge Version: 43.3.5
 - Operating System: windows 10 x64 bits
 - Graphics Card: AMD 8A-6500 APU with radeon Radeon HD Graphics
 - Other Mods:
![image](https://github.com/user-attachments/assets/eefcae5a-8949-4fff-8de4-0f4a08e9a00d)
![image](https://github.com/user-attachments/assets/453d1800-b4b5-4fe9-8c2b-421037f012d6)
![image](https://github.com/user-attachments/assets/74d53ddc-0ee1-41a4-82fa-4a2241d6269b)
![image](https://github.com/user-attachments/assets/adc8ad75-7add-4898-a59d-4b79a9165368)
![image](https://github.com/user-attachments/assets/b18b662c-995b-493d-a513-f7f2ee90c41f)
![image](https://github.com/user-attachments/assets/07a33da2-51ac-4250-9be6-5cca033b1c56)

**Comment by BloCamLimb** [comment]
This is AMD driver bug, all old AMD Radeon GPUs that are no longer supported by AMD and older than GCN 1 architecture will have this texture completeness validation bug. Your GPU is Radeon HD 8570D with TeraScale 3 architecture.

**Comment by BloCamLimb** [comment]
3.11 should add support for old AMD GPUs
