### ISSUE TITLE
[Bug] 与Tooltips Scroll 不兼容

### ISSUE THREAD

**Issue by boring-fishawa** [BloCamLimb/ModernUI#233]
**Describe the bug**
开启现代化工具提示后tooltips scroll无法使用

**To Reproduce**
如上所述

**Expected behavior**
尝试关闭精准定位后tooltips scroll依旧不能使用，只有完全关闭现代化工具提示后才能使用

**Environment**
 - Mod Version: 3.10.1.5 （fabric 1.20.4）
 - Forge Version:0.16.2
 - Operating System:win10
 - Other Mods:Tooltips Scroll

**Comment by boring-fishawa** [comment]
burh Fabric Vesion:0.16.2

**Comment by qznfbnj** [comment]
虽然但是，Expected behavior 指的是“你觉得应该这样“的行为（

**Comment by boring-fishawa** [comment]
那就是开了现代化工具提示后tooltips scroll的移动工具提示的功能（使用滚轮或键盘时）无法生效

**Comment by qznfbnj** [comment]
> 那就是开了现代化工具提示后tooltips scroll的移动工具提示的功能（使用滚轮或键盘时）无法生效

应该是【开启现代化工具提示时，Tooltips Scroll（使用滚轮或键盘时）移动工具提示的功能可以正常生效】

话说回来，我因为 Legendary Tooltips 不兼容的缘故，一直是关着现代化工具提示 + 用 Tooltip Texts Scroller 的，不过现在想想好像 ModernUI 没有这类模组那样的热键绑定？（不过确实会自动来回移动就是了）也可能是我没找到

**Comment by boring-fishawa** [comment]
那个上下滚动应该是精准定位那个功能的效果，但是完全不能设置就很麻烦

**Comment by boring-fishawa** [comment]
如果现代化ui能把那个滚动做成可以用滚轮控制上下就好了，那样就不用加其他mod组合又会出现莫名其妙的问题了

**Comment by BloCamLimb** [comment]
加了一个上下方向键控制上下的，滚轮会和鼠标手势冲撞
