### ISSUE TITLE
[Bug] 当安装"SeasonHUD"时改模组的第一个字无法变为自定义的字体

### ISSUE THREAD

**Issue by MCER2020** [BloCamLimb/ModernUI#235]
**Describe the bug**
同时安装“SeasonHUD”与"ModernUI"时，“SeasonHUD”显示的季节信息中的第一个字仍然是Minecraft原版的字体，并非在"ModernUI"中自定义的字体。
SeasonHUD Version: 1.10.1
ModernUI Version: 3.10.1.2

**To Reproduce**
1. 同时安装“SeasonHUD”与"ModernUI"
2. 打开“SeasonHUD”的显示季节信息
3. 在"ModernUI"中设置自定义字体
4. 发现第一个字是MInecraft原版字体

**Expected behavior**
字体显示正常，即成功应用到自定义字体功能

**Screenshots**
![hud](https://github.com/user-attachments/assets/77d74d39-6ca2-49be-a5d7-d6e22cea7de5)

**Environment**
 - Mod Version: 3.10.1.2
 - Forge Version: 43.4.0
 - Operating System: Windows 11
 - Graphics Card: RTX 4060 Laptop
 - Other Mods: SeasonHUD (https://github.com/IanMods/SeasonHUD)

**Comment by BloCamLimb** [comment]
It seems duplicated with #234

**Comment by MCER2020** [comment]
> It seems duplicated with #234

你好，我的游戏版本是1.19.2，modernui版本是3.10.1.2。在#234里看到您说修复了，是指在即将更新的下一个modernui的版本会修复吗？

**Comment by BloCamLimb** [comment]
Fixed in 3.11

**Comment by MCER2020** [comment]
> Fixed in 3.11

请问Forge1.19.2版本什么时候能更新至3.11呢？Modrinth当前的最新版本仍是3.10.1.2
