### ISSUE TITLE
[Bug] 物品加载不出来，ctrl+k就boom了

### ISSUE THREAD

**Issue by Yummy-cookie** [BloCamLimb/ModernUI#236]
[crash-2024-08-30_22.56.45-client.txt](https://github.com/user-attachments/files/16818867/crash-2024-08-30_22.56.45-client.txt)

**Comment by BloCamLimb** [comment]
如果是偶尔崩溃，这是一个线程安全问题

**Comment by Yummy-cookie** [comment]
偶尔崩溃，多次打开就boom了

**Comment by Yummy-cookie** [comment]
物品图标，数量不显示

**Comment by Yummy-cookie** [comment]
> 如果是偶尔崩溃，这是一个线程安全问题
偶尔崩溃，多次打开就boom了,
物品图标，数量不显示

**Comment by Yummy-cookie** [comment]
> 如果是偶尔崩溃，这是一个线程安全问题
偶尔崩溃，多次打开就boom了,物品图标，数量不显示

**Comment by Yummy-cookie** [comment]
> 如果是偶尔崩溃，这是一个线程安全问题

偶尔崩溃，多次打开就boom了,
物品图标，数量不显示

**Comment by Yummy-cookie** [comment]
> 如果是偶尔崩溃，这是一个线程安全问题

所以怎么搞

**Comment by BloCamLimb** [comment]
Fixed in https://github.com/BloCamLimb/ModernUI-MC/commit/6a4fd89e03589a0a2b65c4a7b826bb47f19e2634

**Comment by Yummy-cookie** [comment]
> Fixed in [BloCamLimb/ModernUI-MC@6a4fd89](https://github.com/BloCamLimb/ModernUI-MC/commit/6a4fd89e03589a0a2b65c4a7b826bb47f19e2634)

谢谢

**Comment by Yummy-cookie** [comment]
所以什么时候更新1.19.2

**Comment by BloCamLimb** [comment]
不好意思，由于新版改动过多，已经很难向后迁移到过旧的Minecraft版本，且1.20以上的玩家远远多于1.19和1.18。如果确实需要特供旧版更新，你可以考虑赞助本项目2000元以上。
