### ISSUE TITLE
[Bug] 只有边框，没有显示信息

### ISSUE THREAD

**Issue by MNWZ211** [BloCamLimb/ModernUI#237]
最近的几次游戏中出现了只有边框没有物品信息的情况，版本1.20.1，忘了截图了。但是删除“ModernUI”文件夹（没有修改过）后重新进入游戏就好了，有问题的文件夹：
[ModernUI.zip](https://github.com/user-attachments/files/16831666/ModernUI.zip)

**Comment by BloCamLimb** [comment]
不明白，你的配置文件就是默认的

**Comment by MNWZ211** [comment]
可能是其他模组导致的，mod很多，而且没法复现了，如果还出现我再反馈吧，打扰了
