### ISSUE TITLE
[Bug] All the Mods 9 to the sky 安装Modern UI之后崩溃

### ISSUE THREAD

**Issue by HL29Mysterious** [BloCamLimb/ModernUI#238]
Forge加载界面接近完成后崩溃

**Environment**
 - Mod Version:3.10.1.4
 - Forge Version:47.2.20
 - Operating System:Win11   23H2   22635.3420
 - Graphics Card: AMD RX590
 - Other Mods: All the Mods 9 to the sky整合包内的Mod

[hs_err_pid11880.log](https://github.com/user-attachments/files/16869442/hs_err_pid11880.log)
[debug.log](https://github.com/user-attachments/files/16869443/debug.log)
[latest.log](https://github.com/user-attachments/files/16869444/latest.log)

**Comment by BloCamLimb** [comment]
与 https://github.com/BloCamLimb/ModernUI/issues/213 重复，请更新显卡驱动

**Comment by BloCamLimb** [comment]
和hsdis无关，它是反汇编的。反正AMD的驱动就是比较玄学，你单独编译这些着色器没问题，但是放一起可能就不行，每次崩溃显示的有关模组也不一样。你这个就是显示龙研的前置brandonscore崩了，你不如到CodeChickenLib那边看看，有说修改Flywheel配置解决的
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404#issuecomment-1364625915
