### ISSUE TITLE
[Bug] Incompatibility with FancyMenu (RenderingUtils.resetGuiScale)

### ISSUE THREAD

**Issue by tajemniktv** [BloCamLimb/ModernUI#239]
**Description**
There most likely is some kind of ModernUI + FancyMenu incompatibility? Looking at the logs I think it would be more appropriate to post it on the FancyMenu tracker, tho it happened after adding ModernUI, hence I'm here...

**Full log**
https://hastebin.com/share/aracufifon.yaml

**To Reproduce**
Try to run FancyMenu along with ModernUI

**Environment**
 - Mod Version: 3.11.0.4
 - Fabric Loader Version: 0.16.5
 - Fabric API version: 0.104.0
 - Operating System: Win11Pro
 - Graphics Card: RX 5700 XT
 - Other Mods: Whole list on hastebin

**Comment by BloCamLimb** [comment]
Modern Text Engine is not compatible with FeyTweaks. This is not a new bug, we have clearly explained it on Modrinth. See also https://github.com/BloCamLimb/ModernUI/issues/156

**Comment by tajemniktv** [comment]
Shoot, apologies, I was so sure I didn't forgor to disable FeyTweaks before making that issue... It works fine with FancyMenu, my bad :d
