### ISSUE TITLE
Error Says that Java version 1.8.0_51 is not compattible.(Fixed)

### ISSUE THREAD

**Issue by OrangeSkyline** [BloCamLimb/ModernUI#24]
This problem was fixed. It is the mod because i just downloaded the mod before ever looking at the version. It was 1.16.4 instead of 1.16.3.

**Comment by OrangeSkyline** [comment]
I just want to know if its the Forge version itself or the mod version. If it is the Forge version please send the download link to the specific version of forge.

**Comment by OrangeSkyline** [comment]
Nevermind. It is the mod because i just downloaded the mod before ever looking at the version. It was 1.16.4 instead of 1.16.3.

**Comment by GhostU023** [comment]
How do i fix this issue??

**Comment by BloCamLimb** [comment]
let your game use newer java
