### ISSUE TITLE
[Bug] §k 随机字符在随机中文时可能出现 NO GLYPH，且不会随机到全角字符

### ISSUE THREAD

**Issue by LTCatt** [BloCamLimb/ModernUI#241]
**Describe the bug**
老版本：
![image](https://github.com/user-attachments/assets/5ec11a38-da88-443b-aca8-c0c506dd4ace)

新版本：
![image](https://github.com/user-attachments/assets/dfebe7b1-5f33-4f23-baea-966d457dfd5d)

**Expected behavior**
按照 [Wiki](https://zh.minecraft.wiki/w/%E6%A0%BC%E5%BC%8F%E5%8C%96%E4%BB%A3%E7%A0%81) 的描述，`使用§k循环出现的随机字符会与原有字符的宽度相同。`

所以 `§k中文` 应当出现随机的全角字符。

**Environment**
 - Mod Version: 3.11.0.1

**Comment by xingnengmao666** [comment]
龙猫走错片场了（？

**Comment by xingnengmao666** [comment]
推测可能是Modern UI的字体渲染问题,感觉可以Render抓帧（？

**Comment by BloCamLimb** [comment]
Improved in https://github.com/BloCamLimb/ModernUI-MC/commit/b6f0fb4ac5136b8dca2fd910e5c82c46c5a4d6b4
