### ISSUE TITLE
[Bug] 1.19.2 与最新版灾变稳定崩溃

### ISSUE THREAD

**Issue by QianFuv** [BloCamLimb/ModernUI#246]
- 模组列表：
  ![image](https://github.com/user-attachments/assets/ce02fe02-43df-4661-a63b-be0c33c46076)
- 崩溃报告：
  https://mclo.gs/BiYexZd

**Comment by BloCamLimb** [comment]
我们官方已经不会再有对Minecraft 1.19.2的支持，况且在Minecraft 1.20.1上没有问题。

ModernUI support for Minecraft 1.19.2 is end-of-life.
