### ISSUE TITLE
[Bug] mod not being skipped when loaded on server (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [BloCamLimb/ModernUI#247]
**Describe the bug**
title

**To Reproduce**
add the mod to server mods folder

**Expected behavior**
the server to skip it
**Screenshots**
https://mclo.gs/gmEFB1C

**Environment**
 - Mod Version: latest
 - Forge Version: neoforge .72
 - Operating System: arch linux
 - Graphics Card: 6750xt
 - Other Mods: too many

**Comment by BloCamLimb** [comment]
Since ModernUI is marked as client-only, it's not expected to be installed on server. Additionally, there are also several client-only mods installed.

**Comment by VaporeonScripts** [comment]
Yes but the mod needs to have the code part to skip it

**Comment by BloCamLimb** [comment]
Done https://github.com/BloCamLimb/ModernUI-MC/commit/d972cb153f8dca8e6351bdeccb5bdd2d74eabca2
