### ISSUE TITLE
Possible to add support for Mod "Untranslated Items"?

### ISSUE THREAD

**Issue by kleinermob** [BloCamLimb/ModernUI#249]
https://www.curseforge.com/minecraft/mc-mods/untranslated-items

It shows the English Items as the same Language you selected
![2024-11-04_20 26 39](https://github.com/user-attachments/assets/14242c27-ebf5-4ce6-b3c8-7f222c4c7a36)
The word "Apfel" is showing twice on the bottom , while the second word should be "Apple", this is not happening without ModernUI

**Comment by BloCamLimb** [comment]
In particular:
UntranslatedItems uses the same Component object to render text in different languages. It modifies the internal state of the Component object to return different characters each time it is visited, but its hashCode() remains unchanged. This is very hacky.

When you disable the text component cache, ModernUI will visit the Component every time to retrieve the real content inside, and then compute the hash code (uncached) to lookup text layout in cache. This will be slightly slower, but it will ensure that it can handle these hacky mods.
