### ISSUE TITLE
[Bug] space character doesn't render correctly with tab-completion.

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#25]
**Describe the bug**
when typing commands which has tab completion such as vanilla command, the chat message isn't rendered correctly.

**To Reproduce**
just type /title playerName

**Expected behavior**
there should be space between command and argument text.

**Screenshots**
![capture 1](https://user-images.githubusercontent.com/11700801/99150123-bc103380-26d5-11eb-9379-4b157563919a.png)

when just typed "/title"

![capture 2](https://user-images.githubusercontent.com/11700801/99150125-be728d80-26d5-11eb-92ab-6a935f83213e.png)

and pressed space bar to type argument "/title "

![capture 3](https://user-images.githubusercontent.com/11700801/99150129-c0d4e780-26d5-11eb-9aa8-78385a7ec49b.png)

after typed argument "/title jho5245"

![capture 4](https://user-images.githubusercontent.com/11700801/99150202-2d4fe680-26d6-11eb-9595-adfe396a5392.png)

this is when I put the cursor here "/title| @a" (| is cursor location)

![capture 5](https://user-images.githubusercontent.com/11700801/99150217-435da700-26d6-11eb-93b1-e53678b64b4a.png)

and this is "/title |@a"

tried with various fonts and the same result.

**Versions you are on**
 - Mod Version: ModernUI-1.16.4-2.2.1.65-universal
 - Forge Version: 1.16.4-Forge-35.0.17

**Comment by jho5245** [comment]
Another example with normal text (chat) and command text.
![capture 6](https://user-images.githubusercontent.com/11700801/99150308-e0b8db00-26d6-11eb-9f04-ff48e4e33f3b.png)

**Comment by BloCamLimb** [comment]
Fixed 8dd54d54d6f27b3e8cd1d2094a489992c9dc9909
