### ISSUE TITLE
[Bug] 1.19.2放入Cisco's Fantasy Medieval RPG整合包崩潰

### ISSUE THREAD

**Issue by Theoretical-Enday** [BloCamLimb/ModernUI#250]
Forge43.3.5
ModernUI-Forge-1.19.2-3.10.1.2
Cisco's Fantasy Medieval RPG [Ultimate] v6a
[crash-2024-11-05_04.45.18-client.txt](https://github.com/user-attachments/files/17623740/crash-2024-11-05_04.45.18-client.txt)
求告知是哪裡出了問題。

**Comment by BloCamLimb** [comment]
我也不清楚問題出在哪裡，也許是原版，也許是Forge。總之只要安裝某些模組就會造成資源載入失敗，而在1.20以上就沒有問題。此外1.19已經 END OF LIFE。

Duplicate with https://github.com/BloCamLimb/ModernUI/issues/246
