### ISSUE TITLE
[Bug] Unable to display any text in 1.19.2 在1.19.2版本无法显示任何文本

### ISSUE THREAD

**Issue by acutenoob** [BloCamLimb/ModernUI#255]
Unable to display any text in 1.19.2
在1.19.2版本不能显示任何文本
**To Reproduce**
1. install this mod 安装本模组
2. start games 启动游戏
**Expected behavior**
1.display texts 显示文本

**Screenshots**
![1732543026718](https://github.com/user-attachments/assets/41d60e7e-139f-42aa-88ab-0bf227dbf305)

**Environment**
 - Mod Version: 3.10.
 - Forge Version:43.4.4
 - Operating System: win10
 - Graphics Card: AMD Radeon 6600M and 6700M Series
 - Other Mods: none
**logs**
https://mclo.gs/DziQX1B

**Comment by BloCamLimb** [comment]
Duplicated with #231

In ModernUI 3.11.0, we worked around the driver bug on old Radeon GPUs, but the new version only supports Minecraft 1.20 and above, and no longer supports 1.19.

**Comment by acutenoob** [comment]
大大辛苦了 我的gpu确实太老了 我还是用我的旧版本吧........

**Comment by acutenoob** [comment]
大大辛苦了 我的gpu确实太老了 我还是用我的旧版本吧........
