### ISSUE TITLE
[Bug] 设置页面不显示

### ISSUE THREAD

**Issue by CreeperBoy-CB** [BloCamLimb/ModernUI#258]
**Describe the bug**
打开ModernUI设置后显示空白

**To Reproduce**
1. 打开模组菜单
2. 点击ModernUI
3. 打开设置

**Expected behavior**
正常情况下应该会显示设置页面

**Environment**
 - Mod Version:3.11.0.4
 - Fabric Version:16.0
 - Operating System:Windows 11 Build 26120.2415
 - Graphics Card:Intel（R） HD Graphics 520
 - Other Mods:Mod Menu、Sodium……

**Comment by BloCamLimb** [comment]
Duplicated #240
