### ISSUE TITLE
[Bug] Experience level can't be hidden by AutoHUD with ModernUI installed

### ISSUE THREAD

**Issue by murphy-slaw** [BloCamLimb/ModernUI#259]
**Describe the bug**
When ModernUI is installed with AutoHUD, AutoHUD is unable to hide the experience level when configured to do so.

**To Reproduce**

1. Install ModernUI and AutoHUD
2. Load a save where the player has at least one experience level.
3. In its default configuration, AutoHUD should hide the entire HUD including the experience level, but the experience level remains on screen.

**Expected behavior**
Expected experience level to be hidden except on level change or when the HUD is force-displayed.

**Screenshots**
![2024-12-05_15 29 36](https://github.com/user-attachments/assets/72890807-2014-462a-922e-e702fc6bea91)

**Environment**
 - Mod Version: 3.11.01
 - Fabric Version: 0.16.9
 - Operating System: MacOS Sonoma 14.6.1
 - Graphics Card: Apple M1 Max
 - Other Mods:
autohud-8.0+1.20.1-fabric.jar
YetAnotherConfigLib-3.6.2+1.20.1-fabric.jar
fabric-api-0.92.2+1.20.1.jar
ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric.jar
modmenu-7.2.2.jar

**Comment by BloCamLimb** [comment]
Released 3.11.1

**Comment by murphy-slaw** [comment]
Thanks for the quick fix!
