### ISSUE TITLE
[Bug] When creating a world with this mod, Quark, and JEI installed, a world will freeze and won't load in 

### ISSUE THREAD

**Issue by BugmanBugman** [BloCamLimb/ModernUI#26]
**Describe the bug**
When creating a world with this mod, Quark, and JEI installed, a world will freeze and won't load in 

**To Reproduce**
1. Load up MC with quark and its library mod, JEI, and this mod
2. Create a world
3. Notice how it freezes after "joining world"

**Expected behavior**
For it to load in

**Screenshots**

**Versions you are on**
 - Mod Version: 2.2.1.65-universal
 - Forge Version: 1.16.4 - 35.0.18

**Comment by BloCamLimb** [comment]
Fixed 8dd54d54d6f27b3e8cd1d2094a489992c9dc9909
