### ISSUE TITLE
[Bug] Forge 1.20.1 crash on start

### ISSUE THREAD

**Issue by KalinZhang** [BloCamLimb/ModernUI#261]
**Describe the bug**
Crash on start with 
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
...
at net.minecraft.client.gui.font.FontManager.m_95006_(FontManager.java:292) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?] 

**To Reproduce**
Crash on start

**Expected behavior**

**Screenshots**
[crash report.](https://pastebin.com/UFzE0VK3)

**Environment**
 - Mod Version: 3.11.01
 - Forge Version:
 - Operating System: Windows 11
 - Graphics Card: 
 - Other Mods:

**Comment by BloCamLimb** [comment]
Please paste your **entire** crash-report/debug.log.

**Comment by KalinZhang** [comment]
Sure. I did not find any *.log under crash-report directory, this is the one under logs
[2024-12-12-4.log](https://github.com/user-attachments/files/18119535/2024-12-12-4.log)

**Comment by BloCamLimb** [comment]
Duplicate #251
Well, Modern Text Engine is not, and will not be compatible with the `Inline` mod, try to disable Inline or Modern Text Engine.
