### ISSUE TITLE
[BUG / INCOMPATIBILITY] TslatEntityStatus text rendering is completely messed up

### ISSUE THREAD

**Issue by remidu64** [BloCamLimb/ModernUI#265]
**Describe the bug**
The text rendering added by TslatEntityStatus are completely messed up and unreadable

**To Reproduce**
1. Install ModernUI
2. Install TslatEntityStatus
3. Boot up Minecraft
4. Go in a world
5. Look at an entity and look at the top left corner for the TslatEntityStatus UI
6. Notice the garbled text

**Expected behavior**
Readable text like this:
![image](https://github.com/user-attachments/assets/b3b9cb51-61e8-4925-93bd-8b2f6f098762)
![image](https://github.com/user-attachments/assets/2d967b55-73f1-4596-9cb3-d2942d598c04)

**Screenshots**
(Supposed to say "INSTAKILL!" here)
![image](https://github.com/user-attachments/assets/c04bb6cf-18a1-4d38-8429-36425d6b4306)

(Supposed to say "Slime" here)
![image](https://github.com/user-attachments/assets/5b020091-0fe7-45f6-b8d7-bcda2d9d1ded)

**Environment**
 - Mod Version: ModernUI 3.11.1.5 / TslatEntityStatus V1.7
 - Fabric Version: Latest
 - Operating System: Windows 10
 - Graphics Card: NVIDIA RTX 4060
 - Other Mods: No other mods that contribute to this issue (i checked every single one of them)

[Corresponding github issue at TslatEntityStatus's github repo](https://github.com/Tslat/TslatEntityStatus/issues/34)

**Comment by BloCamLimb** [comment]
Cannot reproduce, whether in practice or in theory. A typical possible cause of this is ImmediatelyFast and Emojiful. Please list all the mods and paste the full game log.

**Comment by remidu64** [comment]
After a lot of tests, it seems like it's a server resourcepack messing up text rendering

The resourcepack doesn't change any textures so it's a little bit weird that it does that
