### ISSUE TITLE
[1.20.1] Mixin Conflict with Polytone causes startup crash

### ISSUE THREAD

**Issue by seancrain** [BloCamLimb/ModernUI#266]
**Describe the bug**
Upon loading the latest release of Modern UI (3.11.1.1) with Polytone, the game will have a mixin conflict and crash. Downgrading to the previous version, 3.11.0.1, fixes the problem.

**To Reproduce**
1. Install Modern UI's latest release alongside Polytone in a Forge 1.20.1 environment.
2. Start the game, and before the title screen appears, the window will crash due to a mixin loading failure.

Here's the log: [https://pastebin.com/raw/GBQRmBfs](https://pastebin.com/raw/GBQRmBfs)

**Expected behavior**
The game should load normally.

**Screenshots**
N/A

**Environment**
 - Mod Version: 3.11.1.1
 - Forge Version: 47.3.12
 - Operating System: Windows 11
 - Graphics Card: GeForce RTX 2060 Mobile
 - Other Mods: Polytone 2.4.3

**Comment by BloCamLimb** [comment]
Yes. The previous version was not compatible with AutoHUD #259, but now it is not compatible with Polytene. In theory, at least in 1.20.1, it is almost impossible to make both compatible. Maybe changing the Mixin loading order can also solve this, but this is not something we can do here. We recommend that you report this to Polytone, as their MIXIN does not allow "soft fail".

**Comment by MehVahdJukaar** [comment]
Uhm I've looked at your code and I didn't find any mixins or mod related code for theatter, on master branch at least. I don't understand how my mixin could ever fail there, as far as I know modifyarg is safe to use, unless of course somebody is using unsafe stuff live overwrite. Also I can't make it soft fail as having mixins that soft fail is bad practice

**Comment by BloCamLimb** [comment]
The code is here
https://github.com/BloCamLimb/ModernUI-MC/blob/dbdab1595d34dd4cc29f2b57bdfc8997d4d137de/common/src/main/java/icyllis/modernui/mc/text/mixin/MixinIngameGui.java#L36-L63

I don't quite remember the way to resolve the conflict between Redirect and ModifyArg. I think the new version of Fabric Mixin seems to be able to handle.

> Uhm I've looked at your code and I didn't find any mixins or mod related code for the matter, on master branch at least. I don't understand how my mixin could ever fail there, as far as I know modifyarg is safe to use, unless of course somebody is using unsafe stuff live overwrite. Also I can't make it soft fail as having mixins that soft fail is bad practice

**Comment by MehVahdJukaar** [comment]
yeah so Redirects and Overwrite should never be used. They are the only mixin types that are always unsafe to use and will cause issues

**Comment by MehVahdJukaar** [comment]
and there are way better mixin types so one should never need either of those 2

**Comment by BloCamLimb** [comment]
One of our goal is to be compatible with Forge, and NeoForge and Fabric above 1.20.1 have used newer Mixin, which has already solved the mixin order issue, so I am not very interested in fixing this. A simple workaround is to add `"mixinPriority": 2` to `polytone-common.mixins.json`.

**Comment by MehVahdJukaar** [comment]
It's not about ordering. It's about using mixin type. Redirect mixin type and overwrite are by nature incompatible and unsafe and their usage is very discouraged. Instead inject, modify expression value and wrap operation and other should be used

**Comment by seancrain** [comment]
After reading over this, I'm guessing that I'll just need to hold back the Modern UI version for now. 1.21.x is not an option in terms of mod availability for me yet, sadly.

**Comment by BloCamLimb** [comment]
This issue is completed because there's nothing to fix. You can follow my workaround, or wait for an hotfix version.

**Comment by BloCamLimb** [comment]
The compatibility is improved in 3.11.1.6 and 3.11.1.7
