### ISSUE TITLE
[Bug] unsafe mixin usage,causing crash

### ISSUE THREAD

**Issue by VaporeonScripts** [BloCamLimb/ModernUI#267]
**Describe the bug**
Crash on boot

**To Reproduce**
Use the mod ig

**Expected behavior**
Normal launch

**Screenshots**
https://mclo.gs/9LRZGPE

**Environment**
 - Mod Version: latest
 - Forge Version: latest
 - Operating System: CachyOS (arch)
 - Graphics Card: 6750xt
 - Other Mods: check mclogs

**Comment by BloCamLimb** [comment]
Duplicate #266
