### ISSUE TITLE
[Bug] 与EasyAnvils冲突

### ISSUE THREAD

**Issue by adsioho** [BloCamLimb/ModernUI#268]
启动时报错

[minecraft-exported-logs-2024-12-21T14-21-39.log](https://github.com/user-attachments/files/18217470/minecraft-exported-logs-2024-12-21T14-21-39.log)
MC 1.21.1 Fabric0.16.9 Java21.0.3 Ram 12GB

**Comment by BloCamLimb** [comment]
Duplicate #156
