### ISSUE TITLE
[Bug] Game crashes at sometimes with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#27]
**Describe the bug**
When sometimes opening inventory or gui, the game crashes.

**To Reproduce**
I typed a command which opens inventory gui, and the game stops, then crashes.

**Expected behavior**
A normal behavior of inventory open.

**Screenshots**
![capture](https://user-images.githubusercontent.com/11700801/99254832-56978080-2856-11eb-95d5-e7d1d5cd35ec.png)
And here's crash log
[crash-2020-11-16_21.50.38-client.txt](https://github.com/BloCamLimb/ModernUI/files/5546316/crash-2020-11-16_21.50.38-client.txt)

**Versions you are on**
 - Mod Version: ModernUI-1.16.4-2.2.2.66-universal
 - Forge Version: 1.16.4-forge-35.0.17

**Comment by jho5245** [comment]
I'm testing in many cases and the crash point is from the inventory's title contains number.
the title is 'aa1aa' and game crashes with this crash log.
[crash-2020-11-16_23.06.23-client.txt](https://github.com/BloCamLimb/ModernUI/files/5546744/crash-2020-11-16_23.06.23-client.txt)

**Comment by jho5245** [comment]
when the title is 'aaaa', the game not crash but with 'aaaa1' it crashes.

**Comment by jho5245** [comment]
I typed /say §클§릭§캔§슬§큐§컴§버§리§G§U§I§커§스§텀§레§시§피§ §카§테§고§리§ §메§뉴§큐§컴§버§리§G§U§Iaaaa1§p§a§g§e§:§1§c§a§t§e§g§o§r§y§:§z§z§z§t§e§s§t§m§a§i§n§p§a§g§e§:§1

and the game crashes.

**Comment by jho5245** [comment]
My expected conclusion is... after invalid color code (like §j §p, etc.) + number text makes the game crash.

**Comment by jho5245** [comment]
I think invalid color code makes invalid array calculation.

I typed for example commands using color code and invalid color codes.
/say §a an example text

/say §a an exa§6mple text

/say §j§a an example text

/say §j§a an exa§6mple text

And here's screen shot.
![capture](https://user-images.githubusercontent.com/11700801/99267559-6ff4f880-2867-11eb-980e-a47030a1fac6.png)

as you can see, color formatting with invalid color code text is strangely formatted.

**Comment by BloCamLimb** [comment]
Fixed, there will be a release build later, thanks for your report
