### ISSUE TITLE
[Bug] ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jho5245** [BloCamLimb/ModernUI#28]
**Describe the bug**
The game crashes sometimes with certain circumstances (currently known : click multiplayer button, playing in multiplayer server for a while)

**To Reproduce**
Play minecraft with forge version 1.16.4-forge-35.1.0

**Expected behavior**
normal behavior of playing minecraft

**Screenshots**
[crash-2020-11-21_12.40.13-client.txt](https://github.com/BloCamLimb/ModernUI/files/5576957/crash-2020-11-21_12.40.13-client.txt)

**Versions you are on**
 - Mod Version: ModernUI-1.16.4-2.2.3.67-universal
 - Forge Version: 1.16.4-forge-35.1.0

**Comment by jho5245** [comment]
tested with forge 1.16.4-forge-35.0.18 and the same crash happens.
[crash-2020-11-21_12.59.27-client.txt](https://github.com/BloCamLimb/ModernUI/files/5576971/crash-2020-11-21_12.59.27-client.txt)

**Comment by BloCamLimb** [comment]
Fixed
