### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by T0shh** [BloCamLimb/ModernUI#29]
**Describe the bug**
The mod file is in my mods folder, but doesn't show up in Mod Menu's list and none of its functionality is added

**To Reproduce**
1. Place the file in mods folder with Mod Menu
2. Launch Fabric 10.8 from minecraft launcher
3. Click the 'Mods' button

**Expected behavior**
Expected it to show up in the mods list and for functionality to be added.

 - Mod Version: 2.2.4.68
 - Forge Version: Fabric loader 10.8 1.16.4

**Comment by BloCamLimb** [comment]
Obviously, this is a **Forge** Mod, and definitely can't be loaded by Fabric Loader
