### ISSUE TITLE
[Bug] "java 1.8.0_251 or above is required"

### ISSUE THREAD

**Issue by Dividedby0KSJ** [BloCamLimb/ModernUI#31]
**Describe the bug**
I have downloaded this mod and have even downloaded the java sdk 1.8.0_271 but to no avail. my java is up to date

**To Reproduce**
Steps to reproduce the behaviour:
1. download mod
2. lunch Minecraft
3. get error
4. cry T_T

**Expected behaviour**
... to work open...

**Screenshots**
[https://imgur.com/a/ZCpNswS](url)

**Environment**
 - Mod Version: ModernUI-1.16.4-2.2.4.68
 - Forge Version: 1.16.4 35.1.0
 - Operating System: Windows 10 Version 10.0.19042 Build 19042
 - Graphics Card: NVIDIA GeForce RTX 2060 SUPER

**Comment by BloCamLimb** [comment]
Have you read the FAQ carefully? You have to let your game launcher use the java you updated rathen than the built-in one. If it's the official launcher, change the Java Executable.
