### ISSUE TITLE
[Bug] Minecraft unexpectedly crashes while in Mojang 'loading screen'.

### ISSUE THREAD

**Issue by doctor-something5000** [BloCamLimb/ModernUI#32]
**Describe the bug**
Minecraft with _Modern UI_ installed, unexpectedly crashes upon reaching the Mojang **'Loading screen'**
**To Reproduce**
1. Have Modern UI.
2. Start Minecraft
3.  See error.

**Expected behavior**
The game was supposed to run flawlessly

**Screenshots**
Unavailable.

**Environment**
 - Mod Version: ModernUI-1.16.4-2.3.0.69
 - Forge Version: 1.16.4 - 35.1.13
 - Operating System: Windows 7 x64
 - Graphics Card: Mobile Intel(R) 4 Series Express Chipset Family
Logs:
[]https://gist.github.com/doctor-something5000/6b074d3dddc78506bfe06521303b6a42
_You will find at the end of the log, an error with Modern UI._

**Comment by BloCamLimb** [comment]
If you use a laptop, you should select the dedicated graphics for java applications.

**Comment by doctor-something5000** [comment]
Yes I do use a laptop and I have only one type of graphics that is mentioned above.

**Comment by BloCamLimb** [comment]
Your graphics card doesn't meet the minimum requirements of Modern UI, and most PC games.

**Comment by BugmanBugman** [comment]
https://hatebin.com/acoehnbbqa
This is happening for me too

**Comment by BloCamLimb** [comment]
> https://hatebin.com/acoehnbbqa
> This is happening for me too

`Create` mod failed to load, so game crashed
