### ISSUE TITLE
Can't Sleep to Skip the Night Away

### ISSUE THREAD

**Issue by Coraline77447** [BloCamLimb/ModernUI#34]
When you try to sleep the night away and you just stay in bed till the morning without accelerating the night. 

To reproduce this is to simply install Modern UI, latest version, create a new world or load into an existing one, make sure you're operator and type in chat; 
/time set night  or
/time set midnight 

Then grab any colored bed and right click it to sleep in it and wait for as long as you would normally wait for you to wake up in the morning.

What you should expect is that you would stay in your bed till 6 A.M and you didn't actually skip the night and if you have a mod like Survive mod then you'll still be tired with the tiredness effect still going. Also if this bug doesn't get fixed then Survive's sleep features will eventually kill the player cause Survive mod will slowly shut the player's body down due to lack of sleep till the player dies from lack of sleep.

1.16.4
2.3.0.69
35.1.28 (started happening on 35.1.13)
64-bit
Intel Graphics HD 620

Sorry, I didn't take any screenshots of the issue while it was happening cause I truly didn't know which one of my mods was causing this issue till I had to track down which one of my mods was causing this issue and this is one of the most strangest issues cause all that Modern UI is is a UI mod that shouldn't be messing with the sleeping mechanics of Minecraft since it just shows us a UI and nothing else. But fix this issue... please...

Also one more thing, since I have the official minecraft launcher now and when I tried to load my modded game up with Modern UI, the game was telling me that the official launcher is using the wrong java version (java 1.8.0_51) while you're mod requires (java 1.8.0_251), I have that java version and the mod seemed to be working fine when I use my cracked client launcher (Tlauncher) but when I tried with my official launcher (minecraft's official launcher) it isn't working, is the wrong java version problem on my end or your end cause I'm somewhat confused about it right now and I need your help to clarify if that issue is on my end or your end. Ok... P.S. Sorry in advance for this really long report and basically sending you two reports in one report😔

**Comment by BloCamLimb** [comment]
It is confirmed that it is not bug.

**Comment by Coraline77447** [comment]
For which one? The sleep issue I have with this mod or the wrong java version which probably is on my end for that problem but what about the bed issue I have with Modern UI?

**Comment by BloCamLimb** [comment]
When you use the official launcher, you need to make sure that you choose the external Java to run. This mod won't lead to the sleep issue.

**Comment by Coraline77447** [comment]
Wait a sec, before someone who was kind enough to buy me Minecraft for my main Microsoft account I use Tlauncher which is a cracked client and Modern UI worked just fine before that but after I've gotten the official launcher and tried to run one of the installations of forge on the official launcher is when I started seeing my sleep problem for when I use Tlauncher

**Comment by BloCamLimb** [comment]
Do you have other mods installed?

**Comment by Coraline77447** [comment]
Yes, one in particular is Survive mod that has a sleep function but right now it has a bug in its tired overlay that the screen would get way too blurry to the point that its unplayable

**Comment by BloCamLimb** [comment]
The sleep timer and its functionality are processed on the logical server side, Modern UI won't affect it at all.

**Comment by Coraline77447** [comment]
Ok, btw in the latest version that I downloaded and added to my last modded world before it was deleted that I couldn't see the text that was changed. 

I couldn't tell if the mod was installed cause I couldn't see any of the key bindings for modern UI in the controls screen but I'm keeping Modern UI uninstalled anyways cause I must have somehow messed up the mod without even realizing it.

I may have permanently damaged something with the mod or something since both you and I really don't know what's really going on with my modded game...
I may try to use Modern UI again with my new modded survival world that I've made. 

One more thing, when I updated Modern UI and joined the world I had I was able to go to sleep but I just couldn't see the font style changed from default or what resource pack I'm currently using to what Modern UI has so I uninstalled it, especially when I  had Scaling Health mod installed which Modern UI isn't supported with Scaling Health mod...

**Comment by BloCamLimb** [comment]
the config?

**Comment by BloCamLimb** [comment]
Do you have `performant` mod installed?

**Comment by Coraline77447** [comment]
I had performant installed but it was messing with the wondering traders whenever Apotheosis is installed so I uninstalled performant, also I wont add Modern UI cause of some I compatibility with survive mod's UI of the energy and thirst bars above the hunger bar.

**Comment by BloCamLimb** [comment]
I'll check the compatibility problem with Survive mod, but I have to say that `performant` is breaking too many things, do not use it.

**Comment by BloCamLimb** [comment]
I didn't see anything wrong with Survive mod, I'll build and upload the latest version of my mod, then you try that version

**Comment by Coraline77447** [comment]
Alright, cant wait for the next update! Btw please don't recommend the mod for forge 35.1.36 (latest) cause I'm experiencing ticking world crashs with the latest version of forge right now. Ok

**Comment by BloCamLimb** [comment]
performant 3.30m fixed that

**Comment by Coraline77447** [comment]
Alright, btw sorry for the no response for literally over a week... Been playin modded minecraft before I ran into some issues with different mods and worlds dying from the famous ticking world crash and a Backpack mod that I was experiencing technical difficulties with its inventory keybinding stuff which in its latest version somehow fixes that problem... Btw I feel like if we're gonna be talkin with one another then could we talk somewhere else than in my closed report comments section? If you want to that is, ok?

**Comment by BloCamLimb** [comment]
I would welcome you to my [discord server](https://discord.gg/kmyGKt2) to have a discussion

**Comment by Coraline77447** [comment]
Alright, I'll humbly join your discord server since I'm already a community member of Project MMO's discord and Infamous's discord server (Infamous owns Dungeons Mobs and Dungeons Gear mods and a few others btw) 

Even tho I feel like leaving Project MMO's discord server cause I feel like I've broken one too many rules like the one to never ping anyone unless it's an emergency or something really important.. 

Gotten 3 warnings on there already so if I were to get any more warnings then I could get banned from there so I'm just gonna keep my big mouth shut on Project MMO's discord server... 

Finally learned my lesson to never ping anyone on discord unless it's an emergency or something important... 

Also I dont really want to get pinned as well unless it's an emergency or something really important....
