### ISSUE TITLE
[Bug] Server crush

### ISSUE THREAD

**Issue by Nazguliki** [BloCamLimb/ModernUI#35]
**Describe the bug**
Cant run forge server with ModernUI-1.16.4-2.3.0.69-universal
but it does run with ModernUI-1.16.4-2.2.4.68-universal.

Funny thing is, that the singleplayer runs fine.

**To Reproduce**
Start forge server with ModernUI-1.16.4-2.3.0.69-universal

**Expected behavior**
Dont mean any sarcasm, but... the server running.

**Environment**
 - Mod Version: `2.3.0.69`
 - Forge Version: `35.1.28`
 - Operating System: windows 10 (64)
 - Graphics Card: gtx 1070 g1

**Server logs**
[debug.log](https://github.com/BloCamLimb/ModernUI/files/5755449/debug.log)
[latest.log](https://github.com/BloCamLimb/ModernUI/files/5755450/latest.log)
[crash-2020-12-30_21.04.23-fml.txt](https://github.com/BloCamLimb/ModernUI/files/5755452/crash-2020-12-30_21.04.23-fml.txt)

**Comment by BloCamLimb** [comment]
Fixed
