### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by EnterFor** [BloCamLimb/ModernUI#36]
**Describe the bug**
Start client crash.I don't know if this mod is responsible for it.
report：https://paste.ubuntu.com/p/SdWDP3YcT3/
**To Reproduce**
1. Start the game
2. Check for errors

**Screenshots**
none

**Environment**
 - Mod Version:ModernUI-1.16.4-2.3.1.70-universal
 - Forge Version:35.1.28
 - Operating System:win10
 - Graphics Card:GTX1650

**Comment by BloCamLimb** [comment]
It's due to parallel mod loading, `tetra` mod failed to load, causing Modern UI not initialized properly, you can see the exception of tetra in `debug.log` to find the actual reason.

**Comment by EnterFor** [comment]
Thank you, I don't know much about code issues, do I need to report this to the tetra authors?

**Comment by BloCamLimb** [comment]
The crash-report didn't show anything related to tetra, I think you need to report it to its author with a full `debug.log`.
