### ISSUE TITLE
[Bug] ModernUI seems to break features of other mods when Performant is installed

### ISSUE THREAD

**Issue by BugmanBugman** [BloCamLimb/ModernUI#38]
**Describe the bug**
Title. ModernUI seems to break features of other mods when Performant is installed, such as Dynamic Surroundings and Better Hurt Timer. I reported it to them here https://github.com/someaddons/performant_issues/issues/71 and https://github.com/someaddons/performant_issues/issues/80

**To Reproduce**
1. Start up minecraft with performant, dynamic surroundings, better hurt timer, and modern UI
2. notice how the item sounds added by dynamic surroundings dont work
3. also notice how you can't attack enemies, betterhurttimer's system is broken

**Expected behavior**
For BHT and dynamic surroundings to work alongside performant

**Environment**
 - Mod Version: 2.3.2.71
 - Forge Version:  35.1.36
 - Operating System: windows 10
 - Graphics Card: gtx 1050

**Comment by BloCamLimb** [comment]
I found some issues as well, https://github.com/BloCamLimb/ModernUI/issues/34#issuecomment-756096378, and it also breaks Mekanism pipes. But as `performant` is a closed source mod, and it changes some code of Forge using Mixin, I can not help it. I checked the list of its mixin classes, I found nothing conflicts found with Modern UI, so please transfer this issue to its author.

**Comment by BloCamLimb** [comment]
Fixed, update Performant and Modern UI https://www.curseforge.com/minecraft/mc-mods/performant/files/3163347, https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3163070
