### ISSUE TITLE
[Bug] Issue with Performant

### ISSUE THREAD

**Issue by simplebunsen** [BloCamLimb/ModernUI#39]
Quick thing, apparently your mod doesn't play nice with the mod Performant.
I've made an issue on their github here: https://github.com/someaddons/performant_issues/issues/85
Apparantly your mod considers Performant to produce fatal errors.

**Comment by BloCamLimb** [comment]
If you encounter a specific problem, you can open an issue here. If you don't find it, ignore it

**Comment by simplebunsen** [comment]
Can you please add something for disabling that message then? It pops up
every time I start the modpack and while I don't mind it, players would
come asking about in en masse

**Comment by BloCamLimb** [comment]
/config/forge-client.toml -> showLoadWarnings = false

**Comment by BloCamLimb** [comment]
I have already removed it, update the mod later

**Comment by BloCamLimb** [comment]
Wise people know that they should not use this performant. No matther they are in Fabric or Forge community.

**Comment by BloCamLimb** [comment]
Update Performant and Modern UI https://www.curseforge.com/minecraft/mc-mods/performant/files/3163347, https://www.curseforge.com/minecraft/mc-mods/modern-ui/files/3163070
