### ISSUE TITLE
Minecolonies tooltips bugged with ModernUI

### ISSUE THREAD

**Issue by Kriiks** [BloCamLimb/ModernUI#41]
All Minecolonies menu tooltips are empty and tooltip text is displayed on way off lower right corner.

Using MC 1.16.4
Minecolonies 0.13.564
Modern-UI 1.16.4-2.3.4.73

https://i.imgur.com/ch7LIte.png

**Comment by BloCamLimb** [comment]
It seems that MineColonies changes the matrix for larger tooltips, so it passes a transformed mouse position. However, I managed to find a solution to the problem.

**Comment by BloCamLimb** [comment]
be49eeac88cdf24e090777af43fa04becf7c03b7
