### ISSUE TITLE
[1.16.4] 渲染错误

### ISSUE THREAD

**Issue by EnterFor** [BloCamLimb/ModernUI#42]
**Describe the bug**
与电动力学下的核科学一起安装时，方块渲染错误
详情看：https://github.com/aurilisdev/Nuclear-Science/issues/2

**To Reproduce**
1. 下载Electrodynamics、Nuclear-Science、和本Mod的最新版本
2. 进入游戏
3. 放置反应堆涡轮机
4. 查看错误

**Expected behavior**
我希望进入游戏贴图正常

**Screenshots**
![image](https://user-images.githubusercontent.com/10114685/104124175-37453d00-5347-11eb-8642-367a0da8aaf5.png)

**Environment**
 - Mod Version:2.3.4.73
 - Forge Version:35.1.28
 - Operating System:Win10
 - Graphics Card:GTX1060

**Comment by BloCamLimb** [comment]
It caused by Performant mod, updating it would definitely fix this problem. https://www.curseforge.com/minecraft/mc-mods/performant/files/3163347

**Comment by BloCamLimb** [comment]
难道Performant又加了什么钩子吗

**Comment by EnterFor** [comment]
大意了，我没发现Performant更新了，抱歉。

**Comment by BloCamLimb** [comment]
我看你的好像是最新的..

**Comment by EnterFor** [comment]
啊这..

**Comment by BloCamLimb** [comment]
这我就不知道了 反正我测不出来 而且Modern UI是不会影响TESR的 还有我建议你删了Performant这个傻逼玩意

**Comment by BloCamLimb** [comment]
![image](https://user-images.githubusercontent.com/14106648/104125124-b199af80-538f-11eb-9ddf-e8091de1bc3f.png)
装OptiFine

**Comment by EnterFor** [comment]
我想着跟朋友们开个服玩，那玩意好像能优化服务器性能来着，那先这样吧，非常感谢你！ღ( ´･ᴗ･` )比心
OptiFine我以为它的问题更多呢，我会尝试安装一个

**Comment by BloCamLimb** [comment]
我不装OptiFine 只装 Modern UI 和 Performant 也测不出问题

**Comment by EnterFor** [comment]
啊这..那可能跟别的Mod起连锁反应了?..

**Comment by EnterFor** [comment]
当我OptiFine、Modern UI、Performant，一起安装时，渲染错误消失了。
