### ISSUE TITLE
[Suggestion] Menu Depth of Field toggle

### ISSUE THREAD

**Issue by MrSkittlesROTR** [BloCamLimb/ModernUI#45]
Would it be possible to disable depth of field in menus where you can still take action in the world. when using this UI?
Im Running this along side Mine colonies everything works as intended and it all looks good, however when using mine colonies build tool to place down a structure it blurs the background behind the menu making it difficult to see what your doing.
SS attached to show the issue. https://ibb.co/Jn0WgcH
Can still take action in the background moving the blueprint arround using those menu objects however due to the depth of field from the UI got to constantly leave and re-enter the menu to see what your doing.

**Comment by BloCamLimb** [comment]
There're configs located in ./config/ModernUI/ folder, you can edit it as followings:
1. Enable `developerMode` of Modern UI in `common.toml`
2. Open the GUI you don't want to use depth of field
3. Press `Ctrl+P`, and there will be a line start with `[2] Open Gui:` in your `./logs/debug.log`
4. Copy the class name to blurBlacklist in `client.toml`

**Comment by MrSkittlesROTR** [comment]
Setting it to false worked perfectly, thank you.
