### ISSUE TITLE
[Bug] Layout change with Fancy Menu

### ISSUE THREAD

**Issue by Matthysse** [BloCamLimb/ModernUI#48]
Hello!
I love the mod, but it changes completely the layout created using the Fancy Menus mod (changes the position of the buttons)
Here is an example:
![Capture d’écran 2021-01-26 164532](https://user-images.githubusercontent.com/32510957/105872329-94551a00-5ffa-11eb-9e9e-6f43459548f7.png)
![Capture d’écran 2021-01-26 165207](https://user-images.githubusercontent.com/32510957/105872343-97500a80-5ffa-11eb-860f-0c0df55cdc12.png)

**Comment by BloCamLimb** [comment]
Change the Gui Scale in game settings
