### ISSUE TITLE
[Bug] 3D blocks rendering through other blocks

### ISSUE THREAD

**Issue by Matthysse** [BloCamLimb/ModernUI#49]
Hello!
Here are some rendering bugs I encountered:
![2021-01-26_17 08 23](https://user-images.githubusercontent.com/32510957/105872973-47257800-5ffb-11eb-9e78-76cf0828b014.png)
![2021-01-26_17 09 15](https://user-images.githubusercontent.com/32510957/105872975-4856a500-5ffb-11eb-9f2c-275834fab42c.png)
It doesn't happen without your mod.
It's on Minecraft 1.16.5 with a GTX 1050Ti, optifine G7 pre4 and the seus renewed shaders.

**Comment by BloCamLimb** [comment]
Turn off Fast Render, didn't you see anything on curseforge?
