### ISSUE TITLE
[Bug] Modern UI causing loading error

### ISSUE THREAD

**Issue by ElvenMythic** [BloCamLimb/ModernUI#5]
**Bug description**
Whenever I load up Modern UI with _only_ Modern UI installed, I get an error telling me I do not have the right version of Java installed, even though I have the latest version and even specifically redownloaded Java after I got the bug for the first time. I also have OpenGL 4.5.

**To Reproduce**
1. Load up Minecraft with only Moder UI

**Expected behavior**
I expected Modern UI to load without any errors and function.

**Screenshots**
![Screenshot (16)](https://user-images.githubusercontent.com/52633053/80019560-b76bff80-84a5-11ea-828c-fa2a8955803e.png)

**Versions**
 - Mod Version: 1.4.7.41
 - OpenGL Version: 4.5
 - Java Version: Java 8 u251
 - Forge Version: 31.1.46

**Comment by BloCamLimb** [comment]
I'm sure you didn't specify your Java directory

**Comment by ElvenMythic** [comment]
> 
> 
> I'm sure you didn't specify your Java directory

Oops, looks like I didn't, apologies. I'm not particularly sure how to accomplish it but I'll do some research
