### ISSUE TITLE
Item, Bed & NPC Visual Clipping

### ISSUE THREAD

**Issue by Strix21** [BloCamLimb/ModernUI#50]
I can see the Bed that i place (Vanila Bed), Item trough Npc Hand, And Npc Texture Flipped from Minecolonies mod trough wall.when i Take off The Modern UI mod. The visual Glitch are Gonne. So i thought it will be This mod Problem Towards the other Mod. I test it on both 2.3.4.73 (1.16.4) and 2.4.2.77 (1.16.5) And 1.16.5 Have All 3 Visual Issues but the 1.16.4 only have The Bed Clipping Issues. I think This mod have conflict with Optifine. The glitch aint happening when i take both or one of the mod ( Either Optifine or Modern UI ). 

To Reproduce : 
Place Bed in a house, Or surrounding it with any type of block

Screenshots
1.16.5 (2.4.2.77)
https://cdn.discordapp.com/attachments/728157788496461866/804502806723035137/unknown.png

1.16.4
https://cdn.discordapp.com/attachments/728157788496461866/804498643948011540/unknown.png
https://cdn.discordapp.com/attachments/728157788496461866/804498088748253244/unknown.png

while Having this issues. I have Minecolonies, Structurize, 
Optifine HD U G5 and Modern UI Version 2.3.4.73-universal or 2.4.2.77 ( I Swap this around in order to check if the latest one Has the same issues or not)

**Comment by BloCamLimb** [comment]
Turn off OptiFine `Fast Render`
