### ISSUE TITLE
[Bug] Font texture packs is not support.

### ISSUE THREAD

**Issue by EnTIv** [BloCamLimb/ModernUI#52]
should ![image](https://user-images.githubusercontent.com/38716516/106704506-39897700-6627-11eb-90f1-116ad50aa8de.png)

but ![image](https://user-images.githubusercontent.com/38716516/106704606-5faf1700-6627-11eb-88ee-a0f400654da8.png)

```json
        {
            "ascent": 7,
            "chars": [
                "ꐇ"
            ],
            "file": "ui/vip.png",
            "height": 7,
            "type": "bitmap"
        },
```

**Comment by BloCamLimb** [comment]
Bitmap fonts are not supported since it does not contain writing scripts and is not vectorized, so it mostly was applied to Latin based languages

**Comment by BloCamLimb** [comment]
If you want a "picture" inline a text, there's a developing API for it
