### ISSUE TITLE
[Bug] Video Settings Menu Button is Disabled

### ISSUE THREAD

**Issue by HipHopHuman** [BloCamLimb/ModernUI#53]
**Describe the bug**
The "Options" -> "Video Settings" button in the Main Menu and Pause Menu is disabled when ModernUI is installed.

**To Reproduce**
1. Install ModernUI
2. Start Minecraft
3. In the main menu, click "Options"
4. In the "Options" menu, click "Video Settings"

**Expected behavior**
When clicking the Video Settings button, I expect to be taken to the Video Settings menu.

**Actual Behavior**
When clicking the Video Settings button, nothing happens.

**Screenshots**
N/A

**Environment**
 - Mod Version: 1.16.5-2.4.4.79
 - Forge Version: 36.0.15
 - Operating System: Windows 10 Professional
 - Graphics Card: MSI GTX 1060 6GB Overclocked Edition
 - Other Mods: None.

**Comment by BloCamLimb** [comment]
I can't reproduce

**Comment by HipHopHuman** [comment]
I did have other mods in the instance but I disabled all of them while narrowing down the issue, and all that was left enabled was ModernUI. Java version is 1.8.0_261

**Comment by BloCamLimb** [comment]
Could you post a full `logs/debug.log` of your current instance on the last run?

**Comment by HipHopHuman** [comment]
Sorry, I've been a bit busy the last two days. I've been diving into this more and made a fresh instance with all the same mods and the issue does not occur. I guess it is just an artefact of me adding/removing mods. It definitely goes away when I uninstall ModernUI though, so there is that. I will get back to you if/when I encounter this on a fresher instance

**Comment by HipHopHuman** [comment]
@BloCamLimb Hello again, I found the source of the issue. It only happens if TipTheScales is, or at some point was, installed alongside ModernUI.

**Comment by BloCamLimb** [comment]
We include all features that TipTheScales has, and also make these compatible with OptiFine, so you do not need it.
