### ISSUE TITLE
Java 11 Required?

### ISSUE THREAD

**Issue by papaworld** [BloCamLimb/ModernUI#54]
MC             1.16.5
FML            36.0.42
ModernUI   ModernUI-1.16.5-2.4.5.80-universal

Hi, updated to the above ModernUI version... Received the following Game Launch Error:

Modern UI: Java 11.0.9 or above is recommended, your version is Jave 1.8.0_281. Upgrade to newer Java and choose it to launch game, otherwise you cannot use external fonts or will not always get correct text layouts.

ModernUI 2.4.4.79 worked fine with Java 8... is Java 11 now required?

**Comment by BloCamLimb** [comment]
Not exactly, Java 11 or above is recommended, if you don't expect to the warnings, you can change forge's config `/config/forge-client.toml` -> `showLoadWarnings = false`

**Comment by papaworld** [comment]
Thank you for your response. I loaded a test world... all seems fine. I'll take your advice about the config FML warnings thingie.

BTW: Modern UI works very well, looks good and plays well also. ThanX Much!!

**Comment by BloCamLimb** [comment]
But it will not work fine with some languages such as Bengali

**Comment by papaworld** [comment]
Tried the FML showLoadWarning=false... didn't like the results because some warnings for other issues do not display. So, I turned it back to true.

Is it possible to have the Java 11 warning a "one time event" or "do  not display again"? It's annoying enough that MC and FML includes their warnings... "Here be Dragons" and "I know what I'm doing".

Thank you for your consideration.

**Comment by BloCamLimb** [comment]
It's done

**Comment by zanecek** [comment]
Same problem, same solution. I reinstalled older version too...

**Comment by BloCamLimb** [comment]
Update to 2.4.6

**Comment by papaworld** [comment]
Thank you for your update... Nice!!!
