### ISSUE TITLE
[Bug] Using the "#" symbol with REI appears to cause massive lag spikes and stuttering when opening any menu.

### ISSUE THREAD

**Issue by dmsw0303** [BloCamLimb/ModernUI#56]
**Describe the bug**

**To Reproduce**
1. Open up REI / your inventory.
2. In the REI search field, use the pound symbol to search tags.
3. Sometimes it'll let you get a couple letters in after that, sometimes it'll start immedietly after using the symbol. It typically hangs for up to 30 seconds or a minute. If you close out of the inventory while the pound symbol is still there you'll get this horrible stutter every time you open or interact with anything that has an interface.

**Expected behavior**
Use search field properly without lag or stuttering.

**Environment**
 - Mod Version: 2.4.7.82
 - Forge Version: 36.1.0
 - Operating System: Windows 10
 - Graphics Card: Amd rx 570
 - Other Mods: Over 120, but I haven't had a single issue with REI up until I installed this mod. I've used pound thousands of times without a single issue.

I also had a crash log from this issue where Modern UI was identified as the specific culprit. Unfortunately this log is not even in my folder anymore for whatever reason, think it was overridden.

**Comment by BloCamLimb** [comment]
Disable Modern UI tooltip style `/config/ModernUI/client.toml -> tooltip -> enable = false`

**Comment by dmsw0303** [comment]
This was already disabled for me actually, it's one of the first things I did when downloading the mod. Problem still persists.

**Comment by BloCamLimb** [comment]
Some pixel fonts may result in unexpected behaviours

**Comment by dmsw0303** [comment]
ah yeah that might explain it, im using 04b03 so you hit the nail on the head. well ill look into it thank you
