### ISSUE TITLE
[Bug] CRASH!

### ISSUE THREAD

**Issue by lazytspo** [BloCamLimb/ModernUI#58]
**Describe the bug**
I installed this mod, and i run this game. when i try to get to a warning screen, it crashes whilst rendering overlay. a log: https://pastebin.com/jB8aX0Lc

**To Reproduce**
1. Paste the Latest Version of Modern UI on Minecraft mods folder
2. Run the game till you reach a warning screen
3. See error

**Expected behavior**
To reach the mods warning screen

**Environment**
 - Mod Version: 1.16.5-2.4.7.82
 - Forge Version: 36.0.1
 - Operating System: Windows 10 Pro for Workstations
 - Graphics Card: GIGABYTE R9 380 WindForce 2X OC
 - Other Mods: Physics Mod, OpenComputers II, and more

**Comment by BloCamLimb** [comment]
You must provide latest `debug.log` as well

**Comment by BloCamLimb** [comment]
This issue has been closed because it has not been updated for a long time.
