### ISSUE TITLE
Linux下运行的问题

### ISSUE THREAD

**Issue by Puqns67** [BloCamLimb/ModernUI#60]
Minecraft版本：1.16.5
Mod版本：2.5.0.85
Forge版本： 36.1.13
Optifine版本：G7
显卡：AMD RX 590 GME

启动客户端无报错，进入游戏后打开背包栏等UI时报错
OpenGL错误：2 (GL_INVALID_OPERATION in glUseProgram(program 8 not linked))

完整日志: https://paste.ubuntu.com/p/CxwFM8gkg7/

**Comment by Puqns67** [comment]
另一个日志：https://drive.google.com/file/d/1dhIKGHPe1VKuWKNiQ7pfGAAkcJOBtAWs/view?usp=sharing

**Comment by BloCamLimb** [comment]
这个日志信息不够，加入我的Discord服务器，我给你一份内部版本做进一步测试。

**Comment by Puqns67** [comment]
没啥用了，Close了
