### ISSUE TITLE
[Bug] Blurry screen when in Hats GUI screen

### ISSUE THREAD

**Issue by GeorgeOrwell1** [BloCamLimb/ModernUI#61]
**Describe the bug**
When I'm in the Hats mod's hat selection screen, the background is blurred out (see picture), similarly to when I'm in my inventory, which makes it very hard to see.
![2021-05-12_16 33 52](https://user-images.githubusercontent.com/72312697/117993689-3e557980-b340-11eb-8b3c-8c595caf5103.png)

**To Reproduce**
1. Download the Hats mod (by Ichun) with this mod.
2. Open the hat selection GUI screen (default "h") and go through the tutorial.
3. When in the GUI, the background is blurred out.

**Expected behavior**
I expect the background of the GUI to simply not be blurry.

**Screenshots**
(See the first picture.)

**Environment**
 - Mod Version: ModernUI-1.16.5-2.5.0.85
 - Forge Version: Forge 36.1.16
 - Operating System: Windows 10
 - Graphics Card: RTX 2070 SUPER
 - Other Mods: Xaero's minimap, BackTools, InventoryHud+ etcetera.

**Comment by BloCamLimb** [comment]
There are two ways:
1. Disable the blur effect for all screens
  By setting `blurEffect` to false, you will find this config in [gameDir]/config/ModernUI/client.toml
2. Add this screen into blur blacklist
  First, enable `developerMode` in `common.toml` and open the hat screen, then press Ctrl+P, there will be the screen class name in the `logs/debug.log`, and copy the class name to `blurBlacklist` in 'client.toml'

**Comment by BloCamLimb** [comment]
I will add a shortcut to auto complete method 2 in the next version.

**Comment by GeorgeOrwell1** [comment]
> 
> 
> There are two ways:
> 
>     1. Disable the blur effect for all screens
>        By setting `blurEffect` to false, you will find this config in [gameDir]/config/ModernUI/client.toml
> 
>     2. Add this screen into blur blacklist
>        First, enable `developerMode` in `common.toml` and open the hat screen, then press Ctrl+P, there will be the screen class name in the `logs/debug.log`, and copy the class name to `blurBlacklist` in 'client.toml'

Thanks! Now it works!
