### ISSUE TITLE
[Error] OpenGL error

### ISSUE THREAD

**Issue by ruvaldak** [BloCamLimb/ModernUI#65]
Logspam while using latest built version as of commit 76e948e

`[Thread-21/ERROR] [ModernUI/OpenGL]: (API|Error|0x502) GL_INVALID_OPERATION error generated. No active program.`

repeats constantly. ~~No visible issues though.~~ worlds cannot boot, MC freezes & stops responding upon loading. ~~May be an issue related to Optifine+shaders.~~ Problem persists when run alone alongside Forge. Issue is not present in 88f5501, but is present in b1e82c1 and later.

**Comment by BloCamLimb** [comment]
Because the old one (CanvasForge) has been deprecated, the new GLCanvas is introduced. I'm refactoring it, so you cannot launch the game for the time being.
