### ISSUE TITLE
[Bug] Modern UI 与 体素地图VoxelMap有冲突导致字体撕裂

### ISSUE THREAD

**Issue by KobuChi886** [BloCamLimb/ModernUI#66]
Minecraft：1.16.5
Forge：36.1.32
OptiFine：HD_U_G8
模组版本：ModernUI-1.16.5-2.5.1.86
模组版本：forgemod_VoxelMap-1.10.12_for_1.16.5
测试在一个只有Modern UI 和 体素地图VoxelMap的客户端打开进入游戏字体就有撕裂的效果了

**Comment by BloCamLimb** [comment]
Extension layer is not the core of Modern UI, this issue will be deferred

**Comment by BloCamLimb** [comment]
This issue can't be solved on my side, since VoxelMap is closed source.
