### ISSUE TITLE
[Bug] REI（Forge）在安装此模组的情况下，在每次重新打开可使REI出现的GUI中首次搜索会造成大量卡顿

### ISSUE THREAD

**Issue by Peakstep233** [BloCamLimb/ModernUI#69]
**Describe the bug**
如题，在加装JECh时卡顿更甚。

**To Reproduce**
1. 随便打开一个可使REI出现的GUI（如工作台）
2. 随便在搜索栏里输入一些字符
3. 游戏即刻未响应——（Peakstep233.exe已停止运行）

**Expected behavior**
像吃了德芙一样流畅运行

**Screenshots**
az，没有

**Environment**
 - Mod Version: 1.16.5-2.5.1.86
 - Forge Version: 1.16.5 36.1.32
 - Operating System: Windows 10 专业版（21H1）
 - Graphics Card: Nvidia GeForce GTX 1060 3GB
 - Other Mods: Create, Origins (Forge), Ice and Fire, Artisan Worktables 1.16, REI, JECh, IguanaTweaks Reborn, Open Loader以及一大堆模组（以Create为中心）

**Comment by BloCamLimb** [comment]
REI的问题
