### ISSUE TITLE
Licencing Query

### ISSUE THREAD

**Issue by FreneticScribbler** [BloCamLimb/ModernUI#7]
Your readme states the licence as 'All Rights Reserved' with your explicit terms, but you have a LICENSE file in the repo that indicates the repo is GPL, which allows people to redistribute sources and jars, and reuse the code any way they like.

Just wondering which of these is the one you actually intend to apply. (I _think_ the specific terms in the readme would override the licence anyway, but I'm definitely not a lawyer!)

**Comment by BloCamLimb** [comment]
I updated readme just now, there should be no doubt

**Comment by BloCamLimb** [comment]
'All Rights Reserved' is not related to the license, and I explained the license in readme
