### ISSUE TITLE
出现超大量的错误日志，重复同一个错误信息。

### ISSUE THREAD

**Issue by RuggedTime** [BloCamLimb/ModernUI#70]
[Render thread/INFO] [ModernUI/]: OpenGL debug message: GL_INVALID_VALUE
Source: API
Type: Error
Severity: High
Message: GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.

可以正常游玩，但是日志内无穷无尽的重复本条错误消息。
![image](https://user-images.githubusercontent.com/46664847/125291329-d88f6900-e353-11eb-9163-a1a1a99220c6.png)

**Comment by BloCamLimb** [comment]
这个日志已经被我关了（但没发布最新版），OpenGL的错误不一定是哪个Mod引起的
