### ISSUE TITLE
[Suggestion] Adjust color of the blur

### ISSUE THREAD

**Issue by ruvaldak** [BloCamLimb/ModernUI#71]
Would be great if we could change the color/gradient of the background blur when in a UI. I'm working on a UI resource pack that looks best with a white-tinted background rather than a black-tinted, and the blur mod for forge seems to be rather broken, and it's color adjustments don't function.

**Comment by BloCamLimb** [comment]
Good idea

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI/commit/47f921dc5efa6e563fcc06df3940bf6869d9743b
