### ISSUE TITLE
[Bug] ModernUI's font effect is incompatible with Immersive Engineering's Engineer's Manual 

### ISSUE THREAD

**Issue by mcBegins2Snow** [BloCamLimb/ModernUI#74]
**Describe the bug**
ModernUI's font effect(font type and font smooth) is incompatible with Immersive Engineering's Engineer's Manual.

**To Reproduce**
1. Run MC with ModernUI and Immersive Engineering;
2. Create and enter a creative mode world;
3. Use an Engineer's Manual;

**Expected behavior**
The font effect should be changed.

**Screenshots**
![2021-09-03_13 09 44](https://user-images.githubusercontent.com/37864486/131953619-73a9d040-1924-49d8-96bd-4dec541fdf53.png)

**Environment**
 - Mod Version:2.5.1.86
 - Forge Version:36.2.4
 - Operating System:win10x64
 - Graphics Card:NVIDIA GeForce GTX 1050
 - Other Mods:Immersive Engineering 5.0.3-138

**Comment by BloCamLimb** [comment]
I've seen that IE created a new instance without using the vanilla font renderer, so we don't provide any support. There may be an improvement later.

**Comment by BloCamLimb** [comment]
Fixed
