### ISSUE TITLE
Entity  Renders through blocks [Bug] 

### ISSUE THREAD

**Issue by NomadicVoyager** [BloCamLimb/ModernUI#75]
**Describe the bug**
Entities Can be seen through Walls/Floors. This mainly happens with the Tombstone Mod Made by Corail

**To Reproduce**
1. Be near a loot chest or other entity 
2. Have the entity not be visible
2. Have Something In Inventory 
3. Die

**Expected behavior**
Blocks and entities Should not be seen through walls 

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot (8)](https://user-images.githubusercontent.com/71002087/132801139-4821a9f7-63e9-45e0-b041-c9258b445dd9.png)
![Screenshot (9)](https://user-images.githubusercontent.com/71002087/132801146-bd833e7a-fea4-4735-a3ab-6f6711224819.png)

**Environment**
 - Mod Version: ModernUI-1.16.5-2.5.1.86
 - Forge Version: 1.16.5
 - Operating System: Windows 10
 - Graphics Card: Intel UHD Graphics, NVIDIA GeForce GTX 1050 
 - Other Mods: 
Corail Tombstone 6.5.2 for 1.16.5

**Comment by BloCamLimb** [comment]
You don't read the notes on CurseForge. Duplicated of #20
