### ISSUE TITLE
[Bug] Crash seeming to involve the blur handler

### ISSUE THREAD

**Issue by Corvus20** [BloCamLimb/ModernUI#76]
**Describe the bug**
Game crashes if I open the inventory, and according to the crash logs, it is caused by the blur handler.

**To Reproduce**
1. Press the "E" key to open the inventory.
2. Crash should occur instantly
3. Open the crash report

**Expected behavior**
I expected it not to crash when I opened my inventory.

**Screenshots**
N/A

**Environment**
 - Mod Version:  ModernUI-1.16.5-2.6.0.88
 - Forge Version: Forge 36.2.4 for 1.16.5
 - Operating System: Windows 10
 - Graphics Card: AMD RX-590 "Fatboy"
 - Other Mods:
 When in my testing instance to reproduce the problem, the mods installed were: 
-Architectury
-BetterF3
-blame
-KotlinForForge
-Observable
-Sodium Reforged (it is called "Halogen" on curseforge)

I have uploaded the crash log to a pastebin page, hopefully these will help.
https://pastebin.com/VhWfDAjK

**Comment by BloCamLimb** [comment]
Have you changed the config? Post your `.minecraft/config/ModernUI/client.toml -> blurBlacklist` and latest `/logs/debug.log`.

**Comment by Corvus20** [comment]
I have not changed the config, I even deleted it and ran it again to make a fresh one and it still crashed.

blurBlacklist = ["net.minecraft.client.gui.screen.ChatScreen"]

Debug log: https://pastebin.com/GPqTxwnM

**Comment by BloCamLimb** [comment]
All right, I found the reason.

**Comment by BloCamLimb** [comment]
Fixed https://github.com/BloCamLimb/ModernUI/commit/09af1c20ec6d2f24ae290b6a35f6751ad8aba454
