### ISSUE TITLE
[1.16.5] Loading Crash Before Main Menu Appears

### ISSUE THREAD

**Issue by Liamdude** [BloCamLimb/ModernUI#77]
**Describe the bug**
I run a large personal pack. I changed from Modern UI 86 to 88 (reproduced with 89), and received a crash at the end of loading. This crash was odd because the main menu would start to appear, but images and text looked VERY wonky. Then the game crashes immediately before the menu fully loaded. Upon reverting or running another Minecraft instance, all my resource packs were unloaded.
I then ran some personal testing, paring down my mod usage to try to isolate the issue, which I have been unable to do. I have tried loading around 1-5 mods in addition to Optifine and Modern UI (with all my resource packs loaded), and I cannot replicate the crash. I went through my entire mod list in this manner and could not get anything to cause this same crash. However, upon switching back to my full mod list, the crash returns. I am concerned that there might be a three-way conflict, so I will try some more testing, but when this crash occurs, it is extremely annoying to rebuild the environment because I have to reset my resource pack list.
The error also seems unclear because it says that there is an invalid file format on something. I would fix this myself, but the crash does not seem to state _specifically_ what is causing the crash.

**To Reproduce**
Steps to reproduce the behavior (the following is not that helpful):
1. Load personal pack
2. Wait until end of loading
3. Crash happens before main menu fully loads

**Expected behavior**
I expected that the game would load normally given that only Modern UI has been updated. This crash does not happen with Modern UI .86 while on the same pack.

**Environment**
 - Mod Version: 1.16.5-2.6.0.88 or 1.16.5-2.6.0.89
 - Forge Version: 1.16.5 - 36.2.2
 - Operating System: Windows 10
 - Graphics Card: GeForce GTX 1650
 - Other Mods: There is a large mod list, but it includes Optifine and Performant as a warning. I am still going to try to reproduce this issue on a smaller mod list.

EDIT: Forgot all the relevant files.
Crash log: https://pastebin.com/GH3sgU3A
[latest.log](https://github.com/BloCamLimb/ModernUI/files/7173102/latest.log)
[debug.log](https://github.com/BloCamLimb/ModernUI/files/7173103/debug.log)

Another edit:
Managed to create something like the initial crash, but it was not as dangerous. Could be an issue in compatibility with Tetra and Tetrapak. This one did not fully crash, but it does show what I meant by wonky text.
Crashlog: https://pastebin.com/tm8DzyFQ
![2021-09-15_17 03 17](https://user-images.githubusercontent.com/41766967/133513890-9660afc7-b76a-403f-8f89-21acd46b9be5.png)

**Comment by BloCamLimb** [comment]
It is because the Tetra did not load successfully and has no association with the Modern UI.

**Comment by Liamdude** [comment]
Thanks for the response. I will make a report on their Github soon.

**Comment by BloCamLimb** [comment]
Fixed, https://github.com/BloCamLimb/ModernUI/commit/09af1c20ec6d2f24ae290b6a35f6751ad8aba454
