### ISSUE TITLE
[Bug] Mekanism machine tooltips are misaligned

### ISSUE THREAD

**Issue by Desempregago** [BloCamLimb/ModernUI#78]
Modern UI 2.6.2.90

![2021-09-16_05 04 37](https://user-images.githubusercontent.com/14002834/133574655-9928914e-4cb3-4c2d-8d9a-f040a9636650.png)

**Comment by BloCamLimb** [comment]
This should be fixed by Mekanism 1.17.

**Comment by BloCamLimb** [comment]
Fixed in 2.6.3

**Comment by Desempregago** [comment]
Something happened after the update

Before
![2021-09-16_06 20 23](https://user-images.githubusercontent.com/14002834/133861941-f0bbacb0-4783-4736-983e-4aec61538888.png)

After
![2021-09-17_19 55 56](https://user-images.githubusercontent.com/14002834/133861938-8a69fc13-877a-4858-a9d8-d61f22babaa1.png)

Mekanism UIs are now working properly, though

**Comment by BloCamLimb** [comment]
What is this (mod)?

**Comment by Desempregago** [comment]
bpm (Blueprints), a Steve's Factory Manager-esque mod for 1.16

**Comment by BloCamLimb** [comment]
There is no guarantee to support all mods, especially the replaced tooltip rendering. I can only guarantee that most mods developed using Minecraft vanilla and Forge can work well, excluding those using mixin or directly calling the underlying graphics API. But don't worry, I will separate these functions (i.e some of its compatibility layer and extension layer) in 1.17, and users can customize them according to their needs.
