### ISSUE TITLE
[Suggestion] Add an option to disable font antialiasing

### ISSUE THREAD

**Issue by LTCatt** [BloCamLimb/ModernUI#79]
I went out of my way to find a pixel style font, but it looks terrible due to antialiasing...
I think it would be nice if has an option to turn off it! :D

**Comment by BloCamLimb** [comment]
This caused a lot of problems, so I removed the option permanently.

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI/commit/77f833ee2e532a178296e11da32ab0ee25987d1c Added
