### ISSUE TITLE
[Bug] Empty Tooltip

### ISSUE THREAD

**Issue by CepheidVariable** [BloCamLimb/ModernUI#82]
**Describe the bug**
Empty tooltip boxes display for items in inventory.

**To Reproduce**
1. Hover over items in inventory screen.

**Expected behavior**
A tooltip to appear with information in it.

**Screenshots**
![2021-10-16_13 10 06](https://user-images.githubusercontent.com/75629045/137597921-6666716a-85a3-4a45-8c2c-8928947b6781.png)

**Environment**
 - Mod Version: ModernUI-1.17.1-3.0.0.93
 - Forge Version: Forge 37.0.95
 - Operating System: Manjaro (arch x64)
 - Graphics Card: Rtx2060
 - Other Mods: None

**Comment by BloCamLimb** [comment]
This is due to the change of forge. You can back to the Forge version below 37.0.85 but above 37.0.70, or wait for my fix.
