### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [BloCamLimb/ModernUI#83]
**Describe the bug**
Crash log: https://hastebin.com/ebabivuqom.properties

**To Reproduce**
1. Launch the game
2. I'm Minecraft, and I am a crashaholic.

**Expected behavior**
Stop crashing

**Environment**
 - Mod Version: 1.17.1
 - Forge Version: 37.0.95
 - Operating System: Windows 11
 - Graphics Card: GEFORCE GTX 1650
 - Other Mods: See the crash log

**Comment by BloCamLimb** [comment]
The crash log doesn't show the mod list. This issue may be caused by unsuccessful loading of other mods. You need to provide a complete debug log (/logs/debug.log).

**Comment by ChromaPIE** [comment]
> The crash report doesn't show the mod list. This issue may be caused by unsuccessful loading of other mods. You need to provide a complete debug log (/logs/debug.log).

The crash happens only when launching Minecraft through Minecraft Launcher called by CurseForge app. I've tried with ATLauncher and the problem was gone. The issue will be closed but if you still want the debug log say it and I'll have another try with that and get the log cuz I've already deleted that profile.
