### ISSUE TITLE
[Bug] ModernUI 1.16.5 crashes even with Java 1.8.0_311

### ISSUE THREAD

**Issue by Modehz** [BloCamLimb/ModernUI#85]
**Describe the bug**
The game crashes with Java 1.8.0_311, but a minimum of Java 1.8.0_201 as said in the FAQ is required to suppress the crash, and it does not show you a warning.

**To Reproduce**
1. Click on 'Play' with the Modern UI 1.16.5 in Java 1.8.0_311
2. See error

**Expected behavior**
The FAQ say: "A minimum of java 1.8.0_201 is required to suppress the error or warning, java 11.0.9 or above is recommended, and whatever game launcher you are using you must let it use the java you updated rathen than the built-in one or auto-download one. (Since 2.4.4, it will show a warning rather than crashing game, if you don't want to see the warning, change /config/forge-client.toml)". So i should be able to play, since i´m using Java 1.8.0_311.

**Log**
[latest.log](https://github.com/BloCamLimb/ModernUI/files/7388438/latest.log)

**Environment**
 - Mod Version: ModernUI-1.16.5-2.6.4.92
 - Forge Version: 36.2.8
 - Operating System: Windows 10 Pro 21H1
 - Graphics Card: R7 260x - OpenGL 4.6
 - Other Mods: OptiFine_1.16.5_HD_U_G8

**Comment by BloCamLimb** [comment]
Yes, we no longer support Java 10 or below. I just forgot to update curseforge page, but I mentioned it in the changelog.
