### ISSUE TITLE
[Question] How to turn off font changes?

### ISSUE THREAD

**Issue by KKotik** [BloCamLimb/ModernUI#89]
I am using the mod only for lur effect, because it is well optimized. How can I turn off font changes?

**Comment by BloCamLimb** [comment]
That extension part will be separated in the future 1.18, there was no definite method of preventing the loader from injecting codebase for modern text system. However, you can find a bitmap font (must be a TrueType Font) and configure something in the config. For further technical support, join my discord server.

**Comment by sepsol** [comment]
I second this, wish the blur module was separate

**Comment by sepsol** [comment]
I tried turning off the "font engine" via the in-game config but it seemed like after restarting the game, the default font was not brought back. I'll give it another try, maybe it has something to do with the way multi-monitor setups are handled in Windows 11. Also just wanted to let you know that the mod worked absolutely fine with the "Controlling" mod despite what you have mentioned on the Curseforge.

**Comment by BloCamLimb** [comment]
You should also turn off Force Unicode Font in vanilla language settings

**Comment by ProxyPlayerHD** [comment]
wait there is an in-game config? where? how do you access that?
the curseforge page doesn't mention it and i was unable to find it anything in any of the option menus or even the config files to directly disable the text engine...
also when you said "most features are configurable", which ones can't be disabled?

**Comment by BloCamLimb** [comment]
> wait there is an in-game config? where? how do you access that? the curseforge page doesn't mention it and i was unable to find it anything in any of the option menus or even the config files to directly disable the text engine... also when you said "most features are configurable", which ones can't be disabled?

In-game config: Press Ctrl+K to open (1.18.2 only)

Config folder: [gameDir]/config/ModernUI/
Text Engine is controlled by bootstrap level

Non Configurable:
1. Modern UI modifies GUI scale algorithm.
2. Modern UI changes GUI scale widget from Cycle to Slider.

**Comment by ProxyPlayerHD** [comment]
thank you, that worked!
though i recommend mentioning the keybind on the curseforge page (or more obvious if it is mentioned and i just didn't find it) or making the in-game config accessable without the need for a keybind (for example an extra button in the main/pause menu like Quark).
