### ISSUE TITLE
[Bug] Game crashes on startup 1.18.1 

### ISSUE THREAD

**Issue by Theoretical-Enday** [BloCamLimb/ModernUI#90]
Forge 39.0.17 Optifine HD_U_H4 Game 1.18.1 ModernUI-1.18-3.2.0.97
[crash-2022-01-11_14.38.30-client.txt](https://github.com/BloCamLimb/ModernUI/files/7843983/crash-2022-01-11_14.38.30-client.txt)

**Comment by BloCamLimb** [comment]
Have you ever entered the main menu?

**Comment by Theoretical-Enday** [comment]
No,i don't entered main menu,i crash in startup loading.Thank you help me,i see other mods crash in debug.log,sorry for disturbing you.
