### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by keepinitreal247** [BloCamLimb/ModernUI#92]
**Describe the bug**

**To Reproduce**
1. Go Minecraft launcher
2. Click on the play button
3. See error

**Expected behavior**
the game to load fully

**Screenshots**

**Environment**
 - Mod Version:[ModernUI-1.16.5-2.6.4.92]
 - Forge Version:36.3.21
 - Operating System:Windows 10
 - Graphics Card:GeForce RTX
 - Other Mods:https://gist.github.com/keepinitreal247/7c1942f207a5c7d9ecf644bf5b949ef4

**Comment by BloCamLimb** [comment]
It's not a bug, I made it clear in the instructions that you must use Java 11 or above to run.

Java requirements:
Java 17\~18 (Minecraft 1.18)
Java 16\~17 (Minecraft 1.17)
Java 11\~15(16) (Minecraft 1.16) <- Java 16 requires some extra args
Java 8\~15 (Minecraft 1.15)

**Comment by keepinitreal247** [comment]
> It's not a bug, I made it clear in the instructions that you must use Java 11 or above to run.
> 
> Java requirements: Java 17~18 (Minecraft 1.18) Java 16~17 (Minecraft 1.17) Java 11~15(16) (Minecraft 1.16) <- Java 16 requires some extra args Java 8~15 (Minecraft 1.15)

ahhh ok I see my bad how do you go back to version 11?
