### ISSUE TITLE
java 11

### ISSUE THREAD

**Issue by Senne98** [BloCamLimb/ModernUI#93]
**Describe the bug**
minecraft 1.16 doesnt work with java 11, but modern ui needs it

**To Reproduce**
use java 11 to not run minecraft
and java 8 to crash because of modern ui

**Expected behavior**
not crash

**Screenshots**
https://gist.github.com/Senne98/56f3e1e5fbaf0059e47e33316c0dac50

**Environment**
 - Mod Version: ModernUI-1.16.5-2.6.4.92-universal.jar
 - Forge Version: 36.2.21
 - Operating System: windows
 - Graphics Card: mobile rtx 3050
 - Other Mods: 
![image](https://user-images.githubusercontent.com/94780127/156252598-2b60d8b2-5500-4ec8-a6e1-5360d31c5f7a.png)
![image](https://user-images.githubusercontent.com/94780127/156252661-aeb25443-8b27-4083-99a2-e1953e589ee9.png)
![image](https://user-images.githubusercontent.com/94780127/156252695-b24c3635-f31c-44a1-bc8f-6dc93be74357.png)
![image](https://user-images.githubusercontent.com/94780127/156252733-edd04dfc-79cb-4496-b480-5dab309f3df8.png)
![image](https://user-images.githubusercontent.com/94780127/156252759-f9e2bed9-ced0-4eaa-a5dc-0821d06c858d.png)

**Comment by BloCamLimb** [comment]
Yes. But 2.5.X supports Java 8.
