### ISSUE TITLE
[Bug] crash when use the Drippy Loading Screen with 3.4.0.99 on forge39

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [BloCamLimb/ModernUI#95]
**Describe the bug**
Load failed. Game crash when loading itself
**To Reproduce**
1. Go to 'update mod'
2. Click on 'launch'
3. Scroll down to 'load screen'

**Expected behavior**
Old version [ModernUI](https://github.com/BloCamLimb/ModernUI) could run as normal with [Drippy Loading Screen](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen)
But when update the 3.4.0.99. it failed
Game crash when loading itself

**Screenshots**
[minecraft-exported-crash-info-2022-03-10T08-58-29.zip](https://github.com/BloCamLimb/ModernUI/files/8219328/minecraft-exported-crash-info-2022-03-10T08-58-29.zip)

**Environment**
 - Mod Version:3.4.0.99
 - Forge Version:39.0.79
 - Operating System: Windows 11(10.0.22563.1)

 - Graphics Card:
GTX1050ti
 - Other Mods:
Drippy Loading Screen
konkrete_forge

**Comment by BloCamLimb** [comment]
Your Forge is not up-to-date.
