### ISSUE TITLE
[Bug] Incompatibility with Legendary Tooltips

### ISSUE THREAD

**Issue by Warhand** [BloCamLimb/ModernUI#96]
**Describe the bug**
The tooltips added by legendary Tooltips are supposed to display a decorative line underneath the names of items, the text aspect of Modern UI seems to mess with this a bit, and the decorative lines either display in the wrong place or not at all, however this behavior is random, and seems to affect some items but not others.

**To Reproduce**
Install both Legendary tooltips and Modern ui, then hover over various items to observe the behavior.

**Expected behavior**
The tooltips are all supposed to display the decorative line underneath the item names, in every instance.

**Screenshots**
Broken tooltip:
![image1](https://user-images.githubusercontent.com/29134223/158210096-802e5427-b9e2-4bab-86d0-74ab1b595fba.png)

Correct tooltip:
![image2](https://user-images.githubusercontent.com/29134223/158210162-6ff59f22-36fa-420f-8cce-354d2cb76c19.png)

**Environment**
 - Mod Version:
 Legendary tooltips: 1.2.4
 Modern UI: 3.4.0.99
 - Forge Version: 39.1.2
 - Operating System: Windows 10
 - Graphics Card: Nvidia Geforce GTX 1060 6GB
 - Other Mods: https://pastebin.com/BwTVqngZ

**Comment by BloCamLimb** [comment]
Have you disabled Modern UI tooltip rendering?

**Comment by Warhand** [comment]
Yes, I have, thats why legendary tooltips is still able to display its own tooltip style

**Comment by BloCamLimb** [comment]
Will this still happen randomly after removing Modern UI?

**Comment by Warhand** [comment]
Nope, it only occurs when Modern UI is installed

**Comment by BloCamLimb** [comment]
I looked into LegendaryTooltips source code, and I'm sure it's a bug on LegendaryTooltips side. Line Wrapping is ever performed in Forge's event, and LegendaryTooltips *should not* wrap lines again, see [here](https://github.com/AHilyard/LegendaryTooltips/blob/1.18/src/main/java/com/anthonyhilyard/legendarytooltips/render/TooltipDecor.java#L131). As your screenshot shows, the first screenshot's title, is almost the same width as the whole tooltip, so the separator is drawn at the bottom of second line.

**Comment by Warhand** [comment]
After talking to the Legendary tooltips devs, they say the code you're referencing only calculates the number of lines a title should be for longer titles, and it only starts behaving weirdly because modern UI is replacing default functionality with its own.

I'm not sure which of you is right, since I'm no expert when it comes to coding, but do you think you could add an option to disable the text replacement feature of modern UI? I'd like to keep the background blur in menus, however there doesn't seem to be an option to have the latter but not the former.

**Comment by BloCamLimb** [comment]
There's already an option to disable it, just open `/config/ModernUI/bootstrap` and type "1", save in UTF-8 format
