### ISSUE TITLE
[Bug] Crash when loading game

### ISSUE THREAD

**Issue by Warhand** [BloCamLimb/ModernUI#97]
**Describe the bug**
Modern UI has suddenly started crashing after the game finishes loading and tries to open the main menu

Crash report: https://pastebin.com/N5yfyQme

This bug does not occur after downgrading to version 3.4.1.99 of the mod

**To Reproduce**
1. Install forge
2. Install modern UI
4. Load game
5. Game will crash after finishing loading

**Expected behavior**
The game should load properly and enter into the main menu,

**Environment**
 - Mod Version: 3.4.1.100
 - Forge Version: 39.1.2
 - Operating System: Windows 10
 - Graphics Card: Nvidia Geforce GTX 1060 6gb
 - Other Mods: None, this behavior can be reproduced by having a modded setup running nothing else besides modern UI

**Comment by BloCamLimb** [comment]
If shaders failed to load, as it said `null pointer`, then there should be an exception thrown to the mod launcher, you have to check in the latest `debug.log`, just paste it to here.

**Comment by Warhand** [comment]
Where would I find a debug.log? I don't see it in the same folder as latest.log

**Comment by BloCamLimb** [comment]
`/.minecraft/logs/debug.log`

**Comment by Warhand** [comment]
Yup, that's exactly where I looked, and there was no file by that name.

**Comment by BloCamLimb** [comment]
then you just paste `latest.log`

**Comment by Warhand** [comment]
Sorry about the delay, heres that log you asked for, as well as its corresponding crash report.

Latest.log: https://pastebin.com/yfipEvte

Crash report: https://pastebin.com/XR3F7sPE

**Comment by BloCamLimb** [comment]
Ok, I just mess the versioning up, 3.4.0 only runs on 1.18.1, whereas 3.4.1 only runs on 1.18.2, you have 3.4.1 on 1.18.2 so it crashes. I've fixed the supported version display on curseforge.
