### ISSUE TITLE
[Bug] Error window popup during launch

### ISSUE THREAD

**Issue by Corvus20** [BloCamLimb/ModernUI#98]
**Describe the bug**
When trying to launch a modded game with Modern UI installed, an error window titled "Failed to launch Modern UI" pops up, saying something about a certain test failing, and that I should "try to use dedicated gpu for java applications" and "update my GPU drivers", the former being confusing as I only have 1 GPU, and the latter being already done.

**To Reproduce**
1. Install Modern UI
2. Try to launch
3. Minecraft window will open, but will be completely white and go into "not responding"
4. error window will pop up and the not responding game will crash once you click "okay"

**Expected behavior**
For that not to happen. I should be able to launch the game and use the mod as intended.

**Screenshots**
The error pop up window:
![image](https://user-images.githubusercontent.com/75586106/160254370-6f25f91f-019a-45ae-8998-d1656612d2ba.png)

GDLauncher crash explanation:
![image](https://user-images.githubusercontent.com/75586106/160254392-77b14e62-f420-457c-9531-caf2eb0ed3ec.png)

**Environment**
 - Mod Version: 1.18.2-3.4.1.100
 - Forge Version: 40.0.32 for 1.18.2
 - Operating System: Windows 10
 - Graphics Card: AMD XFX RX 590 "Fatboy"
 - Other Mods: First encountered the error in my personal modpack instance of 180 mods, but testing in an instance with just modern ui results in the same error.

Crash log:
[crash-2022-03-26_15.32.16-client.txt](https://github.com/BloCamLimb/ModernUI/files/8356220/crash-2022-03-26_15.32.16-client.txt)

**Comment by BloCamLimb** [comment]
It's already a known issue, and already got fixed

**Comment by BloCamLimb** [comment]
Release 3.4.2
